### ISSUE TITLE
Spelling @ aspnetzero.com - "codes"

### ISSUE THREAD

**Issue by kayagultekin** [aspnetboilerplate/module-zero#100]
Now that I have seen a spelling correction on issues I can state my first finding among all other :)

1. at "What is ASP.NET ZERO? " section and at "Pricing" section at http://www.aspnetzero.com/#pricing 
"Full source codes"  needs to be replaced with: "Full source code"

2. at "How it works?" > "Develop your application", "Start to developing your application! " sentence should be : Start developing your application! 

By the way thanks for the great job. I am coming from web forms with 10+ years experience and seeing your project I am thinking to switch to ABP and I have been observing your repositories for about at least 6 months. I hope I can use it and contribute to it effectively.

Conratulations on your job decision.

Be well..

**Comment by hikalkan** [comment]
Thank you very much for corrections. I'll apply them :)

**Comment by hikalkan** [comment]
Fixed it. Thanks again.

**Comment by kayagultekin** [comment]
Pricing table needs three instances of "Full source codes" that  needs to be replaced with: "Full source code"

You're very welcome..

**Comment by hikalkan** [comment]
Fixed it too :)
