### ISSUE TITLE
Implementing Token Authentication

### ISSUE THREAD

**Issue by emaish** [aspnetboilerplate/module-zero#103]
Dear,
i want to be able to authenticate calls from Native mobile application, so i searched and found that it's possible easily with Token Authentication, i found a simple article [ASP.NET Identity 2.0 Cookie & Token Authentication](http://blog.iteedee.com/2014/03/asp-net-identity-2-0-cookie-token-authentication/) describe how to do that, unfortunately i didn't find WebApiConfig to complete the steps :(, could you help me.

Thanks

**Comment by emaish** [comment]
i tried Configuration.Modules.AbpWebApi().HttpConfiguration but AbpWebApi() not found

**Comment by hikalkan** [comment]
If you add namespace Abp.Configuration.Startup and use the latest ABP, it should be visible.

**Comment by emaish** [comment]
i solved it like this, in the WebApiModule 
```C#
        public override void Initialize()
        {
            var httpConfiguration = IocManager.Resolve<IAbpWebApiModuleConfiguration>().HttpConfiguration;
            //httpConfiguration.SuppressDefaultHostAuthentication();
            httpConfiguration.Filters.Add(new HostAuthenticationFilter("Bearer"));
            .........
        }
```

**Comment by hikalkan** [comment]
OK, actually they are same but I could not understand why you could not see that extenson method.

**Comment by emaish** [comment]
after you mentioned it,i see the extension method with no problem, but i couldn't know how to call it in the WebApiModule.

**Comment by hikalkan** [comment]
Not all configuration of ABP documented. But I rely on intellisense (and resharper). Just type Configuration. and see all options :)
