### ISSUE TITLE
External Authentication Sources

### ISSUE THREAD

**Issue by Caskia** [aspnetboilerplate/module-zero#104]
Hi,
I want to use facebook login in my application.So I use TryLoginFromExternalAuthenticationSources(AbpUserManager.cs) method to login in.But I found out that in this method there have a ExternalAuthenticationSources need to config.I check the source this need to inherit from IExternalAuthenticationSource.
Can you give me a example that how to implement the IExternalAuthenticationSource's method.

Thanks a lot

**Comment by hikalkan** [comment]
Hi,

External Authentication Source concept not appropriate for social logins.
you can get a reference the link http://www.asp.net/mvc/overview/security/create-an-aspnet-mvc-5-app-with-facebook-and-google-oauth2-and-openid-sign-on as a startup point.
But I will implement social logins for module-zero in a very short time. You can follow this issue: https://github.com/aspnetboilerplate/module-zero-template/issues/5

**Comment by Caskia** [comment]
^_^

Look forward to your updates

**Comment by hikalkan** [comment]
I implemented it but not published the template yet. If it's urgent for you, you can check https://github.com/aspnetboilerplate/module-zero-template/ to see how it's implemented.

**Comment by emaish** [comment]
Thank you for your efforts.
You mentioned bearer authentication, how to return the created bearer token to use it later in the request header in native mobile http requests? And will you publish the template soon with external authentication?

**Comment by hikalkan** [comment]
Mobile app calls Authenticate method, gets the token and uses in the header for next calls. I followed http://bitoftech.net/2014/06/01/token-based-authentication-asp-net-web-api-2-owin-asp-net-identity/ to implement it.
New template version will include social media auth and bearer token auth.

**Comment by tiandao-dongguan** [comment]
we can use identityserver3 implemented  token webapi ,here is github:https://github.com/IdentityServer/IdentityServer3.Samples ;by the way,it is very easy to use!

**Comment by tiandao-dongguan** [comment]
how to use it ?you can read this article,this is a MVC Authentication & Authorization example :https://identityserver.github.io/Documentation/docsv2/overview/mvcGettingStarted.html
