### ISSUE TITLE
Abp.Zero - upgrade from 0.6.6 to 0.6.9 or 0.7.0.4 gives errors

### ISSUE THREAD

**Issue by Znow** [aspnetboilerplate/module-zero#106]
Hi

Tried updating my nuget packages for my project today, all though I got some errors.

Tried first upgrading from 0.6.6 -> 0.6.9, got errors.
Then I tried to upgrade to latest stable 0.7.04, still got errors.

Had to downgrade to 0.6.6 again to get the solution working again...

![image](https://cloud.githubusercontent.com/assets/265719/9783707/b4f0de0a-57a6-11e5-81b4-fa875c888c72.png)

All other Abp nuget packages updated fine.

**Comment by hikalkan** [comment]
See release notes:
https://github.com/aspnetboilerplate/module-zero/releases/tag/v0.6.9.0

On Thu, Sep 10, 2015 at 11:33 AM, Daniel <notifications@github.com> wrote:

> Hi
>
> Tried updating my nuget packages for my project today, all though I got
> some errors.
>
> Tried first upgrading from 0.6.6 -> 0.6.9, got errors.
> Then I tried to upgrade to latest stable 0.7.04, still got errors.
>
> Had to downgrade to 0.6.6 again to get the solution working again...
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/265719/9783707/b4f0de0a-57a6-11e5-81b4-fa875c888c72.png>
>
> All other Abp nuget packages updated fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aspnetboilerplate/module-zero/issues/106>.
>



-- 
Halil ibrahim Kalkan
http://halilibrahimkalkan.com/

**Comment by Znow** [comment]
Thanks :-)
