### ISSUE TITLE
UserManager.CreateAsync(TUser user, string password) issue an update before an insert

### ISSUE THREAD

**Issue by guilmori** [aspnetboilerplate/module-zero#11]
UserManager.CreateAsync(TUser user, string password) seems to call UserStore.SetPasswordHashAsync() before calling UserStore.CreateAsync().
Since AbpUserStore.SetPasswordHashAsync() is calling_userRepository.Update(user), it raise an exception because the user has not been inserted yet.

To fix, I added this check inside AbpUserStore.SetPasswordHashAsync():
if(user.Id > 0) _userRepository.Update(user);

**Comment by langman66** [comment]
Thanks Guilmori for posting this issue. I spent a lot of time trying to figure out the issue the issue I was getting and putting in the fix you mentioned above resolved my issue with creating as user.

**Comment by hikalkan** [comment]
Thanks a lot for your bug report. I fixed it.

**Comment by hikalkan** [comment]
Hi,

I will check it and remove _userRepository.Update(user) if UpdateAsync is called always.
