### ISSUE TITLE
Module Zero build error

### ISSUE THREAD

**Issue by bakbuz** [aspnetboilerplate/module-zero#117]
ICacheManager missing. How can I fix. 

![ekran alintisi](https://cloud.githubusercontent.com/assets/2492378/10267303/b8ccbb44-6a97-11e5-838c-f72a58eaffea.PNG)

**Comment by hikalkan** [comment]
Have you upgraded Abp nuget package? It's defined in v0.7.1.

**Comment by bakbuz** [comment]
It's works. Thanks
