### ISSUE TITLE
Agument 1: cannot convert from 'Abp.Domain.Repositories.IRepository<X.MultiTenancy.Tenant>' to 'Abp.Application.Editions.AbpEditionManager'

### ISSUE THREAD

**Issue by Znow** [aspnetboilerplate/module-zero#118]
Hi

Just updated to Abp 0.7.3.

I'm already getting an error in Core/MultiTenancy/TenantManager.cs.

![image](https://cloud.githubusercontent.com/assets/265719/10507907/293f2dbe-7324-11e5-8f35-0cb02646f0b0.png)

![image](https://cloud.githubusercontent.com/assets/265719/10507929/4a22365c-7324-11e5-8518-60c0952d12fd.png)

Please specify these changes in your release notes, so we wont get errors like these when updating.

Kind Regards

**Comment by hikalkan** [comment]
Actually, it's very obvious that base blass waits for an EditionManager (see https://github.com/aspnetboilerplate/module-zero/releases/tag/v0.7.2.0 for EditionManager). So, remove tenantRepository and add the EditionManager instead.
OK, I will write more detailed next time.
