### ISSUE TITLE
Module zero sample application build errors

### ISSUE THREAD

**Issue by brendan-rice** [aspnetboilerplate/module-zero#119]
Hi,

I just tried to load the sample application and ran into a number of issues. I figured most of them out (by updating packages) the issue below baffles me I am not sure what is wrong:

Could not load type 'Abp.Localization.Sources.Xml.XmlEmbeddedFileLocalizationDictionaryProvider' from assembly 'Abp, Version=0.7.3.0, Culture=neutral, PublicKeyToken=null'.

XmlEmbeddedFileLocalizationDictionaryProvider has been deprecated, but I search the sample app solution code and can't find where the reference comes from I can only assume this comes from module zero. As far as I know all packages are up to date.

Can you help please?

http://screencast.com/t/1ciJiYYjs

**Comment by hikalkan** [comment]
OK, then I should upgrade the sample.
Thanks.

**Comment by brendan-rice** [comment]
Just figured it out I didn't upgrade abp.web package, that seems to have fixed it

**Comment by brendan-rice** [comment]
Thanks Halil

**Comment by brendan-rice** [comment]
I also needed to add migration and update-database Halil

**Comment by hikalkan** [comment]
It's updated and moved to it's own repository: https://github.com/aspnetboilerplate/questions-answers
