### ISSUE TITLE
Error in header.js when anonymous Page load

### ISSUE THREAD

**Issue by ddNils** [aspnetboilerplate/module-zero#123]
I would like to have a starting page with anonymous access. This is working, by setting home controller to enable anonymous access. 

Unfortunately header.js gives an error, because appSession.user is null. 

this function has the error: 
vm.getShownUserName 

I would expect to have a login possibility for anonymous users.

**Comment by hikalkan** [comment]
Hi,

It can be easily fixed. Example:

            vm.getShownUserName = function () {
                if (!appSession.user) {
                    return 'anonymous user';
                }

                if (!abp.multiTenancy.isEnabled) {
                    return appSession.user.userName;
                } else {
                    if (appSession.tenant) {
                        return appSession.tenant.tenancyName + '\\' + appSession.user.userName;
                    } else {
                        return '.\\' + appSession.user.userName;
                    }
                }
            };

But this is not the only problem. We have a dropdown on user name which is used to Logout. So, this should be also adapted. Also, HomeController has a [AbpMvcAuthorize]. There maybe some minor changes too, because this application is designed to login.

But I think you can easily change it for your needs.

**Comment by ddNils** [comment]
I did all that, what you suggested. I do get Errors on the first visit.

have a look at: https://bogasco.azurewebsites.net/#/

(that's where i test)

**Comment by hikalkan** [comment]
When I check it, I see this request send error:

https://bogasco.azurewebsites.net/api/services/app/session/GetCurrentLoginInformations

So, this method also needs login. You should check and fix it too.

**Comment by ddNils** [comment]
thanks, I am trying to disable minification of scripts when debugging, should be in System.Web.Optimization.BundleTable.EnableOptimizations = false, but can't find it :(

**Comment by hikalkan** [comment]
You can try to debug=true in web config:

<compilation debug="true"  .../>

This is removed on release normally.

**Comment by ddNils** [comment]
I found a workaround for the time being:
In SessionAppService.GetCurrentLoginInformationsOutput() - now without AbpAuthorize
            if (AbpSession.UserId.HasValue == false)
            {
                return new GetCurrentLoginInformationsOutput() {
                    User = new UserLoginInfoDto() {
                        Name = "No Name",
                        UserName = L("Login_Anonymous_UserName")
                    }
                };
            }
This is working. It's not pretty but it's ok. I will probably have to overwrite Navigation (Header) to make that work pretty as well (now Logout changed to Login via jQuery).

Thank you for leading me in the right direction :+1:

**Comment by hikalkan** [comment]
You're welcome :)
