### ISSUE TITLE
Can't log in when multi tenancy is enabled.

### ISSUE THREAD

**Issue by brendan-rice** [aspnetboilerplate/module-zero#125]
When we do the follow on the login command the user object is null, even though the correct parameters are being supplied for the FirstOrDefault method.

    user = _userRepository.FirstOrDefault(
                u =>
                    (u.UserName == loginModel.UsernameOrEmailAddress ||
                        u.EmailAddress == loginModel.UsernameOrEmailAddress)
                    && u.TenantId == tenant.Id
                );

I opened SQL profiler and looked to see what command was being issued to the db and noticed that the following parameter was NULL, meaning no results get returned.

    @DynamicFilterParam_MayHaveTenant_tenantId=NULL

Is this something to do with incorrectly configuring multitenancy?

Here is how we are turning the MultiTenancy on:

    [DependsOn(typeof(AbpZeroCoreModule))]
    [DependsOn(typeof(BaseSaaSAppDataModule), typeof(BaseSaaSAppApplicationModule), typeof(BaseSaaSAppWebApiModule))]
    public class BaseSaaSAppWebModule : AbpModule
    {
        public override void PreInitialize()
        {
           Configuration.MultiTenancy.IsEnabled = true;

**Comment by hikalkan** [comment]
Hi,

In multi-tenancy, you don't have to add Where Condition for "TenantId". ABP automatically filters current tenants. So, remove your TenantId condition. If you want to get data of a specific tenant, use SetFilterParameter.

You should read these documents to understand it:
* http://www.aspnetboilerplate.com/Pages/Documents/Data-Filters
* http://www.aspnetboilerplate.com/Pages/Documents/Zero/User-Management#user-manager

Have a nice day.
