### ISSUE TITLE
Display menu based on permissions

### ISSUE THREAD

**Issue by smooney1234** [aspnetboilerplate/module-zero#127]
I am currently trying to display only menu items that are related to each user.

superAdmin will have the menu admin - tenants
admin will have settings

Here are the permissions i have set

using Abp.Authorization;
using Abp.Localization;
using Abp.MultiTenancy;

namespace BaseSaaSApp.Authorization
{
    public class BaseSaaSAppAuthorizationProvider : AuthorizationProvider
    {
        public override void SetPermissions(IPermissionDefinitionContext context)
        {
            context.CreatePermission("SuperAdmin", new FixedLocalizableString("AdminManagement"), isGrantedByDefault: true);
            context.CreatePermission("Settings", new FixedLocalizableString("SettingManagament"), isGrantedByDefault: true);
        }
    }
}

This is the navigationprovider

using Abp.Application.Navigation;
using Abp.Localization;

namespace BaseSaaSApp.Web
{
    /// <summary>
    /// This class defines menus for the application.
    /// It uses ABP's menu system.
    /// When you add menu items here, they are automatically appear in angular application.
    /// See .cshtml and .js files under App/Main/views/layout/header to know how to render menu.
    /// </summary>
    public class BaseSaaSAppNavigationProvider : NavigationProvider
    {
        public override void SetNavigation(INavigationProviderContext context)
        {
            MenuItemDefinition adminMenuItem = GetAdminMenuItem();
            MenuItemDefinition quotesMenuItem = GetQuotesMenuItem();
            MenuItemDefinition repsMenuItem = GetRepsMenuItem();
            MenuItemDefinition settingsMenuItem = GetSettingsMenuItem();

            context.Manager.MainMenu
                .AddItem(adminMenuItem).AddItem(settingsMenuItem).AddItem(quotesMenuItem).AddItem(repsMenuItem);
        }

        private static MenuItemDefinition GetAdminMenuItem()
        {
            MenuItemDefinition adminMenuItem = new MenuItemDefinition(
                "Admin",
                new LocalizableString("SuperAdmin", BaseSaaSAppConsts.LocalizationSourceName),
                url: "#/admin",
                requiredPermissionName:"SuperAdmin",
                icon: "icon-settings");

            MenuItemDefinition tenantsMenuItem = new MenuItemDefinition(
                "Tenants",
                new LocalizableString("Tenants", BaseSaaSAppConsts.LocalizationSourceName),
                url: "#/admin/tenants",
                icon: "icon-layers"
                );

            adminMenuItem.AddItem(tenantsMenuItem);

            return adminMenuItem;
        }

        private static MenuItemDefinition GetSettingsMenuItem()
        {

            MenuItemDefinition settingsMenuItem = new MenuItemDefinition(
                "Settings",
                new LocalizableString("Settings", BaseSaaSAppConsts.LocalizationSourceName),
                url: "#/settings",
                icon: "icon-layers"
           
                );

            return settingsMenuItem;
        }

        private static MenuItemDefinition GetQuotesMenuItem()
        {

            MenuItemDefinition quotesMenuItem = new MenuItemDefinition(
                "Quotes",
                new LocalizableString("Quotes", BaseSaaSAppConsts.LocalizationSourceName),
                url: "#/admin/quotes",
                icon: "icon-layers"

                );

            return quotesMenuItem;
        }

        private static MenuItemDefinition GetRepsMenuItem()
        {

            MenuItemDefinition repsMenuItem = new MenuItemDefinition(
                "Reps",
                new LocalizableString("Reps", BaseSaaSAppConsts.LocalizationSourceName),
                url: "#/admin/reps",
                icon: "icon-layers"

                );

            return repsMenuItem;
        }
    }
}

Currently if i add requiredPermissionName to any menu item it will display none at all.
If i remove them it will display all menu items.

Would appreciate your help, thanks

**Comment by hikalkan** [comment]
Hi,

"Currently if i add requiredPermissionName to any menu item it will display none at all."

Have you granted access for permissions?

**Comment by smooney1234** [comment]
Hi,

Yes the isGranted property is set to true in the seed method and shows in the database

**Comment by hikalkan** [comment]
Hi,

Your code seems fine. What do you get when you call PermissionChecker.IsGranted("SuperAdmin")?
Also, remember that you should login.

**Comment by smooney1234** [comment]
There is an isGranted field in the permissions table.

I set a breakpoint on the tenant service gettenant method and added PermissionChecker.IsGranted to the watch.

The field does not come up in the watch.

Am i missing an extension method?
