### ISSUE TITLE
redirectUrl doesn't work when there is # in /Application#/tenant/something

### ISSUE THREAD

**Issue by xumx** [aspnetboilerplate/module-zero#128]
everything after the # character didn't make it into the ViewBag. also need to escape # to %32

this affects Login and Register page

**Comment by hikalkan** [comment]
Thanks for reporting.

**Comment by hikalkan** [comment]
This is same problem with: http://forum.aspnetboilerplate.com/viewtopic.php?f=5&t=728
I will resolve it soon.

**Comment by hikalkan** [comment]
Fixed it: https://github.com/aspnetboilerplate/module-zero-template/commit/10b55b642b7d7bd510e354a2bad418879261a771
