### ISSUE TITLE
Add support for OAuth 2.0

### ISSUE THREAD

**Issue by CloneXpert** [aspnetboilerplate/module-zero#13]
Be able to login using credentials from external authentication providers such as [Facebook and Google](http://www.asp.net/mvc/overview/security/create-an-aspnet-mvc-5-app-with-facebook-and-google-oauth2-and-openid-sign-on).

I believe it would be wonderful if we could re-use this part from the new MVC template. Let me know what do you think, thanks.

**Comment by kegumx** [comment]
+1, thanks

**Comment by codemonkey21** [comment]
After getting all my user bells and whistles in place I was able to run my app. I got the appropriate Facebook claims to display on the ExternalLoginConfirmation view and in AccountController the _userManager.CreateAsync(user); throws a validation error that the password field was null. If you look at the IdentitySample from Microsoft, the IdentityUser which is the equivalent of ApbUser does not have a password field. Passwords are handled by the IPasswordStore http://msdn.microsoft.com/en-us/library/dn613273(v=vs.108).aspx

As a work around, I could ask the user to add a password on the ExternalLoginConfirmation view, but this kinda defeats the purpose of the external login.

If anyone wants to play around with the Asp.Net Identity Samples, create a new MVC project with user accounts. Then use NuGet to install this package (https://www.nuget.org/packages/Microsoft.AspNet.Identity.Samples). It will rebuild the template with a working example using all the latest from AspNet.Identity.

**Comment by emaish** [comment]
@langman66 did you integrate it with ModuleZero, as i still want other features implemented in ModuleZero.

Thank you

**Comment by langman66** [comment]
Sorry I didn't have a chance to work on this integration yet.    Maybe @codemonkey21 can help?

**Comment by codemonkey21** [comment]
I did get Facebook to work, but I had to change quite a few things from the ModuleZero Sample. I know I had to move the role, user, permission stores and managers to the ModuleZeroSampleProject.EntityFramework project. I also commented out the owin context per request and the way the Identity sample created a new user manager per request. When I'm home I can post a couple samples of the changes I made.

**Comment by Jerome2606** [comment]
@langman66 Any codes to share with your plan to integrate the tutorial into ModuleZero ?

@codemonkey21 Did you already post any samples with your facebook integration ?

**Comment by codemonkey21** [comment]
It works by default in Module-Zero now. Instead of the startup.cs in the app_start folder, using the newest template, the app key and secret are in the web.config.

@hikalkan still has to add documentation on it, but it's there if you follow some of the sample apps.

**Comment by hikalkan** [comment]
Sorry, I'm busy a few days more. Then I will document it.

**Comment by brunobertechini** [comment]
+1 for the documentation for OAUTh2 using aspnetboilerplate...

Is that available ?

Bruno

**Comment by hikalkan** [comment]
Since it's documented, I'm closing this issue.
http://www.aspnetboilerplate.com/Pages/Documents/Zero/Startup-Template#social-logins

**Comment by Jerome2606** [comment]
WOW !! Great news

Thanks
