### ISSUE TITLE
AbpAuthorize redirect

### ISSUE THREAD

**Issue by smooney1234** [aspnetboilerplate/module-zero#133]
I have the abpauthorize tag attached to a service. If i try to access it then  it blocks as expected. However it does not redirect. How can i do this in module zero?

Thanks

**Comment by hikalkan** [comment]
This code makes the redirection: https://github.com/aspnetboilerplate/module-zero-template/blob/master/src/AbpCompanyName.AbpProjectName.WebSpaAngular/App_Start/Startup.cs#L26

Do you have it? If you have, do you make ajax request? if so, can you check and share network response?

**Comment by smooney1234** [comment]
Yes, 

Yes I have that, but I am trying to block certain users from certain areas. The abpauthorize tag blocks OK, i'm just wondering how to redirect them if they are blocked.

**Comment by hikalkan** [comment]
Hi,

It automatically redirects unauthorized requests to the Login page. Do you want to redirect somewhere else? Also, you want to redirect all to a single URL, or conditionally?
