### ISSUE TITLE
abp-zero recaptcha bug

### ISSUE THREAD

**Issue by AlexGeller** [aspnetboilerplate/module-zero#138]
Hi,

I find out that abp-zero project's register page use Recaptcha.Web.dll to generate recaptcha, but this dll use google's api to generate recaptcha, as we can visit google's web site in china, so this function is unuseful to us, please consider to change another way to generate recaptcha. thank you.

alex.

**Comment by hikalkan** [comment]
Hi,

I don't want to change it since Recaptcha is the most widely used method. But you can change it for your application and it does not get too much time of you.

Thanks.
