### ISSUE TITLE
Abp.Zero.Ldap has not been mentioned under the Module Zero Nuget Packages

### ISSUE THREAD

**Issue by Sampath-Lokuge** [aspnetboilerplate/module-zero#141]
Abp.Zero.Ldap has not been mentioned under the Module Zero Nuget Packages.I think it should be mentioned under it here : [Module Zero Nuget Packages](http://www.aspnetboilerplate.com/Pages/Documents/Zero/Nuget-Packages)

**Comment by hikalkan** [comment]
Fixed it. Thanks ;)
