### ISSUE TITLE
Registering a tenant-specific routes for each tenacy

### ISSUE THREAD

**Issue by 4nonym0us** [aspnetboilerplate/module-zero#142]
Hello,

I've been reading the docs  and I'd like to know how can i allocate sub-domains to each tenants? Is this option is available in ABP out of the box? if not, what's your advises on implementing sub-domain routing?
[docs](http://aspnetboilerplate.com/Pages/Documents/Zero/Tenant-Management): _(***TenancyName***: This is unique name of a tenant in the application. It should not be changed normally. It can be used to allocate subdomains to tenants like '***mytenant***.mydomain.com'. Tenant.TenancyNameRegex constant defines the naming rule.)_

**Comment by hikalkan** [comment]
Hi,

This is out of scope of ABP.
There may be different options for it.
One way is to redirect all *.yourdomain.com subdomains to a static IP of your server. It's configured in your DNS server.
Then, in IIS, you can bind this IP to your web application.
Thus, all requests redirected to your application. Then you can check URL in your ASP.NET application and get tenant name from URL.

**Comment by 4nonym0us** [comment]
Thanks for the fast response!

So if I make the IIS listen to all of the connections on port (80, for example), I can easily access the the sub-domain value using custom route handler (and I can use this variable in a future to determine tenant), am I right? Will it work in the same way while using wildcard-specific DNS-server configuration?

I'd also like a ask if you have an experience with the Azure web-services? What options should work fine on it?

**Comment by hikalkan** [comment]
Hi,

"So if I make the IIS listen to all of the connections on port (80, for example), I can easily access the the sub-domain value using custom route handler (and I can use this variable in a future to determine tenant), am I right?"

It should be like that. I'm not much experienced on this topic. I've spent many hours to make properly work my project. Then I did DNS wildcard trick and IIS static IP binding for demos on http://aspnetzero.com (try to create a demo to see in action).

I also have no experience on azure web services, sorry.

**Comment by 4nonym0us** [comment]
Hi,

Ok, at least I have a starting point now :) Thanks a lot for the help!
Yeah, aspnetzero.com seems to work great with sub-domains. Could you tell me (unless It's a secret) how do you host the http://aspnetzero.com/ (do you use any cloud-based hosting provider, shared hosting or VPS/VDS)?

**Comment by hikalkan** [comment]
Hi,

I have a dedicated virtual server :)

**Comment by 4nonym0us** [comment]
Hi,

Thanks a lot for the answers, they were really useful! :)
