### ISSUE TITLE
Can I use this in any ASP Identity project

### ISSUE THREAD

**Issue by smartmeter** [aspnetboilerplate/module-zero#146]
Hello, I would like to know if this a true module, i.e can I use it in my existing ASP MVC Identity 2.2 project? 

 *    Which id is the main key ID for users, email , user name or GUID? can you show me how to change it to email or user ID
 *    In the sample web.config file, can you add other options for the connection string, since the EDMX file is missing in the reference of the connection string VS 2015 is showing the connection in connection explorer but failing on `update-database` I even tried  `-verbose`
*     Do I need to enable migrations option in packet manager for this to work?
*     Can you show me how to enable audit tracking entity or tables (for e.g who change passwords etc)
*     How to add google Captcha to your login http://bit.ly/1PMi4Xu here is the plug in for it on github
*     Security, can you add NWebSec https://www.nuget.org/packages/NWebsec.Mvc/ this is very extensive used for security - implemented as asp http://bit.ly/1O7hhQy here on git hub as well
*     Can you please update to .NET 4.6.1 from last month release

**Comment by wocar** [comment]
There is no EDMX because it is codefirst. If you need more properties I
guess you can add ir.
Furthermore to update-databasr you should set the startup project to the
.Web Project and in the package management conse you should set the
.EntityFramework project

**Comment by smartmeter** [comment]
ok
