### ISSUE TITLE
Added the module but multi tenancy is not visible

### ISSUE THREAD

**Issue by patagoniahiker** [aspnetboilerplate/module-zero#148]
Hello, I added this to the module to ABP, very nice work BTW :+1: 

However, the views like the demo for org and role management / by tenant are not visible. How can I see those drag and drop pages for the tenant.

**Comment by hikalkan** [comment]
Hi,

Where did you see the demo? Is it that: http://www.aspnetzero.com/
If so, it's a paid product, not open source.

**Comment by patagoniahiker** [comment]
Thanks, are those not available here
This is seemingly unclear, can you point out which features exactly, and what does it come with

**Comment by hikalkan** [comment]
module-zero provides the domain layer. aspnet zero is application layer and user interface, in brief.
So, role, tenant... management... (see module zero section on http://www.aspnetboilerplate.com/Pages/Documents for all features) are open source and free. But there is no user interface.
aspnet zero is a paid product which is built on abp and module zero.

**Comment by patagoniahiker** [comment]
Ahh! But In the demo I do not see any tenants, is that the same are the root unit?
Do you have a road map for whats coming next and what will be included?
Will you support MongoDb or Any graphDbs next?

**Comment by hikalkan** [comment]
Demo is 'tenant view'. There is also a host view to manage tenants. You can see screenshots in the document: http://www.aspnetzero.com/Documents/Development-Guide#tenant-management
See road map: http://www.aspnetzero.com/Documents/Road-Map

Only EntityFramework support.

**Comment by patagoniahiker** [comment]
How can I need new functionality in the premium version, would they be features based on a template.

**Comment by hikalkan** [comment]
If you need to ask questions on AspNet Zero, can you write to the forum: http://forum.aspnetboilerplate.com/viewforum.php?f=6
Thus, wo don't distrub other people following this repository.

Thanks.
