### ISSUE TITLE
the best practice that how to get the password reset code and send e-mail

### ISSUE THREAD

**Issue by chiaki-yu** [aspnetboilerplate/module-zero#150]
Hello，I'm sorry to bother you.
I have a question bothers me a lot of days.
I want to get the password reset code and send e-mail,
I know how to  do with asp.net Identity,because I read http://go.microsoft.com/fwlink/?LinkID=320771.
But I want to know the best practice in the zero(abp).
Can you help me? thank you very much!

**Comment by chiaki-yu** [comment]
I use Abp.Net.Mail now,thx.

**Comment by GouseBaig** [comment]
Hi,

Can you please send me code samples.
