### ISSUE TITLE
Add FullName for User

### ISSUE THREAD

**Issue by andmattia** [aspnetboilerplate/module-zero#157]
I think is a good option to have a FullName (Surname + Name) like
       `public static string FullName(this User user)
        {
            return $"{user.Surname} {user.Name}";
        }`

**Comment by hikalkan** [comment]
Such an extension method is a good idea. It's appriciated if you contribute it. Thanks a lot.

**Comment by CooperLiu** [comment]
Hi hikalkan, it's not a good idea early use C# 6.0 feature,  some cost of upgrade issue. But I am still happy to see Abp grow up fast .

**Comment by hikalkan** [comment]
It's already implemented: https://github.com/aspnetboilerplate/module-zero/blob/master/src/Abp.Zero/Authorization/Users/AbpUser.cs#L98

But I also don't want to use C# 6 features since some developers may still use VS 2013. So, I'll change it. Thanks.

**Comment by andmattia** [comment]
Ok.

I keep in mind for next dev.

+1

**Comment by kayagultekin** [comment]
Not to open a closed issue but may I suggest an addition and change including **FullNameReverse** and **FullName** because both are used widely:

```
/// <summary>
/// Return reverse full name  (Surname Name)
/// </summary>
[NotMapped]
public virtual string FullNameReverse { get { return this.Surname + " " + this.Name; } }
```
and
```
/// <summary>
/// Return full name (Name Surname)  
/// </summary>
[NotMapped]
public virtual string FullName { get { return this.Name + " " + this.Surname; } }
```

**Comment by hikalkan** [comment]
Thanks @kayagultekin
We generally use Name + Surname, instead of Surname + Name. I also think like that.

**Comment by kayagultekin** [comment]
You're most welcome!
