### ISSUE TITLE
How Login by Impersonator User ?

### ISSUE THREAD

**Issue by mona6767** [aspnetboilerplate/module-zero#162]
Hi ,
best regard .

How i can login Admin by user (Impersonator) ?

not find "Account/Impersonate" controller !

thank you .

**Comment by hikalkan** [comment]
I have created a gist for it before: https://gist.github.com/hikalkan/8862d9f7ae8b4874976d
You can also search it on the forum: http://forum.aspnetboilerplate.com/search.php?keywords=impersonation

**Comment by kibria06cse** [comment]
How can I prevent admin/or other users to impersonate a user, if that user is currently logged in? Or what can I do, if any user is impersonating another user and then that user is logged in the system, then all impersonated users will be logged out. How can I do it via asp.net boilerplate with MVC?

**Comment by hikalkan** [comment]
It's an interesting request. However it should be possible. This is not much related to AspNet Boilerplate actually.

For example, you can use a cache/database value that indicates the last activity time of the user and check it if it's in last 5 minutes then you don't allow to login by impersonation. Anyway, that's an independent design issue.
