### ISSUE TITLE
Change or Remove "Abp" prefix from tables.

### ISSUE THREAD

**Issue by hikalkan** [aspnetboilerplate/module-zero#165]
Include this code (https://gist.github.com/hikalkan/4f8f793c7929a81d300f) to Abp.Zero project.

**Comment by hikalkan** [comment]
How to use:

Example 1: Remove table prefix:

````C#
protected override void OnModelCreating(DbModelBuilder modelBuilder)
{
    base.OnModelCreating(modelBuilder);

    modelBuilder.ChangeAbpTablePrefix<Tenant, Role, User>("");
}
````

Example 2: Change to another prefix:

````C#
protected override void OnModelCreating(DbModelBuilder modelBuilder)
{
    base.OnModelCreating(modelBuilder);

    modelBuilder.ChangeAbpTablePrefix<Tenant, Role, User>("MyPrefix");
}
````

**Comment by chiaki-yu** [comment]
I have a mistake such use:"Cannot resolve symbol 'ChangeAbpTablePrefix'"
and I also write "using Abp.Zero.EntityFramework;"
can you help me? thanks!

**Comment by hikalkan** [comment]
It's not released yet. You can copy code from here for now: https://gist.github.com/hikalkan/4f8f793c7929a81d300f

**Comment by Worthy7** [comment]
There is a bug. If you use this function, then any  [Table("参加")] definitions get ignored.

**Comment by hikalkan** [comment]
Yes. It's not possible to use them together. However, you can call ChangeAbpTablePrefix, then set table name after that to override naming (and don't use Table attribute).

**Comment by Worthy7** [comment]
I think the table attribute should take priority, don't you?

**Comment by hikalkan** [comment]
Entity Framework overrides attributes by fluent configuration. This is EF's design and we follow it. Why not just using fluent configuration?

**Comment by Worthy7** [comment]
Fair enough.

**Comment by redbinkieresearchlabs** [comment]
I have added the code to my DBContext class and i get the error OnModelCreating no suitable method found to overwrite. I have taken your code earlier and updated it my Abp.Zero and recompiled the dll and referenced them again in my test project. What am I doing wrong?

**Comment by hikalkan** [comment]
OnModelCreating is DbContext's method (and it's EF's own class), not ABP's.
