### ISSUE TITLE
Specific tenant inherits language texts defined by host in database

### ISSUE THREAD

**Issue by mengvisal** [aspnetboilerplate/module-zero#166]
Hi! I added language texts for a host (tenantId = null), and I do not have language texts for the default tenant. As i logged in as the default tenant, can the localstring translate the text using language texts added in the database for a host or do i need to add language texts for each specific tenant? 

FYI: When I added texts as host tenant and logged in as default tenant, my pages did not translate. However, when I added texts as the default tenant, my pages are translated correctly.

**Comment by hikalkan** [comment]
When you override a text for host, it should be available for all tenants. No need to add it to every tenant seperately. I will test and return you.

Thanks.

**Comment by ismcagdas** [comment]
We have tested it and unable to reproduce your situation.
Do you still have the problem ?

If you still have the problem, can you explain steps to reproduce it ?

You can reopen this issue if you still have the problem.
