### ISSUE TITLE
how to change MaxParametersLength

### ISSUE THREAD

**Issue by ChiakiYu** [aspnetboilerplate/module-zero#167]
in module-zero ,there is the rows:

```
public const int MaxParametersLength = 1024;
```

and  

```
Parameters = auditInfo.Parameters.TruncateWithPostfix(MaxParametersLength),
```

I want to change or overwrite the number "1024" 
Because my project use the datatables,and the parameter is very much,the rows Truncate my parameter .
thanks

**Comment by hikalkan** [comment]
There is no way of changing it currently.

**Comment by chiaki-yu** [comment]
Oh,My god, that I have to think of other way to handle this truncated parameter.
Still thank you very much,abp is very good
