### ISSUE TITLE
how to add my custom properties to OrganizationUnit

### ISSUE THREAD

**Issue by wendell620** [aspnetboilerplate/module-zero#168]
just like abpuser and abpusermanager

**Comment by tonyqus** [comment]
We have the same issue as @wendell620. OrganizationUnit entity looks not to be extensible.

**Comment by hikalkan** [comment]
You can check this tutorial as an example of extending entities: http://aspnetzero.com/Documents/Extending-Existing-Entities#extending-non-abstract-entities
While it extends Edition, OrganizationUnit is also similar.

**Comment by tonyqus** [comment]
It works! thank you!

**Comment by hikalkan** [comment]
You're welcome.
