### ISSUE TITLE
Oracle object name length restriction

### ISSUE THREAD

**Issue by Otgontugs** [aspnetboilerplate/module-zero#169]
When i use Oracle.ManagedDataAccess via EntityFramework these objects throw error.

NotificationInfo.EntityTypeAssemblyQualifiedName
NotificationSubscriptionInfo.EntityTypeAssemblyQualifiedName
User.ShouldChangePasswordOnNextLogin

These names should not exceed length of 30 chars due to Oracle restrictions.

**Comment by hikalkan** [comment]
I did not know it. This is a bad restriction. I suggest you to map properties to a shorter name by overriding onmodelcreating in your dbcontext

**Comment by Otgontugs** [comment]
Yes, i overrided it. But this may be informational for further development at least. 
There was Hangfire also hardly bound to MSSQL. I thought that the framework should not depend on a single technology.

**Comment by hikalkan** [comment]
ABP does not depend on HangFire. Just startup template includes it. You can easily remove it from your solution.
