### ISSUE TITLE
Possibility to change string lengths in User class. Email length.

### ISSUE THREAD

**Issue by easyest** [aspnetboilerplate/module-zero#17]
It would be nice to be able to override string lengths for `Name` and `Surname` fields.

Email field length should be 254 chars as per RFC 5321 and RFC 5322

**Comment by codemonkey21** [comment]
If you're using Entity Framework Migrations, you can just modify the script before you run it. That's what I did to override the default values. I also made username and email 254 chars since I'm using the email as the login.

**Comment by hikalkan** [comment]
I changed them. (I did not try but as I know) you can override data annotation attribute values by overriding OnModelCreating of your dbcontext.
