### ISSUE TITLE
Account problem

### ISSUE THREAD

**Issue by chiaki-yu** [aspnetboilerplate/module-zero#178]
There is a user whose username is "demo" and email is "demo@demo.com" in the current system.

now,someone register with username "demo@demo.com" and any email which is not exist.

It can register successfully

but it can't log in, 

Because there is one user whose email is "demo@demo.com", it hint "AbpLoginResultType.InvalidUserNameOrEmailAddress".

**Comment by chiaki-yu** [comment]
I now the solution is to limit the username that don't let use email as the username

**Comment by hikalkan** [comment]
Thank you very much for the information. Your solution is fine. We will also apply it.

**Comment by ismcagdas** [comment]
moved to module zero template https://github.com/aspnetboilerplate/module-zero-template/issues/30
