### ISSUE TITLE
Permission, Role and User

### ISSUE THREAD

**Issue by easyest** [aspnetboilerplate/module-zero#18]
`User` has `UserPermissionSetting`, that extends `PermissionSetting`. `Role` has `RolePermissionSetting` that also extends `PermissionSetting`. So, generated database table `AbpPermissions` has both `UserId` and `RoleId`. Am I right to assume, that there is no separate table with unique permission entries and the table `AbpPermissions` can have multiple permissions with the same `Name` if this permission is added to several roles? Where should we keep global list of permissions, that we could show in the web form for adding to the role?
Could You give some brief information, how `Permissions` work, how `Roles` and `Users` should be managed (created, edited, permissions assigned to roles and/or individual users etc)?

**Comment by guilmori** [comment]
I have the exact same question.

**Comment by brendan-rice** [comment]
+1 for a bit of an explanation around permissions. I wanted to limit the main navigation by role but couldn't figure out how to do it and had to hack a solution together.

Thanks for sharing the framework by the way, it has saved me a ton of time.

**Comment by easyest** [comment]
It is answered in another issues somewhere - authorization is done by permission, not by role. There are few possible workarounds - use a permission in each role to determine user's role. In this case You have to limit the possibility to remove such permission.
The other way would be to check the role manually.

**Comment by hikalkan** [comment]
Hi,

List of all permissions are not stored in the database. It's stored 'in the code'. If you want to get a list of all permissions in the system, just inject IPermissionManager and use GetAllPermissions() method.

**Comment by hikalkan** [comment]
BTW,

I don't advice to check the role in the code. Because roles are dynamic, can be added and deleted by users. So, how can we know name of the role while we're coding..? Instead, check permissions. Role will be granted for permissions.

But, for some projects, we may need roles those are used in the code. I define these roles as 'static roles' (See Role.IsStatic property). Static roles can not be deleted by users and must be exists in the DB migration script. So, you can check it with UserManager.IsInRole("..."). Also, you can use they in AbpAuthorize attributes.

I haven't documented these yet since they are in-development. But I wanted to give brief info here :)

**Comment by brendan-rice** [comment]
Thanks for a more detailed answer, it should help me  a lot.

Can you let me know how you would go about securing pages in the system based on whether the user is an admin or not and geenrating the navigation accordingly please?

**Comment by easyest** [comment]
Why do You need to generate navigation if a user "is admin"? Wouldn't it be better if any user would see only items that he has permission to access? There is a parameter for that in navigation provider.
```c#
public MenuItemDefinition(string name, ILocalizableString displayName, string icon = null, string url = null, bool requiresAuthentication = false, string requiredPermissionName = null, int order = 0);
```
If Your pages are a general CRUD, then You would add a `Read` permission, so a user would see the link only if he can view this information.

I am closing this, as @hikalkan has answered my initial question.
