### ISSUE TITLE
DataBase Migration issue when i want to try add new table in existing datbase

### ISSUE THREAD

**Issue by mayureshpisal** [aspnetboilerplate/module-zero#182]
Hi hikalkan,

I was started work on ASP.NET Boilerplate A Multi-Tenant (SaaS) Application with ASP.NET MVC, but I am facing some issue,

In my application I provide one azure search functionality to user for that reason I need to create table in database. So as per document I have created migration class and write create table script into this class. After that I ran update-database command on package manager console then table created successfully into provided database. I have created application service to save the data into newly created table and insert the record successfully
But my question is 

In Migration Script I have provided “dbo.SaveSearch” name to that table but in database two tables created 1) SaveSearch 2) SaveSearches and when I want try to insert the record into savesearch, DBcontext then DBContext get the table name as “SaveSearches” I also checked my solution, I am not provided the “SaveSearches” name to any class or  entity. Then why two tables are created and why DBContext get the Savesearches  as table. Could you please provide me the document of Database migration I search in your forum but I not found any document.

My licen issued by OrangeBoy

**Comment by hikalkan** [comment]
Hi,

Understood your problem. But this is not related to ABP, therefore it's not documented. It's a standard EntityFramework (EF) configuration. You should add [Table("SaveSearch")] attribute to the entity.

Also, beside that, do not change table/column names in the automatically created migration code. Do your changes on the model via attributes or EF fluent configuration. Then add migration again.

Have a nice day.

**Comment by mayureshpisal** [comment]
Hi,

Thanks for your prompt reply. I understand the problem its not related to ABP its related to Entity Framework.
If you have only one entity which is mapped to a table that is not pluralized then you can remove the **# **PluralizingTableNameConvention** **and manually configure the table name of the entity. To remove the PlurazingTablename i just added below method in DBContext class

protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<**PluralizingTableNameConvention**>();
            base.OnModelCreating(modelBuilder);
        }

After that my Problem is resolved. Thanks
