### ISSUE TITLE
Dependency cycle Exception

### ISSUE THREAD

**Issue by iyhammad** [aspnetboilerplate/module-zero#185]
I got the below exception after updating my solution to AbpZero 0.8.4

`
"innerException":{"message":"An error has occurred.","exceptionMessage":"Dependency cycle has been detected when trying to resolve component 'HRPayroll.MultiTenancy.TenantManager'.\r\nThe resolution tree that resulted in the cycle is the following:\r\nComponent 'HRPayroll.MultiTenancy.TenantManager' resolved as dependency of\r\n\tcomponent 'AbpZeroFeatureValueStore' resolved as dependency of\r\n\tcomponent 'HRPayroll.Editions.EditionManager' resolved as dependency of\r\n\tcomponent 'HRPayroll.MultiTenancy.TenantManager' resolved as dependency of\r\n\tcomponent 'HRPayroll.Users.UserAppService' resolved as dependency of\r\n\tcomponent 'Abp.WebApi.Controllers.Dynamic.Interceptors.AbpDynamicApiControllerInterceptor`1[[HRPayroll.Users.IUserAppService, HRPayroll.Application, Version=0.0.0.5, Culture=neutral, PublicKeyToken=null]]' resolved as dependency of\r\n\tcomponent 'Abp.WebApi.Controllers.Dynamic.DynamicApiController`1[[HRPayroll.Users.IUserAppService, HRPayroll.Application, Version=0.0.0.5, Culture=neutral, PublicKeyToken=null]]' which is the root component being resolved.\r\n","exceptionType":"Castle.MicroKernel.CircularDependencyException","stackTrace":"   at Castle.MicroKernel.Handlers.DefaultHandler.ResolveCore(CreationContext context, Boolean requiresDecommission, Boolean instanceRequired, Burden& burden)\r\n 
`

**Comment by hikalkan** [comment]
Thanks for informing, we will check it.

**Comment by codemonkey21** [comment]
Yea, I've got a similar issue after I upgraded to 8.4. It took awhile to figure out what base classes had changed to 8.4 without documentation. Once I got it to run, everything worked until I hit a page I had to be logged in for.

>  [HandlerException: Can't create component 'Nyxly.MultiTenancy.TenantManager' as it has dependencies to be satisfied.
> 
> 'Nyxly.MultiTenancy.TenantManager' is waiting for the following dependencies:
> - Service 'Abp.Application.Editions.AbpEditionManager' which was not registered.
> ]
>    Castle.MicroKernel.Handlers.DefaultHandler.AssertNotWaitingForDependency() +52
>    Castle.MicroKernel.Handlers.DefaultHandler.ResolveCore(CreationContext context, Boolean requiresDecommission, Boolean instanceRequired, Burden& burden) +165
>    Castle.MicroKernel.Handlers.DefaultHandler.Resolve(CreationContext context, Boolean instanceRequired) +40
>    Castle.MicroKernel.Handlers.AbstractHandler.Resolve(CreationContext context) +26
>    Castle.MicroKernel.Resolvers.DefaultDependencyResolver.ResolveFromKernelByType(CreationContext context, ComponentModel model, DependencyModel dependency) +242
>    Castle.MicroKernel.Resolvers.DefaultDependencyResolver.ResolveFromKernel(CreationContext context, ComponentModel model, DependencyModel dependency) +153
>    Castle.MicroKernel.Resolvers.DefaultDependencyResolver.ResolveCore(CreationContext context, ISubDependencyResolver contextHandlerResolver, ComponentModel model, DependencyModel dependency) +316
>    Castle.MicroKernel.Resolvers.DefaultDependencyResolver.Resolve(CreationContext context, ISubDependencyResolver contextHandlerResolver, ComponentModel model, DependencyModel dependency) +43
>    Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.CreateConstructorArguments(ConstructorCandidate constructor, CreationContext context) +258
>    Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.Instantiate(CreationContext context) +54
>    Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.InternalCreate(CreationContext context) +40
>    Castle.MicroKernel.ComponentActivator.AbstractComponentActivator.Create(CreationContext context, Burden burden) +36
>    Castle.MicroKernel.Lifestyle.AbstractLifestyleManager.CreateInstance(CreationContext context, Boolean trackedExternally) +65
>    Castle.MicroKernel.Lifestyle.AbstractLifestyleManager.Resolve(CreationContext context, IReleasePolicy releasePolicy) +37
>    Castle.MicroKernel.Handlers.DefaultHandler.ResolveCore(CreationContext context, Boolean requiresDecommission, Boolean instanceRequired, Burden& burden) +205
>    Castle.MicroKernel.Handlers.DefaultHandler.Resolve(CreationContext context, Boolean instanceRequired) +40
>    Castle.MicroKernel.Handlers.AbstractHandler.Resolve(CreationContext context) +26
>    Castle.MicroKernel.DefaultKernel.ResolveComponent(IHandler handler, Type service, IDictionary additionalArguments, IReleasePolicy policy) +86
>    Castle.MicroKernel.DefaultKernel.Castle.MicroKernel.IKernelInternal.Resolve(Type service, IDictionary arguments, IReleasePolicy policy) +61
>    Castle.MicroKernel.DefaultKernel.Resolve(Type service, IDictionary arguments) +41
>    Castle.Windsor.WindsorContainer.Resolve(Type service) +27
>    Abp.Dependency.IocManager.Resolve(Type type) +62
>    Abp.Web.Mvc.Controllers.WindsorControllerFactory.GetControllerInstance(RequestContext requestContext, Type controllerType) +82
>    System.Web.Mvc.DefaultControllerFactory.CreateController(RequestContext requestContext, String controllerName) +93
>    System.Web.Mvc.MvcHandler.ProcessRequestInit(HttpContextBase httpContext, IController& controller, IControllerFactory& factory) +196
>    System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state) +72
>    System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContext httpContext, AsyncCallback callback, Object state) +67
>    System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object extraData) +30
>    System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +103
>    System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155
