### ISSUE TITLE
Upgrade the latest version="0.8.4.0" then EditionManager,FeatureValueStore,TenantManager constructor giving error

### ISSUE THREAD

**Issue by mayureshpisal** [aspnetboilerplate/module-zero#191]
1) Edition Manager constructor error 

![image](https://cloud.githubusercontent.com/assets/17999434/15065155/2fdb7ba4-137a-11e6-8bd2-5979099648e6.png)

2) FeatureValueStore CONSTRUCTOR error

![image](https://cloud.githubusercontent.com/assets/17999434/15065172/534c866e-137a-11e6-9451-e34828f430fc.png)

3) TenantManager constructor

![image](https://cloud.githubusercontent.com/assets/17999434/15065187/6fc43f94-137a-11e6-8f6f-697fe3170e56.png)

any suggestion why this happening , I upgrade this version because when I set up a new database and create all entity in a new database then login is not working.

var loginResult = await GetLoginResultAsync(loginModel.UsernameOrEmailAddress, loginModel.Password, loginModel.TenancyName);

this call is not working properly even no exception occurred in this method  call.

please help me.

**Comment by hikalkan** [comment]
Constructors may change on upgrades since base class injections can be changed. See release notes before/after upgrading it: https://github.com/aspnetboilerplate/module-zero/releases

**Comment by wocar** [comment]
What if you change constructor injection to property injection?

Regards :)

**Comment by hikalkan** [comment]
Well... I could not make them all property injection because of abstract classes. Then I decided to follow best practices as much as possible, and used constructor injection for required dependencies. This also allows you to easily replace dependencies with your own implementations.
I think it's not that hard to change ctor after upgrades :)
