### ISSUE TITLE
Implement IUserLockoutStore

### ISSUE THREAD

**Issue by hikalkan** [aspnetboilerplate/module-zero#192]
See http://forum.aspnetboilerplate.com/posting.php?mode=reply&f=5&t=2524

**Comment by joe704la** [comment]
+1

**Comment by Redok09** [comment]
+1

**Comment by chiaki-yu** [comment]
+1

**Comment by joe704la** [comment]
I came up with a solution for this a while back that fit my particular needs. I posted how I did it in the forum. 

http://forum.aspnetboilerplate.com/posting.php?mode=reply&f=5&t=2524
