### ISSUE TITLE
How can add another properties like TenantGuid in AbpSession

### ISSUE THREAD

**Issue by mayureshpisal** [aspnetboilerplate/module-zero#196]
Hi,

I have existing multitenant Application which is Live but existing application TenantId is Type GUID but in AspnetZero type is int.For that reason I have created new property in tenant Class as below 

public class Tenant : AbpTenant<Tenant, User>
    {
        protected Tenant()
        {
            TenantGuid=  Guid.NewGuid(); 
        }

```
    public Guid TenantGuid { get; set; }

    public Tenant(string tenancyName, string name)
        : base(tenancyName, name)
    {
        TenantGuid = Guid.NewGuid();
    }
}
```

And I want to add this GUID into AbpSession how can I add this because TenantGUID is my TenantId.

**Comment by hikalkan** [comment]
See this: https://gist.github.com/hikalkan/67469e05475c2d18cb88
