### ISSUE TITLE
Questions & Enhancements for AbpZeroDbMigrator

### ISSUE THREAD

**Issue by iyhammad** [aspnetboilerplate/module-zero#199]
I'm trying to use the new **AbpZeroDbMigrator** to insert initial data when the user creates a new Tenant. I've 2 Questions:

1. If Insert any data during the Tenant Creation, It goes to the new Tenant Database correctly But with TenantId = 0. Should I Assign the TenantId explicitly. If Yes, What's the Best way to transfer the TenantId from AbpZeroDbMigrator to the DbContextMigrationConfiguration Object (Particulary the Seed Function).

For Me to Resolve this issue, I Override **CreateOrMigrateForTenant** and **CreateOrMigrate** to capture the TenantId and then call the Initial Data Passing this Value. I think It will be better to have it ready in the **AbpZeroDbMigrator** . If you Agree let me know to Create a Pull Request.

2. What If I've a multi Module System that every module have It's own data layer and It's initial data. I think **AbpZeroDbMigrator** currently won't Support. To overcome this I did the following in my **AbpZeroDbMigrator** 

````
  public override void CreateOrMigrateForTenant(AbpTenantBase tenant)
        {
            base.CreateOrMigrateForTenant(tenant);
            var typeFinder = this.iocResolver.Resolve<ITypeFinder>();
            var types =
                typeFinder.Find(
                    z => z.IsClass && !z.IsAbstract && typeof(IAbpZeroDbMigrator).IsAssignableFrom(z) && z.FullName != this.GetType().FullName);
            foreach (var type in types)
            {
                var migratorObject = (IDisposableDependencyObjectWrapper) this.iocResolver.ResolveAsDisposable(type);
                ((IAbpZeroDbMigrator)migratorObject.Object).CreateOrMigrateForTenant(tenant);
            }
        }

````
Here I Searched for all the Classes the implements this Interface and called their **CreateOrMigrateForTenant** Function.

It will be great If it can be implemented in AbpZero with the taking into consideration the Dependency.For Example Module A Depends on Module B then Module B should be initialized before Module A.

**Comment by hikalkan** [comment]
I resolved TenantId issue with that: https://github.com/aspnetboilerplate/module-zero/issues/198
Will think on the second problem after this release.

**Comment by hikalkan** [comment]
Continue on https://github.com/aspnetboilerplate/module-zero/issues/213 for the second problem.
