### ISSUE TITLE
v.0.9.0.0 Source code does not compile

### ISSUE THREAD

**Issue by denisvirissimo** [aspnetboilerplate/module-zero#200]
The source code provided for release v.0.9.0.0 (https://github.com/aspnetboilerplate/module-zero/archive/v0.9.0.0.zip) does not compile. Found errors on Zero and then in Zero.EntityFramework.

**Comment by hikalkan** [comment]
We can compile it. What errors are you getting?

**Comment by denisvirissimo** [comment]
I'm getting a  "'Abp.Zero.Configuration.AbpZeroConfig.EntityTypes.get' must declare a body because it is not marked abstract or extern. Automatically implemented properties must define both get and set accessors." at Abp.Zero\Zero\Configuration\AbpZeroConfig.cs, line 22

`public IAbpZeroEntityTypes EntityTypes { get; }`

If I corret to:

`public IAbpZeroEntityTypes EntityTypes { get; set; }`

then I get an error "Invalid expression term '['" in Abp.Zero.EntityFrameworkError.AbpZeroDbMigrator.cs, line 34.

` var args = new DbPerTenantConnectionStringResolveArgs(null, MultiTenancySides.Host)
            {
                ["DbContextType"] = typeof(TDbContext)
            };`

**Comment by hikalkan** [comment]
I suppose you are using Visual Studio 2013 (C# 5) and we used C# 6 features (with VS 2015). I just tried in VS 2013 and got the same error. I will revert to C# 5.
