### ISSUE TITLE
Own NavigationProvider: Resolve dependencies

### ISSUE THREAD

**Issue by lemestrez** [aspnetboilerplate/module-zero#203]
Hallo,

I create in the past my own menu:

```
   public class MyNavigationProvider : NavigationProvider
    {
        public override void SetNavigation(INavigationProviderContext context)
        {
            var menuService = IocManager.Instance.Resolve<IMenuService>();

            // build menu

            IocManager.Instance.Release(menuService);
        }
    }

```
Since the update I became an error:

> 'Abp.Zero.EntityFramework.DbPerTenantConnectionStringResolver' is waiting for the following dependencies:
> - Service 'Abp.MultiTenancy.ITenantCache' which was not registered.
> 

I look at the code and it looks, that the INavigationProvider.SetNavigation() will be called in Module:Initialize

But AbpZeroCoreModule.RegisterTenantCacheIfNeeded() will be called in Module:PostInitialize

Greeting,

Patrick

**Comment by hikalkan** [comment]
Hi,

To solve your problem:

In your module's initialize code, write the following like:

````C#
IocManager.Register<ITenantCache, TenantCache<Tenant, User>>(DependencyLifeStyle.Transient);
````

I will fix it in next release.

Thanks for informing that.

**Comment by lemestrez** [comment]
Hi Halil,

many thanks. So, i leave the point open.

Best wishes,
Patrick
