### ISSUE TITLE
Setting manager Question / Issue

### ISSUE THREAD

**Issue by amwdrizz** [aspnetboilerplate/module-zero#205]
Not sure if intended, but this code

`
SettingManager.GetSettingValueForTenant(settingName,TenantId);
`

Should not return a value if empty / non existent even if defined on the host.  As it is right now, it returns the application / host value if the tenant is not defined.

**Comment by hikalkan** [comment]
It's intended. It returns default value, overrided by application, overrided by the tenant if exists.

**Comment by amwdrizz** [comment]
Would it be possible to look into having the GetSettingValueForX return either that setting or null?  And have the GetSettingValue get the setting based on default value, app, tenant, user?

**Comment by hikalkan** [comment]
GetSettingValue does it, but what if you need to tenant's CURRENT value? GetSettingValue always overrides by user value.
Most of the time you don't need to tenant's database value since it's not the used value. Are you doing something different?

**Comment by amwdrizz** [comment]
I am storing AD/LDAP connection info that is per tenant / host.  The host will be connecting to a different AD/LDAP directory while each tenant has their own.  Right now I am trying to figure out the best way to store that data so the tenants cannot see the host AD/LDAP connection info.  As is right now, I am running into the issue with unconfigured tenants being able to see / use the host AD/LDAP string.

This is for full AD management not just logins.

**Comment by hikalkan** [comment]
So, you want that tenant setting should not inherit host setting? So, why don't you use ``isInherited = false`` while defining this setting?

**Comment by amwdrizz** [comment]
I glossed over the isInherited flag, thank you for pointing that out since it does what I need it to do.
