### ISSUE TITLE
Mapping a sub domain to a tenant

### ISSUE THREAD

**Issue by brendan-rice** [aspnetboilerplate/module-zero#21]
I have a requirement of mapping a sub-domain to a tenant so:

1. http://myTenant.mySite.com would map to tenant.Id = 1
2. Only users from that tenant could log into that domain

What is the best way of going about this?

Thank in advance.

**Comment by easyest** [comment]
Create a tenant with the name `myTenant`. Then in Your login method get tenant name from URL, get it's Id from tenant repository ant try to login the user with this tenant.
