### ISSUE TITLE
Intermediate value is not a function in main.js

### ISSUE THREAD

**Issue by jfbaudracco** [aspnetboilerplate/module-zero#214]
In chrome debugger, i get an error in main.js. It seems that closure function around the code to configure blockUI is not necessary !
If i comment the closure, all seems run correctly.
```
    //Configure blockUI
    //(function ($) {
        if ($.blockUI) {
            $.blockUI.defaults.baseZ = 2000;
        }
    //})(jQuery);
```
I submit the problem. I don't know if the solution is good !

thanks
Jean-François

**Comment by hikalkan** [comment]
Thank you for reporting this. While it seems closue should not effect the code, we will check it.

**Comment by hikalkan** [comment]
Fixed with https://github.com/aspnetboilerplate/module-zero-template/commit/8596f4825fbbd8b45d5278a281fab248962c3e48
