### ISSUE TITLE
AbpUserStore.IsInRoleAsync exception thrown when role doesn't exists

### ISSUE THREAD

**Issue by Redok09** [aspnetboilerplate/module-zero#215]
If a role doesn't exist and AbpUserStore.IsInRoleAsync is called the exception System.InvalidOperationException is thrown. Using FirstOrDefaultAsync instead of SingleAsync should do the trick. Just need to return false if the role is null. 

The code would look like this:

public virtual async Task<bool> IsInRoleAsync(TUser user, string roleName)
{
         var role = await _roleRepository.FirstOrDefaultAsync(r => r.Name == roleName);
         return role != null && await _userRoleRepository.FirstOrDefaultAsync(ur => ur.UserId == user.Id && ur.RoleId == role.Id) != null;
}

**Comment by hikalkan** [comment]
I'm not sure about that. If a role does not exists and you are calling to IsInRoleAsync with that non-exists role name, it's better to throw exception, thus you can know that you are doing something wrong. But the exception message can be better.

**Comment by Redok09** [comment]
Yes you are probably right. I agree with you for making a better exception.

The reason why I got the exception is because I was doing some unit testing and I deleted a role and wanted to check if the user was still in the role. But it makes sens that it would never happen while using the app normally.

Thanks for response!

**Comment by hikalkan** [comment]
You're welcome and thank you too.
