### ISSUE TITLE
Create User and return Id

### ISSUE THREAD

**Issue by Znow** [aspnetboilerplate/module-zero#219]
Hi

I can't seem to find a method on UserManager that allows me to create a user, and return the Id, or the object straight away.

How can I achieve this?

Thanks in advance
Kind regards

**Comment by hikalkan** [comment]
pseudo code:

```
var user = new User(...);
UserManager.Create(user);
unitofwork.SaveChanges();
var id = user.id;
```

**Comment by Znow** [comment]
@hikalkan Thanks alot! Didn't think of that :/
