### ISSUE TITLE
Cannot create user with email address that has "-" in domain, as username

### ISSUE THREAD

**Issue by Znow** [aspnetboilerplate/module-zero#220]
Hi

I can fine register a new user with "test@test.com" and assign that email as the username, and use that for login.

But if I enter "test@test-test.com" - it gives "Can only contain letters and digits" (something like that).

I should be able to use any "valid" email, as the username.

Kind regards

**Comment by ismcagdas** [comment]
Please see this forum topic http://forum.aspnetboilerplate.com/viewtopic.php?f=5&t=2702&p=6185&hilit=UserManager#p6185

**Comment by Znow** [comment]
@ismcagdas Thanks!
