### ISSUE TITLE
Navigation properties

### ISSUE THREAD

**Issue by babinecm** [aspnetboilerplate/module-zero#221]
We should add navigation properties for all ABP Zero related entities.
Or there is a reason that they are missing?

**Comment by hikalkan** [comment]
Some of them are missing to keep it simple. For example, UserRole has no navigation to User and Role, because they are generic classes and we did not want to make UserRole generic too.

**Comment by babinecm** [comment]
I see. So, what is the best simplest solution to get a **Role.DisplayName** through the **UserRole** class, if there is only **RoleId** property?
EF does not automatically load **Role** entity.
If there were **Role** navigation property, then you can simple create **RoleDisplayName** property in your DTO class and AutoMapper do the rest.
What is your suggestion? Thank you.

**Comment by hikalkan** [comment]
My suggestion is to use a LINQ join :)

**Comment by babinecm** [comment]
Ok, I thought :). Thank you.
