### ISSUE TITLE
Create Abp.Zero.EntityFrameworkCore package

### ISSUE THREAD

**Issue by hikalkan** [aspnetboilerplate/module-zero#223]

**Comment by arthurspa** [comment]
Hi! I want to start a project using Abp.Zero.EntityFraeworkCore even if it does not support soft delete (I'll try to implemente it). 

Any due date of when will this be merged to master?

Thanks.

**Comment by hikalkan** [comment]
Hi,

Soft delete is not the only data filter. There are multi tenant filters which are needed for single db multithreading.

I did not test it yet, I will try to have a time to test and merge it in a week.

**Comment by arthurspa** [comment]
Thanks!
