### ISSUE TITLE
MultiTenancy with Different Database 

### ISSUE THREAD

**Issue by karen-hikesupport** [aspnetboilerplate/module-zero#225]
Hi,

we are using MultiTenancy architecture with our product, we have Master db that have Tenants, users, roles, login and Extra account Detail in which we store the all tenants detail.

other Database per Tenant that create automatically, so can we do with the same in this architecture and if yes so how?

**Comment by hikalkan** [comment]
Have you tried module zero startup template? It already does that: http://www.aspnetboilerplate.com/Templates

**Comment by karen-hikesupport** [comment]
yeh i have tried this template but they always creating same db with when create tenant, My question is about can we create two Context like HostContext or TenantContext and can u tell me in brief

**Comment by hikalkan** [comment]
see this: http://forum.aspnetboilerplate.com/viewtopic.php?f=5&t=2756

**Comment by karen-hikesupport** [comment]
Hi Hikalkan,

i am facing the issue with AbpZeroMigrator
Error : " 'HikePOS.MigrationsTenant.Configuration' cannot be used as type parameter 'TConfiguration' in the generic type or method 'Abp.Zero.EntityFramework.AbpZeroDbMigrator<TDbContext,TConfiguration>'. There is no implicit reference conversion from 'HikePOS.MigrationsTenant.Configuration' to 'Abp.Zero.EntityFramework.IMultiTenantSeed'."

can u tell me how can we resolved? 
Code is like below : 
public class AbpZeroDbMigrator : AbpZeroDbMigrator<TenantDbContext, Configuration> 
    {
        public AbpZeroDbMigrator(
            IUnitOfWorkManager unitOfWorkManager,
            IDbPerTenantConnectionStringResolver connectionStringResolver,
            IIocResolver iocResolver)
            : base(
                unitOfWorkManager,
                connectionStringResolver,
                iocResolver)
        {
        }
    }

?

**Comment by karen-hikesupport** [comment]
Hi, 

can u give help?

**Comment by hikalkan** [comment]
The error says it explicitly. Just implement IMultiTenantSeed for your Configuration class.
