### ISSUE TITLE
How can migrate our Tenant Databases?

### ISSUE THREAD

**Issue by karen-hikesupport** [aspnetboilerplate/module-zero#229]
Hi,
I have Multiple Tenant Databases based on tenants, now we have to run the migration tool for change that for migrate with others tenant so can u tell me what we need to do change in migration tool projects? or any document have?

**Comment by karen-hikesupport** [comment]
Hi,

can you do the reply ?

**Comment by karen-hikesupport** [comment]
can u give me answer?

**Comment by ismcagdas** [comment]
Do you have single DbContext of seperate DbContext for host and tenant databases ?

**Comment by karen-hikesupport** [comment]
i have Seperate dbcontext for Host and Tenants also

**Comment by ismcagdas** [comment]
Then you will need two DbMigrators. Please see this forum topic http://forum.aspnetboilerplate.com/viewtopic.php?f=5&t=2756&p=6402&hilit=DbMigrator#p6402
