### ISSUE TITLE
Access ResetPasswordTokenPurpose

### ISSUE THREAD

**Issue by vdurante** [aspnetboilerplate/module-zero#230]
The following class has a protected attribute called ResetPasswordTokenPurpose:

https://github.com/aspnet/Identity/blob/4ef80fabf66624b464e77ac9dd6e8c4461759e0c/src/Microsoft.AspNetCore.Identity/UserManager.cs

AbpUserManager inherits from UserManager, but still I can't access it from my AppUserManager that inherits form AbpUserManager.

I would like to understand why, since it is interesting to access the token purpose to generate password reset tokens.

**Comment by hikalkan** [comment]
The code you shared is new Identity version used with AspNet Core (https://www.nuget.org/packages/Microsoft.AspNetCore.Identity/).
Module zero uses previous version (https://www.nuget.org/packages/Microsoft.AspNet.Identity.Core)
