### ISSUE TITLE
Disable MultiTenancy

### ISSUE THREAD

**Issue by jofone** [aspnetboilerplate/module-zero#234]
I'm using Abp with ModuleZero on a project, and this project is for a single company, so I disabled multitenancy:
Configuration.MultiTenancy.IsEnabled = false;

When I view the page, it shows an error:
42703: column Extent1.ConnectionString does not exist

**Comment by hikalkan** [comment]
Hi,

When you created your project? Which version of Abp and Abp.Zero packages you're using? Can you check if there is a ConnectionString field in the AbpTenants table?

**Comment by jofone** [comment]
Hi, hikalkan. 
I created this project a few days ago. This is the version we used:
<package id="Abp" version="0.10.3.0" targetFramework="net452" />
<package id="Abp.Zero" version="0.10.1.0" targetFramework="net452" />

And there is no ConnectionString field in the AbpTenants table.

**Comment by hikalkan** [comment]
Did you run "update-database" command? Because, AbpTenants table must have this field.

**Comment by jofone** [comment]
I did run "update-databse", but it has not completely successful, some errors occured.
The database we used is PostgreSQL.

**Comment by hikalkan** [comment]
I hadn't work with PostgreSQL, so could not understand the problem. Which migration has applied lastly? You can check in _MigrationHistory table.

**Comment by jofone** [comment]
The last migration is 201512241146128_Upgrade_To_Module_Zero_0_7_6.
And this is in dbo schema. In 'public' schema, the last migration is 201604271412090_Upgraded_To_V0_9

**Comment by hikalkan** [comment]
You should try to understand what command causes the exception, because I don't have a test environment.

**Comment by jofone** [comment]
Ok, thanks a lot! I'll try to fix it.
