### ISSUE TITLE
Cache name error In Abp.MultiTenancy.TenantCacheManagerExtensions

### ISSUE THREAD

**Issue by jeremyyang824** [aspnetboilerplate/module-zero#238]
Hi:
   I find that  class "Abp.MultiTenancy.TenantCacheManagerExtensions.cs" has an error.
   Whether it should be get cache by name "TenantCacheItem.ByNameCacheName" but not "TenantCacheItem.CacheName" in method TenantCacheItem.CacheName.

[https://github.com/aspnetboilerplate/module-zero/blob/dev/src/Abp.Zero/MultiTenancy/TenantCacheManagerExtensions.cs](url)

**Comment by hikalkan** [comment]
Thank you for informing us.

**Comment by squidwardthetentacles** [comment]
the link is down or moved

**Comment by acjh** [comment]
Moved to `Abp.Zero.Common` [in aspnetboilerplate repo](https://github.com/aspnetboilerplate/aspnetboilerplate/blob/bc266e3503fcb2825684ec829cc356815f94f397/src/Abp.Zero.Common/MultiTenancy/TenantCacheManagerExtensions.cs#L14).
