### ISSUE TITLE
EntityFramework MySQL Not Support AlterTableAnnotations

### ISSUE THREAD

**Issue by baiyunchen** [aspnetboilerplate/module-zero#239]
When I Change ABP-Zero DataBase To **MySQL** and execute update-database -verbose -force, throws an exception:
System.NotImplementedException: AlterTableOperation

**I found Alter Table Annotations just simply add a comment,Can I delete all the files DbMigration Alter Table Annotations?**

**Comment by jaq316** [comment]
The annotations aren't actually necessary. I've implemented a custom migration generator. See below:

```
    public class CustomMigrationMySQLGenerator : MySqlMigrationSqlGenerator
    {
        public override IEnumerable<MigrationStatement> Generate(IEnumerable<MigrationOperation> migrationOperations, string providerManifestToken)
        {
            var statments = new System.Collections.Generic.List<MigrationOperation>();
            foreach (var item in migrationOperations)
            {
                var migration = item as AlterTableOperation;
                if (migration == null)
                {
                    statments.Add(item);
                }
            }
            return base.Generate(statments, providerManifestToken);
        }
    }

```

I then specified that the custom migration generator must be used in the DB migrations config:

`            SetSqlGenerator("MySql.Data.MySqlClient", new CustomMigrationMySQLGenerator());
`

**Comment by baiyunchen** [comment]
@jaq316 thanks.
it's a good idea. Perfect solved my problem.I found that EntityFramework support for Mysql is very poor.The ABP-Zero Migration has many "Cannot drop index 'IX_RoleId': needed in a foreign key constraint error".My solution is first remove the foreign key,then drop index, and then add the deleted foreign key,is there a better way?

**Comment by jaq316** [comment]
Yes. There are many nuances in using EF code first migrations with MySQL. not sure about the dropping of indexes as I've never run into this problem, however, if you use a custom migration generator, you can customize the statements used in doing the migration.

**Comment by mikerouse** [comment]
Finding this workaround in a single Google search has made my day, thank you. 

I also hit the "cannot drop index" problem above, but got out of it by using these migrations:

[http://forum.aspnetboilerplate.com/viewtopic.php?p=6918&sid=fc68362a4a8cbc5313b308eaf2aad028#p6918](http://forum.aspnetboilerplate.com/viewtopic.php?p=6918&sid=fc68362a4a8cbc5313b308eaf2aad028#p6918)

They were provided by, and props to, GuillaumeJ.
