### ISSUE TITLE
Permission loading

### ISSUE THREAD

**Issue by Otgontugs** [aspnetboilerplate/module-zero#24]
I've seen that PermissionChecker is added to the Abp.Authorization. I want to implement authorization in module-zero. I tried to insert a record to AbpPermission table with corresponding RoleId, UserId fields values and Name="TestPermission", IsGranted=1. I also added [AbpAuthorize("TestPermission")] to a controller action. But there NullPermissionChecker is used. Where should i load all permissions from database?

**Comment by emaish** [comment]
I can't see any effect from Permission table, all user always get all permission

**Comment by hikalkan** [comment]
Check https://github.com/aspnetboilerplate/module-zero/tree/master/sample
PermissionChecker is implemented.

**Comment by emaish** [comment]
Dear, you updated the sample with the not published yet libraries :), all people will got errors :(

**Comment by Otgontugs** [comment]
Thank you
