### ISSUE TITLE
Remove IdentityFrameworkClaimsAbpSession

### ISSUE THREAD

**Issue by hikalkan** [aspnetboilerplate/module-zero#240]
Not needed to this class since ClaimsAbpSession handles all.

**Comment by andmattia** [comment]
I Asp.Zero the class AbpNetZeroAbpSession need to be exclude e remove on initialization???
mat

**Comment by hikalkan** [comment]
AbpNetZeroAbpSession should be derived from ClaimsAbpSession, instead of IdentityFrameworkClaimsAbpSession like that: https://github.com/aspnetzero/aspnet-zero/blob/master/src/MyCompanyName.AbpZeroTemplate.Core/Runtime/Session/AspNetZeroAbpSession.cs
