### ISSUE TITLE
found a bug

### ISSUE THREAD

**Issue by csharpweb** [aspnetboilerplate/module-zero#241]
at line 64 in the file 
src\Abp.Zero\Organizations\OrganizationUnit.cs

`        [Required]
        [StringLength(MaxDisplayNameLength)]
        public virtual string Code { get; set; }`
and it  should be
`        [Required]
        [StringLength(MaxCodeLength)]
        public virtual string Code { get; set; }`

**Comment by hikalkan** [comment]
Fixed https://github.com/aspnetboilerplate/module-zero/commit/705db5a52578df7cf8d86cbec4f4991f43433a58
Thanks for reporting.
