### ISSUE TITLE
 Project Source Code Version is too new

### ISSUE THREAD

**Issue by YINZHU2016** [aspnetboilerplate/module-zero#242]
Hello  Halil İbrahim Kalkan
       You Project is so great project.i'm is a china .NET developer.i want to use you project to study and use it .  when i down load you [module-zero] project.i find some error.
**The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found.**
      I know this may be my vs2015 is too old version.
      But you know.In my country.there many vs2010,vs2013,vs2015 version development tool.
      Because our code programming technology is relatively backward, general **.net version** will be behind you .
      **Is there has some version in you project can be use in old vs2015 or vs2013?**
                                                                                                                                        thanks very muck

**Comment by hikalkan** [comment]
Hi,

Thank you very much for trying to use ABP.
Unfortunately, current templates works best in VS 2015 (with latest Updates) and you may have some problems with older versions.
