### ISSUE TITLE
Error detail not sent by server

### ISSUE THREAD

**Issue by tonidy** [aspnetboilerplate/module-zero#243]
Hi,

When I access http://localhost:6240/Application#/welcome then I get the following error (see image below).

![image](https://cloud.githubusercontent.com/assets/823034/18132293/77f81558-6fc0-11e6-8592-a8a9ef68c7e5.png)

Here stacktrace : https://gist.github.com/tonidy/f8268b74cb5d130fbafada0901589029

**Comment by tonidy** [comment]
I know workaround for this issue is restart IIS express. But if ABP could handle it, it would be great. Sorry I could not give the minimum reproduce steps.

**Comment by hikalkan** [comment]
Can you see it Logs why this happen?

**Comment by tonidy** [comment]
Luckily I can debug it :smile:. I found the error in file https://github.com/aspnetboilerplate/module-zero/blob/dev/src/Abp.Zero/MultiTenancy/TenantCache.cs line 75.

```csharp
var tenant = GetTenantOrNull(tenantId);
return CreateTenantCacheItem(tenant);
```

So, the culprit is `GetTenantOrNull` method. It causes `CreateTenantCacheItem` get null reference exception.

**Comment by hikalkan** [comment]
Thank you. But why it can not find the tenant? What is tenant id and did you check if there is a tenant in the database?

**Comment by tonidy** [comment]
> But why it can not find the tenant? What is tenant id and did you check if there is a tenant in the database?

When I access tenantId in immediate window:
```
tenantId

Cannot obtain value of the local variable or argument because it is not available at this instruction pointer, possibly because it has been optimized away.
```
Any alternative way to get tenantId?

Yes, I have check AbpTenants table has tenant record.

**Comment by hikalkan** [comment]
I suppose you run another application in same TCP port which have different tenants. Then you changed it without logout from the application and tenantid cookie remained in the browser. Anyway, we can ignore it.

**Comment by tonidy** [comment]
> Then you changed it without logout from the application and tenantid cookie remained in the browser
Agreed, I think cookie still remained in the browser while I didn't logout 

> Anyway, we can ignore it.
Okay, I saw you have committed to fix this issue. Thanks
