### ISSUE TITLE
unable to find version '0.5.0.4' of package 'abp'

### ISSUE THREAD

**Issue by emaish** [aspnetboilerplate/module-zero#25]
i got error message unable to find version '0.5.0.4' of package 'abp' when i try to restore packages for the sample project.

**Comment by hikalkan** [comment]
Hi,

ABP 0.5.0.4 is not published yet and it's in-work. If you really want to use it, first download ABP, compile in release, create nuget packages. Then in VS add this foldet to nuget package sources.

**Comment by emaish** [comment]
Thank you

**Comment by hikalkan** [comment]
Hi,

Released nuget packages. Please get latest version from github.

**Comment by emaish** [comment]
You are the best :)

**Comment by hikalkan** [comment]
:)
