### ISSUE TITLE
ChangeAbpTablePrefix should add “AbpUserClaims”

### ISSUE THREAD

**Issue by ChiakiYu** [aspnetboilerplate/module-zero#256]
``SetTableName<AbpUserClaims>(modelBuilder, prefix + "UserClaims", schemaName);``

**Comment by hikalkan** [comment]
Thank you for finding this bug. Until it's released, you can do this in your ``OnModelCreating`` method:

````C#
modelBuilder.Entity<UserClaim>().ToTable("...");
````
