### ISSUE TITLE
Abp.Zero.SampleApp.NHibernate.Should_Find_User_By_Name test fail when loading SQLite dll

### ISSUE THREAD

**Issue by brunobertechini** [aspnetboilerplate/module-zero#261]
I've downloaded (forked) module-zero source code and im trying to run unit tests.

The test below:
`Abp.Zero.SampleApp.NHibernate.Should_Find_User_By_Name`
fails with the exception 
`An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)`

I have tried to change Test Architecture to x86 and x64 with no success.

Any thoughts?

I believe is something related to SQLite.Integration.dll loading in x86/x64 environments.

Im using Windows 10 x64 with VS2015 Community

Bruno

**Comment by brunobertechini** [comment]
For reference: [http://stackoverflow.com/questions/15400265/error-opening-conn-with-system-data-sqlite-an-attempt-was-made-to-load-a-progra](url)

**Comment by hikalkan** [comment]
Yes, this is a known problem. Because AppVeyor uses 32 bit test environment and if we use 64 bit version our test is passed but AppVeyor fails. So, I prefered to fail in my environment and run properly in AppVeyor.

**Comment by brunobertechini** [comment]
The strange issue is even if I Mark Visual Studio to use 32bits processor architecture it doesnt work.

```
Menu Test\TestSettings\DefaultProcessorArchitecture\x86
```

**Comment by brunobertechini** [comment]
Maybe you can use VSTS for building integrated with AppVeyor.

Do you have any constraints to use AppVeyor or its just a preferrable choice in your point of view ?

**Comment by hikalkan** [comment]
Hi,

I don't have any constraints. It's one of the popular CI services and I just used it.

> even if I Mark Visual Studio to use 32bits processor architecture it doesnt work

But if we copy 64bit version of the dll, it works.
