### ISSUE TITLE
Invalid Token - Password Reset

### ISSUE THREAD

**Issue by psyvision** [aspnetboilerplate/module-zero#262]
I am having problems since upgrading to ABP and Module Zero v1.0 with the password reset functionality.  When attempting to reset the password I am given the IdentityResult with an error "Invalid Token".

I have removed the temporary workaround for the DataProtectionProvider that used to be detailed in https://github.com/aspnetboilerplate/module-zero/issues/50 and then carried out the steps mentioned:
1. Ref NuGet package Abp.Zero.Owin as part of web project
2. Added [DependsOn(typeof(AbpZeroOwinModule))] to WebModule
3. Called app.RegisterDataProtectionProvider(); after app.UseAbp()

I am generating my token via:

```
string token = await userManager.GeneratePasswordResetTokenAsync(user.Id);
```

And carrying out the reset with:

```
await userManager.ResetPasswordAsync(user.Id, input.Token, input.NewPassword);
```

**Comment by emaish** [comment]
Does userManager.GeneratePasswordResetTokenAsync(user.Id); update the database table record with generated token, i don't think so,  you need to update it with yourself

**Comment by psyvision** [comment]
No it doesn't.  I have changed my code so that this is now stored in the PasswordResetCode field.  But I still receive the Invalid Token error.

**Comment by hikalkan** [comment]
This maybe related to https://github.com/aspnetboilerplate/module-zero/issues/263 ?

**Comment by ismcagdas** [comment]
Tested and seems like resolved.

**Comment by psyvision** [comment]
@ismcagdas what did you test this with?  I have implemented a non-UserManager based work around for this because I can't get it working. #263 seems to relate to AspNetCore which I am not using.

Is there a planned NuGet release of change since v1.0 soon?

**Comment by hikalkan** [comment]
v1.1 is completed, updating docs and will release soon (probably today).

**Comment by psyvision** [comment]
Thanks, I'll give it a test and report back.

**Comment by psyvision** [comment]
I'm still having issues with this after upgrading to v1.1.1.

I'm trying to find out why (will report any extra information as I find it) but I'm still receiving an "Invalid Token" response to:

```
await userManager.ResetPasswordAsync(user.Id, input.Token, input.NewPassword);
```

**Comment by hikalkan** [comment]
Hi,

Maybe it's because of old tokens in database? Can you generate a new token?

**Comment by psyvision** [comment]
I think I've just tracked it down.  I think I had implemented SecurityStamp as part of the User class before it was in AbpUser, therefore it's not getting the correct value as part of the token generation/validation.

**Comment by psyvision** [comment]
Yes - this is working.  Thanks!
