### ISSUE TITLE
AuthenticationManager.SignIn() always persist cookie in google chrome !

### ISSUE THREAD

**Issue by emaish** [aspnetboilerplate/module-zero#27]
When i login to the sample project from google chrome it always make the cookie persistent, when i lose the browser and open it again it doesn't require login, it only happens with chrome, no problem with IE.
Any one else have this issue ?!

**Comment by hikalkan** [comment]
Actually, it uses ASP.NET Identity Framework's built-in SignIn method. I'll test it in my computer.

**Comment by emaish** [comment]
did you check it ?

**Comment by hikalkan** [comment]
Yes, it is. Currently I could not understand why. But I think it's related to Identitiy framework rather than ABP. We should search it a bit.

**Comment by emaish** [comment]
i figured out the reason for this behavior, at least my case, it's related to chrome.
There is a setting in chrome > setting > system > "Continue running background apps when Google Chrome is closed"
if you un check this option the cookie will be deleted and every thing will be fine.
this [link](https://code.google.com/p/chromium/issues/detail?id=128513) inspired me but my case was related to another option.

**Comment by hikalkan** [comment]
Thanks for the information.

**Comment by emaish** [comment]
welcome dear
