### ISSUE TITLE
Set language per user or per domain

### ISSUE THREAD

**Issue by diegosword** [aspnetboilerplate/module-zero#272]
Hi, i have 2 questions.
1. I want to know if it is possible to set the language per user instead of per tenant.  So when the user logs in the application loads in the language defined for the user.
2. Is it possible to set the language depending of the domain ending like www.test.com.us for english and www.test.com.es for spanish?
I any ideas how to do this? thanks

**Comment by hikalkan** [comment]
Hi,

1. Language can be set/get for a user using setting manager. ABP reads the language from cookie (https://github.com/aspnetboilerplate/aspnetboilerplate/blob/dev/src/Abp.Web/Web/AbpWebApplication.cs#L72). Default cookie name is "Abp.Localization.CultureName". It's value can be "en", "en-US" and so on.
So, if you set this cookie when user logged in, then ABP will get the true language from cookie.

ABP (1.0) automatically sets language for current user (https://github.com/aspnetboilerplate/aspnetboilerplate/blob/dev/src/Abp.Web.Mvc/Web/Mvc/Controllers/Localization/AbpLocalizationController.cs#L37) when you change language in the standard startup template.

The setting name is defined in LocalizationSettingNames.DefaultLanguage constant (in Abp.Localization namespace). To get current value of the setting, use setting manager (see document: http://www.aspnetboilerplate.com/Pages/Documents/Setting-Management). So, you can get it from setting manager and set the cookie on login.

2. Yes, override SetCurrentCulture in global.asax (see the original code: https://github.com/aspnetboilerplate/aspnetboilerplate/blob/dev/src/Abp.Web/Web/AbpWebApplication.cs#L72). Here, you can get URL from Request object and set Thread.CurrentThread.CurrentUICulture.

**Comment by thanhdevapp** [comment]
Hi, so, i using aspnet core how to default language with cultureName

**Comment by jamesatgithub** [comment]
@hikalkan Any suggestion to do localization per user based on user's settings in db? I need to return localized message from api controllers but don't want client to send language per each call, reading user's language local in db is prefered

**Comment by hikalkan** [comment]
You can get it from setting manager:

````C#
//Get for current user in AbpSession
var language = SettingManager.GetSettingValueAsync(LocalizationSettingNames.DefaultLanguage);

//Get by user id
var language = SettingManager.GetSettingValueForUserAsync(LocalizationSettingNames.DefaultLanguage, tenant-id, user-id);
````

You can also use SettingManager to change setting's value for a user.

**Comment by jamesatgithub** [comment]
@hikalkan what should be the best practice to set default language for a site by configuration, I see this thread https://github.com/aspnetboilerplate/aspnetboilerplate/issues/692 and changed the setting value to 'zh-CN' but the site still used English as default, only works after I override the SetCurrentCulture in global.asax

**Comment by hikalkan** [comment]
@jamesatgithub have you tried to set it in the database?

**Comment by jamesatgithub** [comment]
@hikalkan yes I set that value in the AbpSettings table, I'll double check if this still an issue I'll report here

**Comment by jamesatgithub** [comment]
@hikalkan it works. I read this doc https://aspnetboilerplate.com/Pages/Documents/Localization again and realized it could the cookie of the old language preference is overriding the database setting, after clearing cookie and the default language by setting works
