### ISSUE TITLE
UserManager.UpdateAsync doesn't properly check former UserName.

### ISSUE THREAD

**Issue by PmzDev** [aspnetboilerplate/module-zero#273]
Hi,
I've an issue while trying to change admin UserName:  I can't get the CanNotRenameAdminUser error.

Here is my AppService code:
``` C#
public async Task UpdateUser(UpdateUserInput input)
        {
            var user = (await UserManager.GetUserByIdAsync(input.Id));
            input.MapTo(user);
            CheckErrors(await UserManager.UpdateAsync(user));
        }
```
After debugging the code of the AbpUserManager, it appears that there is a problem on this line:
``` C#
var oldUserName = (await GetUserByIdAsync(user.Id)).UserName;
```
In my case, the oldUserName is set to the new value. How could I have this working please ?

**Comment by hikalkan** [comment]
Hi,

It probably because of EF. It caches Entity in the memory and does not re-get from database. Thus, ``(await GetUserByIdAsync(user.Id)).UserName`` gets the changed username.

I'll try to solve this problem. For now, check it yourself before ``input.MapTo(user);`` line.
