### ISSUE TITLE
social login bug

### ISSUE THREAD

**Issue by Poepon** [aspnetboilerplate/module-zero#275]
After the login success, back to the login page, the use of social login, will be an exception.
Page display:
[Un authorized operation]

[You are not authorized to perform this operation]

I think we should be able to directly use the social login.

**Comment by Poepon** [comment]
What can be done to achieve this effect?

**Comment by hikalkan** [comment]
Can you share stacktrace, full exception message and which template you are using?

**Comment by Poepon** [comment]
Is not an exception error, should be logged in the process of BUG.
In the case has been successfully logged in, and then request a social login, this problem will appear.
This could be caused by UseCookieAuthentication. Because the login Cookie already exists.
My current solution is to enter the Login Action, the use of _signInManager.SignOutAllAsync (), and then re-enter the Login Action.
But I feel that this is not a good solution.

**Comment by hikalkan** [comment]
When user clicks to social login button, you should logout the user before continue. I think this is reasonable, why you didn't like it?
BTW, are you using AspNet Core version with module-zero? If so, it may be related to https://github.com/aspnet/Announcements/issues/201

**Comment by Poepon** [comment]
I see.
Thank you.
