### ISSUE TITLE
Possible security issue

### ISSUE THREAD

**Issue by brendan-rice** [aspnetboilerplate/module-zero#28]
While trying to debug a login issue I noticed that the username and password are send as part of the request payload via an ajax call:

password: "123qwe"
rememberMe: false
usernameOrEmailAddress: "admin"

Is this a security issue? Would it not be better to let the login happen on an ASP.Net MVC form post rather than ajax?

**Comment by hikalkan** [comment]
Hi,

Actually, there is no big difference while you're not using HTTPS. If you use HTTP, both will send password as plain text. Is this the problem you say?
Also, sample project is just a sample. You can change it if you need more security.

**Comment by brendan-rice** [comment]
You are right Halil, sorry I wasn't thinking.

HTTPS it is then.
