### ISSUE TITLE
AbpLoginManager.cs should have read-only injected properties protected

### ISSUE THREAD

**Issue by gpcaretti** [aspnetboilerplate/module-zero#280]
v. 1.0.0+ 
/src/Abp.Zero/Authorization/AbpLoginManager.cs has all the read-only injected properties marked as private.

They should be public or protected for using in derived class (see AbpUserManager<>).

**Comment by hikalkan** [comment]
Since they are constructor-injected, you can assign an object to a a field of your derived class if you need. But, I'll make commonly used ones protected.
