### ISSUE TITLE
Can I Override Login Method To Avoid TenantName

### ISSUE THREAD

**Issue by krishnandusarkar** [aspnetboilerplate/module-zero#285]
I'm planning to develop a Multi Tenant SaaS Application hosted in the could. I'm using ASP.NET BoilerPlate. Can I override `_logInManager.LoginAsync` to override allowing users to logging in without TenancyName?

I tried navigating through the code, but it seems like, the Abp.Zero Module is bundled and source code is not present in the BoilerPlate Template.

**Comment by hikalkan** [comment]
Hi,

Tenancy name is required since business rule is that: a username can be re-used accross different tenants. That means you can create an "admin" user for tenant A and an "admin" user for tenant B. If you don't provide tenancyname on login, how we can know which user you wanted to login (also, login method internally checks if given tenant is active)?

BUT... you don't have to get tenant name from user in the login form. If you are using subdomains to identify tenants (like tenantA.mydomain.com), then don't add tenancy name to login form, but get it from subdomain in the code.

**Comment by krishnandusarkar** [comment]
@hikalkan Thanks a lot for your reply. The whole framework of ASP.NET Boilerplate is matching with that of my requirements except this one situation.

In my case, usernames will be same as emails (something which most of the application now follow to ease remembering of usernames) and thus I need to override this business logic to perform login irrespective of tenant. And upon login, the app would return me (and set) the tenant details (to session / token).

So in my case, users would be unique across tenants. Any idea how can I override this?

**Comment by hikalkan** [comment]
So, you can do it like that: In the AccountController.Login, first disable IMayHaveTenant filter and query user from IReposiory<User, long>, something like that:

````C#
int? tenantId;
CurrentUnitOfWork.DisableFilter(AbpDataFilters.MayHaveTenant)
{
    tenantId = _userRepository.FirstOrDefault(u => u.EmailAddress = input.EmailAddress)?.tenantId;
}

//get tenant from tenant repository to find it's tenancyname (or use ITenantCache)
````

Then you will have the tenancyName. You can pass it to the LoginManager.

BUT.. remember that this only works if all tenants are in same database. If you use database per tenant approach, you can not execute query accross multiple databases.

**Comment by krishnandusarkar** [comment]
@hikalkan That's great!! Yes I can do that. Do you require TenantID or TenantName?

I have two more questions...

- Can I remove tenantName property from Login Model? API Users of mine otherwise would get confused with that property around.

- Most importatantly, how can I modify the access token? I mean I need to add more return values like TenantID and other initial values on successful login which the apps can store and send me on consecutive requests.

**Comment by hikalkan** [comment]
Login method needs tenancyname. You can see it's signature: https://github.com/aspnetboilerplate/module-zero/blob/dev/src/Abp.Zero/Authorization/AbpLoginManager.cs#L114

For the token question; you may want to check this: https://gist.github.com/hikalkan/67469e05475c2d18cb88 (it may be different in your case, but the fundamental idea is to add claims to the cookie/token)

**Comment by krishnandusarkar** [comment]
Thanks a lot @hikalkan :)
