### ISSUE TITLE
Separate tenant group by database

### ISSUE THREAD

**Issue by marcosribj** [aspnetboilerplate/module-zero#286]
I'm interested in hybrid database

I would like to split tenants group between database

For example:

Database1 = TenantA, TenantB and TenantC
Database2 = TenantD, TenantF
...

In this case, would I have three databases? One for users, role e tenant data, and two others for the tenants and yours informations?

Would it be enough to pass the connectionstring to each tenant and use UOW?

In this example, a Tenant group shares the same bank

So I'll always have to use
```
  using (_unitOfWorkManager.Current.SetTenantId(AbpSession.GetTenantId()))
         {
             return MyRepository.Method ();
         }
```
UOW is limited to the repository? Or any action from my dbcontext?
```
using(_unitOfWorkManager.Current.SetTenant(AbpSession.GetTenantId())
{  
   myAnyService.AccessAnyInMyDbContext()
}

```
is ok?

**Comment by hikalkan** [comment]
````
Database1 = TenantA, TenantB and TenantC
Database2 = TenantD, TenantF
````

For this case, you can have 2 or 3 databases. If you want to store host data (host users, roles, tenants... tables) in a separated db, you will have a 3rd database. If you, for example, want to store host data in database1, then you can have 2 databases.

It's enough to pass connection string while creating new tenant (for module-zero startup template). Then it will handle the rest. You normally don't need to manually use SetTenant to switch tenants unless you want to switch to a different tenant than the current tenant in AbpSession. If you need to switch to a tenant, it will handle all, not only repositories.

**Comment by marcosribj** [comment]
@hikalkan  
With this new implementation DapperRepository has been deprecated?

**Comment by hikalkan** [comment]
This is not related to Dapper. Also, ABP has not built-in DapperRepository.

BTW, DbContext factory is for EF. There is also a ConnectionStringResolver (which is used by DbContextResolver).
