### ISSUE TITLE
Connect With Azure AD 

### ISSUE THREAD

**Issue by krishnandusarkar** [aspnetboilerplate/module-zero#287]
Hi, I have gone through your documentation of LDAP Settings. But my requirement is kind of, I'll definitely run it in multi tenant mode and the WebAPI's will be consumed by Mobile App and the Web Portal will be used by my internal support people to create tenants or edit anything if the consumers of WebAPI are having problem.

So my query is, can I connect the Web Portal with Azure AD? Only specific people whom I add to Azure AD can login and operate in Web Portal.

**Comment by hikalkan** [comment]
Current LDAP integration does not run for Azure AD (I don't know if it's working actually).
But you can create a class to authenticated with Azure AD. See documentation: http://www.aspnetboilerplate.com/Pages/Documents/Zero/User-Management#external-authentication

**Comment by krishnandusarkar** [comment]
Thanks I'll try that :)

**Comment by wocar** [comment]
When you are done implementing your solution, mind sharing it with us?
Thank you :)

**Comment by krishnandusarkar** [comment]
Sure @wocar :) If I can successfully implement it, I'll surely share it here for benefit of others
