### ISSUE TITLE
Some questions about OU

### ISSUE THREAD

**Issue by maliming** [aspnetboilerplate/module-zero#289]
The OU does not have permission.
I think some permissions to bind in the department or position is more reasonable.
What ABP OU design idea is?
How do I combine permissions and OUs?

**Comment by hikalkan** [comment]
Hi,

Permission system is used to restrict application functionality (say, creating a user, see a report...), OU is used to restrict application data (say, see a subset of data in the report, or see data related to his own OU). See doc: http://www.aspnetboilerplate.com/Pages/Documents/Zero/Organization-Units

Your suggestion is also seems reasonable at first sight. And I think https://github.com/aspnetboilerplate/module-zero/issues/187 is a more general concept of that.

**Comment by maliming** [comment]
In other words, ou and Permissions no relationship? Difficult or should not let both Associated with?

**Comment by hikalkan** [comment]
I depends on what you want to achive. Example scenario:

You want to have an OU which have several members. Then you want to set one of the users as 'manager', so a manager can assign tasks to the members of this OU.

To achive it; you can define a 'assign task to members' permission and create a 'Manager' role which has this permission. Then you can assign manager role to a user in the OU. Then you can allow this manager to assign tasks to users in same OU (you can filter users for a OU). Thus, you can combine permissions and OUs.

**Comment by maliming** [comment]
You each ideas are enough I think some time. Our team will discuss this question. Before I do not know OU is used to restrict application data.Now I deeper understanding of the OU. Thank 👍
