### ISSUE TITLE
Permission Checker - Permission override

### ISSUE THREAD

**Issue by emaish** [aspnetboilerplate/module-zero#29]
In Permission Checker, it would be nice that granting a permission for a user override setting for a role for the same permission, for example if a permission "CreateTicket" is granted to a role "A" where users "X,Y,Z" is under that role, suppose i want to allow all user under role "A" to get that permission expect User Z, so i create a permission record for "CreateTicket" with User Z and dis-grant it, is it possible now?, and if it's n't , could you consider it an enhancement ?

After testing, i see that Role permission override User permission what ever records order "Order shouldn't matter any way" but it should be the opposite :)

**Comment by hikalkan** [comment]
Hi,

It's planned exactly like that but not implemented yet. User-specific permission setting will override roles of the user.

**Comment by hikalkan** [comment]
It will be implemented in a very near future.

**Comment by emaish** [comment]
Thank you, i'm watching ;)

**Comment by emaish** [comment]
Thank you, i'm watching ;)

**Comment by emaish** [comment]
Hi dear,
Can you give me  guidelines to implement it by my own, as i need it for my current on going project

**Comment by hikalkan** [comment]
If you have time, plase wait I will implement in 2 weeks at most (as I planned).

**Comment by emaish** [comment]
I can survive for 2 weeks :), thank you dear

**Comment by hikalkan** [comment]
It's implemented ;)

**Comment by emaish** [comment]
I noticed that few days ago, and i implemeted it on the system, thank you dear :)
