### ISSUE TITLE
Documentation tag for AbpUser.PhoneNumber is incorrect

### ISSUE THREAD

**Issue by junghandy** [aspnetboilerplate/module-zero#290]
The summary text for AbpUser.IsPhoneNumberConfirmed reads "Is the `AbpUserBase.EmailAddress` confirmed." when it should probably read "Is the `AbpUser.PhoneNumber` confirmed."

See https://github.com/aspnetboilerplate/module-zero/blob/dev/src/Abp.Zero/Authorization/Users/AbpUser.cs#L136

**Comment by hikalkan** [comment]
Thanks a lot. Fixed: https://github.com/aspnetboilerplate/module-zero/commit/36f950756fbca1a42920f054fc5de3d462ce4d06
