### ISSUE TITLE
Active Directory based authentication

### ISSUE THREAD

**Issue by nandaccio** [aspnetboilerplate/module-zero#297]
Does module-zero support a configuration like the following one, we need to send AD requests to

````
Base DN = "DC=region,DC=intra,DC=dummy,DC=com" 
Server name = "servername.region.intra.dummy.com" 
Alternate server name = "servername2.region.intra.dummy.com" 
TCP Port = 3268 (global catalog) 
````

As our authorization server.

I added Abp.Zero.Ldap.Domain to [dbo].[AbpSettings] and the corresponding value is retrieved successfully from:

````C#
  public LDAPAuthenticationSource(ILdapSettings settings, IAbpZeroLdapModuleConfig ldapModuleConfig)
            : base(settings, ldapModuleConfig)
        {
// HERE settings settings.GetDomain returns the expected value stored in the database
        }
````
Configuration.Modules.ZeroLdap().Enable(typeof(OurLDAPAuthenticationSource));  is invoked in the PreInitialize() method of our module and  Configuration.Modules.ZeroLdap().IsEnabled returns TRUE. 

But I have no idea if the LDAP-based authentication actually takes places or if module-zero is only making the authorization against the local database (AbpUsers, AbpRoles, etc).

**Comment by hikalkan** [comment]
As you know, you derived your class from LdapAuthenticationSource (https://github.com/aspnetboilerplate/module-zero/blob/dev/src/Abp.Zero.Ldap/Ldap/Authentication/LdapAuthenticationSource.cs). You can override any method to see if it's called. For example, override TryAuthenticateAsync and add a breakpoint. It should be called when user logging in.
Also, I suggest you to check this class. You can override any method to customize it.

**Comment by nandaccio** [comment]
It actually works! At least, TryAuthenticateAsync is invoked as expected. I guess that I'll have to put there the logic to make requests to:

**Comment by nandaccio** [comment]
I found it. GetLoginResultAsync is invoked first, then the TryAuthenticateAsync method of my LDAPAuthenticationSource class. Great!
