### ISSUE TITLE
Register account with facebook error because contrains foreign key

### ISSUE THREAD

**Issue by thanhdevapp** [aspnetboilerplate/module-zero#300]
I get error when register with facebook, i debug and see in sql insert id  not match with id of table user, i need drop constrain to fix, i think is id of facebook 

SqlException: The INSERT statement conflicted with the FOREIGN KEY SAME TABLE constraint "FK_dbo.AbpUsers_dbo.AbpUsers_CreatorUserId". The conflict occurred in database "ABPnetcoreDb", table "dbo.AbpUsers", column 'Id'.
The statement has been terminated.

**Comment by hikalkan** [comment]
Which template are you using?

**Comment by hikalkan** [comment]
moved to https://github.com/aspnetboilerplate/aspnetboilerplate-templates/issues/49

**Comment by ismcagdas** [comment]
Hi @thanhdevapp,

Which version do you use ? ASP.NET MVC 5.x or ASP.NET Core ?
