### ISSUE TITLE
A constructible type deriving from dbContext could not be found in the selected file

### ISSUE THREAD

**Issue by sujanmah062** [aspnetboilerplate/module-zero#301]
Hi all,

I'm using Abp.0.10.3.1 version.  When i try to generate precompiled view using EF PowerTools Beta 4 and it says "A constructible type deriving from dbContext could not be found in the selected file". 

Could someone please help me to solve this problem.
Thanks in advance

**Comment by hikalkan** [comment]
Never tried EF PowerTools before. Can you share your dbcontext constructors? Maybe it waits for a default constructor.

**Comment by sujanmah062** [comment]
public PropertyDbContext() : base("Default")
        {
                  
        }
       
   public PropertyDbContext(string nameOrConnectionString) : base("Default")
        {
          
        }
  
  public PropertyDbContext(DbConnection dbConnection) : base(dbConnection, true)
        {

        }

**Comment by sujanmah062** [comment]
Hi @hikalkan 
I googled around and thought "public class PropertyDbContext : AbpZeroDbContext<MyTenant, MyRole, MyUser>" might be the cause. When i replace AbpZeroDbContext<MyTenant, MyRole, MyUser> with DbContext it says "Could not load file or assembly Abp, version 0.10.3.1"

![screenshot_1](https://cloud.githubusercontent.com/assets/25734794/22877384/52ddaf02-f1fd-11e6-89e5-34e662d64786.png)

**Comment by hikalkan** [comment]
AbpZeroDbContext<MyTenant, MyRole, MyUser> is a generic class. I don't think that it does not support a generic base class. I will test it.

**Comment by hikalkan** [comment]
I suppose this tool does not support inheritance.
If you want to create code first classes for your database, I suggest you to do it in an empty project (without ABP) then copy your classes into your ABP based solution.
