### ISSUE TITLE
OrganizationUnitManager Create issue

### ISSUE THREAD

**Issue by maliming** [aspnetboilerplate/module-zero#302]
[OrganizationUnitManager.cs#L31](https://github.com/aspnetboilerplate/module-zero/blob/dev/src/Abp.Zero/Organizations/OrganizationUnitManager.cs#L31)

I think this should be `await OrganizationUnitRepository.InsertAndGetIdAsync (organizationUnit);`

Or if once create multiple ou, containing parent id not easily。

**Comment by maliming** [comment]
`
 var organizationUnit = new OrganizationUnit(tenantId: AbpSession.TenantId, displayName: tree.Key, parentId: id);
          _organizationUnitManager.Create(organizationUnit);
//_unitOfWorkManager.Current.SaveChanges();
var childrenOrganizationUnit = new OrganizationUnit
{
          TenantId = AbpSession.TenantId,
           DisplayName = "",
           ParentId = organizationUnit.Id,
};
              _organizationUnitManager.Create(childrenOrganizationUnit);

`

**Comment by hikalkan** [comment]
It should get id when you call ``_unitOfWorkManager.Current.SaveChanges();``. Doesn't it work?

**Comment by maliming** [comment]
yes，its work，Perhaps should not be internal call savechange. thanks！
