### ISSUE TITLE
Is Lockout functionality working after MaxFailedAccessAttemptsBeforeLockout ?

### ISSUE THREAD

**Issue by emaish** [aspnetboilerplate/module-zero#303]
It's not working with me

**Comment by hikalkan** [comment]
The user's IsLockoutEnabled should be true in the database. Can you check it?

**Comment by hikalkan** [comment]
When I enable it in the database it worked.

But there is a problem in the startup templates. They don't show an appropriate error message for user lockout. I created an issue for that: https://github.com/aspnetboilerplate/aspnetboilerplate-templates/issues/46

BTW, you can change AccountController.CreateExceptionForFailedLoginAttempt method to handle lockout case.

**Comment by emaish** [comment]
i already changed CreateExceptionForFailedLoginAttempt , but i didn't know that IsLockoutEnabled  should be toggled on, it's not documented :) 

Thank you

**Comment by hikalkan** [comment]
Actually, this is a feature of Microsoft.AspNet.Identity. This is why we haven't documented user lockout feature at all.
But I made it enabled by default for next releases (https://github.com/aspnetboilerplate/module-zero/commit/919e8f0b3f13109a722e9e750850189e2cca7519)
