### ISSUE TITLE
Why can not create new permissions after the application is started?

### ISSUE THREAD

**Issue by maliming** [aspnetboilerplate/module-zero#304]
as this title.

**Comment by maliming** [comment]
I found a way to create it

```
var _permissionDefinitionContext = (IPermissionDefinitionContext)_permissionManager;
_permissionDefinitionContext.CreatePermission("test");
```

**Comment by hikalkan** [comment]
ABP's permissions are hard-coded. That means their names are known in development time. For example, you can use such an attribute for an application service:

````C#
[AbpAuthorize("CanDeleteBlogPosts"]
public void DeleteBlogPost(...)
{
    ...
}
````

With such a usage, it's not possible to make this permission name dynamic.

In brief, we think we know permissions in the development time and no meaning to create dynamic permissions on runtime.

But, surely you may have different requirements that need to dynamic permissions. Can you describe your situation?

**Comment by maliming** [comment]
Our company has a number of subsidiaries, in an application office. (Not multi-tenant applications).

We currently have SubsidiaryA, SubsidiaryB.
X employees in SubsidiaryA. 
Y employees at SubsidiaryB.

The application has a ViewCompanyAddressBook function:
```
Public void ViewCompanyAddressBook (...)
{
/*
Customize the permissions check, 
this method checks if the end of the employee permission string contains "ViewCompanyAddressBook".
Get Permissions for Custom Attributes: SubsidiaryId
Which is why I want to extend permission https://github.com/aspnetboilerplate/aspnetboilerplate/issues/1861
Finally perform business logic, now we do not consider how to detect permissions
*/
}
```

Business needs:
Employees can only view the company's address book.
But also allows him to see other subsidiaries of the address book.

So the application permissions will have multiple, such as:
SubsidiaryA.ViewCompanyAddressBook
SubsidiaryB.ViewCompanyAddressBook

X employees have SubsidiaryA.ViewCompanyAddressBook permissions.
Y employees have SubsidiaryA.ViewCompanyAddressBook, SubsidiaryB.ViewCompanyAddressBook permissions.

Subsidiaries may be dynamically added, but abp permissions can not be created dynamically.

**Comment by hikalkan** [comment]
Even permissions was dynamic, I think permission system is not proper for such a business rule. I suggest you to use organization units (so, you can add a user to more than one OU to allow to see address book of given OUs) or create your own table to maintain you custom permissions.

**Comment by maliming** [comment]
The idea above is based on what we want to use abp permissions. 
Thank you very much for your reply, we will think about other ways. 😊
