### ISSUE TITLE
Add an attribute to the OrganizationUnit Entity.

### ISSUE THREAD

**Issue by maliming** [aspnetboilerplate/module-zero#305]
hi @hikalkan 
I think you should add an attribute to the OrganizationUnit Entity, such as Name or any other attribute.
If we need to query out a tree structure in the OU when using this property.

Because DisplayName may be modified by the UI, but Name will not change in general.
The service layer uses the Name property when getting the OU tree.
UI modification DisplayName does not need to rewrite the service layer to get the OU method.

**Comment by hikalkan** [comment]
Organization Unit has a Code property for that. Do you know it?

**Comment by maliming** [comment]
Code may change and are not readable. But Name can be customized.

**Comment by hikalkan** [comment]
Do you want to show this Name on UI? If so, how will you localize it? And, is that will be an hard-coded name?
Anyway, actually you can a new property as described here: https://www.aspnetzero.com/Documents/Extending-Existing-Entities#extending-non-abstract-entities
While this doc is for Edition entity, it's similar for OU entity too.

**Comment by maliming** [comment]
DisplayName is displayed on the UI(), and Name is used in the application.
We can modify the DisplayName on the UI, but it does not affect the application layer method.
```
 public void GetOusAndChildren()
 {

    |-Mobile phone   =>  DisplayName:"Mobile phone", Name:"Phone"
    |---Samsung
    |---Apple
    |---Nokia
    
    |-XXX Company Departments   =>  DisplayName:"XXX Company Departments", Name:"Departments"
    |---HumanResources
    |---FinanceDepartment
    |---CustomerService

     var Phone = _organizationUnitRepository.GetAll().Where(x => x.Name == "Phone").FirstOrDefault();
     var PhoneTree = _organizationUnitRepository.GetAll().Where(x => x.Code.StartsWith(Phone.Code));

     var Department = _organizationUnitRepository.GetAll().Where(x => x.Name == "Department").FirstOrDefault();
     var DepartmentTree = _organizationUnitRepository.GetAll().Where(x => x.Code.StartsWith(Department.Code));
 }
```

**Comment by maliming** [comment]
I know that can be extended, just feel abp should also be added.

**Comment by hikalkan** [comment]
In most applications, OUs are completely dynamic but in some applications some OUs can be static. I'm not sure if this is a common requirement.
Please extend it for you. If it's not hard, no need to add to the framework.

**Comment by maliming** [comment]
ok I'll do that. Thank you so much!
