### ISSUE TITLE
Refresh Token

### ISSUE THREAD

**Issue by marcosribj** [aspnetboilerplate/module-zero#307]
Implement refresh token feature
Why ? Because prevent the theft of access_token, and leave its life cycle lower and guarantees auto login for the user(only refresh your token)

**Comment by rcyq** [comment]
Hi can I check if this feature will be included in v2.0 stable release?

**Comment by hikalkan** [comment]
No. But we will look for Identity Server 4 integration just after 2.0 (.net standard) release. Identity Server 4 has already that mechanism.

**Comment by hikalkan** [comment]
Closing since we are integrating to https://github.com/aspnetboilerplate/module-zero/issues/358
