### ISSUE TITLE
How Use SwitchToLinkedAccount ?

### ISSUE THREAD

**Issue by mona6767** [aspnetboilerplate/module-zero#308]
hello,

best regard .

How use "SwitchToLinkedAccount" for user in AccountController ?

thank you .

**Comment by hikalkan** [comment]
Hi,

As I know, there is no such a feature in free templates. Where is it?

**Comment by mona6767** [comment]
salam! 

bebakhshid./

i see that on "aspnetzero.com" demo .

so , i need multi account for one UserId , for login with different Tenant ! 

is it possible for module-zero ?

can i use "ImpersonateSignIn" for this ?

mamnon.

**Comment by hikalkan** [comment]
For module-zero, you should develop it yourself. But it's not so hard.
I don't know where did you see ImpersonateSignIn?

**Comment by mona6767** [comment]
i see that here : 
https://gist.githubusercontent.com/hikalkan/8862d9f7ae8b4874976d/raw/c3a6af68584184fb49a5d9823d313ec9b0806ba2/AccountController.cs

**Comment by mona6767** [comment]
very thank you .

**Comment by hikalkan** [comment]
Hi,

I had shared this to people want to know how to implement this. So, you can take it as a starting point to build this feature.

**Comment by mona6767** [comment]
of course, very thank you .
