### ISSUE TITLE
IsGranted and complex permissions

### ISSUE THREAD

**Issue by Worthy7** [aspnetboilerplate/module-zero#311]
At the moment I have written a bunch of functions inside each service such as:

CanEdit(EntityDto input) {
//has super admin permission then return true
//can edit because it is related to this user then return true
return false
}

I read in the documentation that "IsGranted" could be overwritten to perform all kinds of logic. I guess this would be using a large switch/case statement for each of the permissions.

If I do this, then when I call IsGranted using Ajax, I won't have the PermissionNames strongly typed - which is why I've avoided this method.
Instead I am calling my service layer: services.App.Orders.CheckCanEdit({Id: Id})

My questions are:
1) Does my method seem sound? Or am I missing something in terms of best practice. Should all permission management be under IsGranted?
2) Regarding the strong typecasting problem, do you know any solution to this?

Thanks

**Comment by hikalkan** [comment]
Your case requires "per entity permissions". ABP does not provide a solution for that except organization unit system which may help you. So, you can go however you like.

**Comment by Worthy7** [comment]
The solution would be to have some kind of advanced PermissionChecker class custom for ones solution which would allow for any number of `CheckIfUserCan` type functions, which in turn would allow all services to do these kinds of checks nicely. It's outside the scope of ABP.
