### ISSUE TITLE
How do you properly configure multi tenancy?

### ISSUE THREAD

**Issue by brendan-rice** [aspnetboilerplate/module-zero#32]
Currently I have the following code to set the multi tenancy, in the AccountController constructor.

At some point the default tenant gets switched to Tenant 1, so if I am logged in as Tenant 2 all of a sudden I can see Tenant 1 in the app. This is a pretty big security issue for me, due to the nature of the project.

-- Full AccountController class --
https://gist.github.com/brendan-rice/aa8815eb9d9d76fb9419

    public AccountController(QuoteMonkeeUserManager userManager, IRepository<User, long> userRepository,
            IRepository<Tenant> tenantRepository, MultiTenancyConfig multiTenancy)
        {
            _userManager = userManager;
            _userRepository = userRepository;
            _tenantRepository = tenantRepository;
            _multiTenancy = multiTenancy;
            _multiTenancy.IsEnabled = true;
        }

What is the correct way to configure multi tenancy, making sure the tenant gets persisted?

**Comment by langman66** [comment]
In my Web project (based of the Zero sample project), I have the following:

public class ModuleZeroSampleProjectWebModule : AbpModule{

            //Setup for multi-tenancy.
            Configuration.Modules.Zero().MultiTenancy.IsEnabled = true;

}

I'm not sure if you would want to set the IsEnabled on each construction of your AccountController, but rather once when the application boots up.

Chris

**Comment by brendan-rice** [comment]
Thanks for that Chris, where do you put that code, in the  PreInitialize or the Initialize method?

**Comment by langman66** [comment]
I followed the documentation found at this link   

http://www.aspnetboilerplate.com/Pages/Documents/Startup-Configuration  

Preinitialize mehod is where I have the changes

**Comment by easyest** [comment]
Just don't forget to manually add `Zero` configuration namespace - extension methods are not resolved automatically.
```c#
using Abp.Zero.Configuration;
```

**Comment by brendan-rice** [comment]
Thanks

**Comment by Otgontugs** [comment]
Hi Buddies,
I'm developing and web application which is customers' basic information are shared by 2 organization.  Each organization finds a customer by social security number and then adds its organization specific informations. All other informations such as products, login users, sales are separate. In this case, Is the following the correct use of tenancy? 
public class Organization: AbpTenant {}; 
public class User: AbpUser { }; 
public class Product { Organization org; // and other fields ... }; 
public class Customer { // Here is no Organization instance };

**Comment by brendan-rice** [comment]
That looks about right

**Comment by Otgontugs** [comment]
Thank you for tooo fast answer ;) So i'll try to implemet this.

**Comment by easyest** [comment]
@brendan-rice, please close the issue if the question has been answered. This will save few seconds for tracker moderator.
