### ISSUE TITLE
[UnitOfWork] property in the Controller

### ISSUE THREAD

**Issue by maliming** [aspnetboilerplate/module-zero#320]
[module-zero-template AccountController](https://github.com/aspnetboilerplate/module-zero-template/blob/master/src/AbpCompanyName.AbpProjectName.WebMpa/Controllers/AccountController.cs#L177)

```
[HttpPost]
[UnitOfWork]
public virtual async Task<ActionResult> Register(RegisterViewModel model)
{
....
```

Why is this marked [UnitOfWork], and other methods are not marked, as far as I know . Controller default is the unit of work, I am confused.

**Comment by hikalkan** [comment]
I suppose this is an old code. Written when controller actions were not unit of work by default. We can remove it.

**Comment by hikalkan** [comment]
moved to https://github.com/aspnetboilerplate/aspnetboilerplate-templates/issues/51
