### ISSUE TITLE
questions with roles and users;

### ISSUE THREAD

**Issue by xyfy** [aspnetboilerplate/module-zero#321]
I have several roles ,a role have its own user model。

for example:
the [Seller] Role  have Seller Model
the [Admin] Role have Admin Model
the [Buyer] Role have  [Buyer] Model

Is there any better method to resolve my scene?

I want to overload  Abp.Authorization.AbpLogInManager,but the property [userManager] is AbpUserManager is readonly,cannot overwrite in sub-class.

**Comment by hikalkan** [comment]
Hi,

I think you want to create multiple User types. You can create subclasses of User. It's not proper to make it via roles which are just used to group permissions.

**Comment by xyfy** [comment]
if I create subclasses of User ,  do I need to rewrite the 【zero】?   Some property of classes could not overload,
for example:
the property [userManager] in AbpUserManager is readonly

**Comment by xyfy** [comment]
I do not use you source code ,only find it in nuget.

**Comment by hikalkan** [comment]
User class can be inherited without changing Abp.Zero source code.  User code is in your own solution. UserManager will work with base User class, but nor problem EF supports inheritance. You can use TPH approach.

**Comment by xyfy** [comment]
`     public class loginmanager : AbpLogInManager<Tenant, Role, User>
    {
       
        public loginmanager(AbpUserManager<Role, User> userManager, IMultiTenancyConfig multiTenancyConfig, IRepository<Tenant> tenantRepository, IUnitOfWorkManager unitOfWorkManager, ISettingManager settingManager, IRepository<UserLoginAttempt, long> userLoginAttemptRepository, IUserManagementConfig userManagementConfig, IIocResolver iocResolver, AbpRoleManager<Role, User> roleManager) : base(userManager, multiTenancyConfig, tenantRepository, unitOfWorkManager, settingManager, userLoginAttemptRepository, userManagementConfig, iocResolver, roleManager)
        {
            this.UserManager = userManager;
        }
    }`

there is an error in [this.UserManager = userManager;],   it's a readonly property.

**Comment by xyfy** [comment]
In this scene , is better to use TPT approach?

**Comment by xyfy** [comment]
What's the relation between User & UserAccount

**Comment by hikalkan** [comment]
UserAccount is a simplified and unified Users table. With database per tenant approach, each tenant's users are stored in their own database and it's not possible to query from all users in a single query. UserAccounts are always stored in the host database (and synchronized with all tenant users), so we can query from it in certain cases.
