### ISSUE TITLE
How to use cellphone to login

### ISSUE THREAD

**Issue by xyfy** [aspnetboilerplate/module-zero#322]
you provide using the email to login.

but if i want to using the cellphone to login.how to do this?

**Comment by hikalkan** [comment]
Do you mean two factor login? If so, you can do that yourself. AspNet Identity has two-factor auth feature.

**Comment by xyfy** [comment]
no,I  want to use [username or cellphone] to login, not use  [username or email] to login which is default.

**Comment by maliming** [comment]
[Phone numbers are not guaranteed to be unique today, they are not  #keys](https://github.com/aspnet/Identity/pull/1055)

#https://github.com/aspnet/Identity/pull/1055

**Comment by hikalkan** [comment]
AbpLoginManager does not support this, but you may change AccountController.Login method to handle it yourself (query database for cellphone, find user, check password and make login).

**Comment by xyfy** [comment]
I know this way,but I am not tend to use this.

it's perfect when you can define such methods in your source code ,

**Comment by ChiakiYu** [comment]
In  `_logInManager.LoginAsync` ,it call `UserManager.AbpStore.FindByNameOrEmailAsync`  
so you can override `FindByNameOrEmailAsync` like 
```
 public override async Task<User> FindByNameOrEmailAsync(string userNameOrEmailAddress)
 {
     return await _userRepository.FirstOrDefaultAsync(
        user => (user.UserName == userNameOrEmailAddress 
            || user.EmailAddress == userNameOrEmailAddress
            || user.PhoneNumber == userNameOrEmailAddress));
 }

```

**Comment by xyfy** [comment]
thanks,I know this way.  but the method name is not match the content
