### ISSUE TITLE
TPH questions

### ISSUE THREAD

**Issue by xyfy** [aspnetboilerplate/module-zero#325]
When I created sub-class for Users , the table added column named "Discriminator"

How can I use this column to filter data???

**Comment by hikalkan** [comment]
It's Entity Framework's own field. You can search web if you want to find more about that (this is not related to ABP).

**Comment by xyfy** [comment]
I'm sorry ,but where I used it in abp.zero ,      it's hard to use.    with abp.zero when I derive serveral class from User,     how can I use the sub-class?      

May be I should overload   the [Users] property in [AbpZeroDbContext] class?

**Comment by hikalkan** [comment]
Hi. You can read this document to understand inheritance on EF: https://weblogs.asp.net/manavi/inheritance-mapping-strategies-with-entity-framework-code-first-ctp5-part-1-table-per-hierarchy-tph
