### ISSUE TITLE
Localization problem.

### ISSUE THREAD

**Issue by scorpion86** [aspnetboilerplate/module-zero#326]
Hi I downloaded AspNetCore 1.x Multi Page Web App template with modul-zero. When i try to login with wrong password it gives an exception (Must Set LocalizationSourceName before, in order to get LocalizationSource). But i can change language on ui.

**Comment by hikalkan** [comment]
Maybe this is missed for the project. Can you check: https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Core/Controllers/AbpProjectNameControllerBase.cs#L11

**Comment by scorpion86** [comment]
I checked it. But the code is same.

**Comment by scorpion86** [comment]
Im using sql express 2016 by the way.

**Comment by hikalkan** [comment]
Add a breakpoint to your class and see if LocalizationSourceName is set to a value? If not, set it from your constructor (actually, in startup templates it's set in base controller, but maybe your controller does not derive from it).

**Comment by scorpion86** [comment]
All my controllers derive from baseclass and i tried it with a new sample which i didnt changed anything. When i look at that property with breakpoint in debug mode i can see that its value have been set.

**Comment by scorpion86** [comment]
i added case AbpLoginResultType.LockedOut and not used L() method and it works. But when i tried to use it with L() method then im  getting that exception again.

**Comment by hikalkan** [comment]
If this exception is thrown in a new template, it's easier to fix. Let us check it. Thanks.

**Comment by ismcagdas** [comment]
Closed https://github.com/aspnetboilerplate/module-zero-core-template/issues/13.
We need to set LocalizationSourceName in constructor of AbpLoginResultTypeHelper because it is not an app service, it derives from AbpServiceBase.
