### ISSUE TITLE
TableNames

### ISSUE THREAD

**Issue by prom3theu5** [aspnetboilerplate/module-zero#327]
Hi. Can we change table names without having to grab source? I see there is a built in extension for it - any pointers on how or where to use it? - I need to add a prefix to the already existing prefix.

**Comment by hikalkan** [comment]
in your dbcontext:

````C#
protected override void OnModelCreating(DbModelBuilder modelBuilder)
{
    base.OnModelCreating(modelBuilder);
    modelBuilder.ChangeAbpTablePrefix<Tenant, Role, User>("MyPrefix");
}
````

**Comment by prom3theu5** [comment]
Awesome sauce - thanks man
And nice work on this :)
