### ISSUE TITLE
How to close [email] required attribute

### ISSUE THREAD

**Issue by xyfy** [aspnetboilerplate/module-zero#329]
My System do not required the [email address]  ,but required cellphone

and I am in Asia ,not use [surname],[name],        one [Name] maybe is all.

how can I do with this scene?

**Comment by hikalkan** [comment]
You can use EF's onmodelcreating to make email optional in database. Then you can check cellphone while creating user. Also, you could easily make a workaround by setting emailadress to a dummy value (like cellphonenumber@yourdomain.com).

**Comment by xyfy** [comment]
so the best way to resolve my question  is setting emailadress to a dummy value(like cellphonenumber@yourdomain.com).
Thanks.
