### ISSUE TITLE
when i search the problem in google,i find that the result point your forum

### ISSUE THREAD

**Issue by Craft24** [aspnetboilerplate/module-zero#335]
when i search the problem in google,i find that the result point your forum,but if you are not logined,you will not see the result.I suggest sincerely that you can let it show openly,because i register it but i also can't login.

**Comment by hikalkan** [comment]
Forum is open, you can read it without login normally. Can you send your username and the forum topic you want to see.

**Comment by Craft24** [comment]
It's ok,I can search it and see it today.My user name it's`KingSun`,If the forum can search directly,it will be more convenient for both of us.

**Comment by hikalkan** [comment]
You can search on the forum:

![image](https://cloud.githubusercontent.com/assets/1210527/24694963/99deb89e-19ec-11e7-9c66-41915227213c.png)

**Comment by Craft24** [comment]
ok,i get it,thank you!It'a good job.It's an amazing framework.
