### ISSUE TITLE
AbpUserManager.IsGrantedAsync multiplies the queries in database

### ISSUE THREAD

**Issue by jfbaudracco** [aspnetboilerplate/module-zero#336]
Hi,

Since v1.5.1, AbpUserManager.IsGrantedAsync includes a supplementary test : 

`//User not found
if (await FindByIdAsync(userId) == null)
{
return false;
}`

So, each permission test queries database.
Multiples IsGrantedAsync calls in a loop produce multiples queries that in this context are not required.
For example, GetMenuAsync produces multiples queries. The same, each GetScripts, on each page loading, produces same effect.

Perhaps, it is possible to test if the user exists uniquely if the permission is not first found in the cache !
If yes, on user deletion, the cache should be cleared. 
I do not know if this is a solution.

Thank you

**Comment by hikalkan** [comment]
I agree with that and will consider as a high priority issue. Thanks.
