### ISSUE TITLE
how to remove some of the attributes AbpUser?

### ISSUE THREAD

**Issue by maliming** [aspnetboilerplate/module-zero#337]
Such as: Name , Surname attribute.

**Comment by hikalkan** [comment]
You can configure EF to ingore these properties (in onmodelcreating).

**Comment by maliming** [comment]
thank you very much

**Comment by ltm0203** [comment]
protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {         
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<User>().Property(a => a.Name).IsOptional();
            modelBuilder.Entity<User>().Property(a => a.Name).HasMaxLength(35);
            modelBuilder.Entity<User>().Property(a => a.Surname).IsOptional();
            modelBuilder.Entity<User>().Property(a => a.Surname).HasMaxLength(35);
            modelBuilder.Entity<User>().Property(a => a.EmailAddress).IsOptional();

        }

This is set Name Surname is optional, but there is no effect.Error is also very funny

![Paste_Image.png](http://upload-images.jianshu.io/upload_images/1979022-0f4f6ee49ff04b0f.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![Paste_Image.png](http://upload-images.jianshu.io/upload_images/1979022-6042857c249de143.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

As shown, still hint my name is required
This is the design of the database
![Paste_Image.png](http://upload-images.jianshu.io/upload_images/1979022-101e34952e24c454.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
@hikalkan

**Comment by ltm0203** [comment]
我修改下配置信息,使用ignore来去除name
 protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
                base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<User>().Ignore(a => a.Name);
            modelBuilder.Entity<User>().Ignore(a => a.Surname);
            modelBuilder.Entity<User>().Property(a => a.EmailAddress).IsOptional();

        }
![Paste_Image.png](http://upload-images.jianshu.io/upload_images/1979022-c76b63442611e820.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

Still hint my name for the required fields
@hikalkan 

Please look at how I this situation, if there is one solution, the more the better.thank you

**Comment by hikalkan** [comment]
One more option is to override User properties and add attributes. But as I know, OnModelCreating must work normally.

**Comment by maliming** [comment]
@hikalkan 
override property add [NotMapped] attribute still does not work.

**Comment by maliming** [comment]
@hikalkan 

I found a solution [**Private new**]
```
[NotMapped]
Private new string Name {get; set;}

[NotMapped]
Private new string SurName {get; set;}
```
this is okay!

**Comment by ltm0203** [comment]
@hikalkan  
The above is my modified code
 `
 public class User : AbpUser<User>{
  
        private new string Name { get; set; }

        private new string Surname { get; set; }

        [Required(AllowEmptyStrings = true)]
        public override string EmailAddress { get; set; }
}
`

**Comment by maliming** [comment]
Other options:
We can manually verify the entity before the property assignment (property is not in the database).
I do not know if this is the best practice, but in the database to remove some of the properties, VS IntelliSense also remind us that we no longer use these property.

```
[AttributeUsage(AttributeTargets.Property)]
public class NotRequiredAttribute : System.Attribute
{

}
   
public class User : AbpUser<User>
{

   [Obsolete("Surname is no longer used.", true)]
   [NotMapped]
   [NotRequired]
   public override string Surname { get; set; }

   [Obsolete("Name is no longer used.", true)]
   [NotMapped]
   [NotRequired]
   public override string Name { get; set; }

   [Obsolete("FullName is no longer used.", true)]
   [NotMapped]
   public override string FullName { get; }
   
}

public override int SaveChanges()
{
   SetNotRequired();
   return base.SaveChanges();
}

public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken)
{
   SetNotRequired();
   return await base.SaveChangesAsync(cancellationToken);
}

private void SetNotRequired()
{
   var entries = ChangeTracker.Entries().ToList();
   foreach (var entry in entries)
   {
      entry.Entity.GetType()
         .GetProperties()
         .Where(x => x.GetCustomAttributes(typeof(NotRequiredAttribute), true).Any()).ForEach(x =>
         {
            x.SetValue(entry.Entity, "this is not required");
         });
   }
}
```
