### ISSUE TITLE
Question: Register a User Without Logging in as Admin

### ISSUE THREAD

**Issue by coommark** [aspnetboilerplate/module-zero#338]
I'm trying to register a new user on the .Net Core, MVC version. So I send this via Postman:

```
{
	"TenancyName" : "",
	"Name" : "Markie",
	"Surname" : "Meltony",
	"UserName" : "coommarkie",
	"EmailAddress" : "coommarkie@gmail.com",
	"Password" : "SAwyakubu78$",
	"IsExternalLogin" : true
}
```
The object is  received in the Register method as expected, everything runs without throwing an error, but the user is not registered (stored in the DB).

However when I log in and use the user creation form this goes. Why is it so? How can I register a user via a WebAPI call?

**Comment by hikalkan** [comment]
Do you see anything in logs?

**Comment by coommark** [comment]
Hi @hikalkan , thank you always for the help. I created a different api controller, commented out the `[AbpAuthorize(PermissionNames.Pages_Users)]` on the `UserAppService` and I am back in the game, rolling like a rockstar. Thank you!

**Comment by hikalkan** [comment]
But be carefull on that since you removed authorization completely. Instead, you could add [AbpAllowAnonymous] for your Register method only.

**Comment by coommark** [comment]
Oh! Thank you for that. I will do that.
