### ISSUE TITLE
UserManager.CreateAsync password issue

### ISSUE THREAD

**Issue by amalmansouri** [aspnetboilerplate/module-zero#34]
I'm using createAsync and the password is "123qwe" but this is the password I'm founding in the db
AF786NYuaPWo4C9/+g6IxTMB+pz6m/eeVgPJx65mj206zG9klJzHWmrWZtYKM5Raqg==

which it should be as the sample shows 
AM4OLBpptxBYmM79lGOX9egzZk3vIQU3d/gFCJzaBjAPXzYIK3tQ2N7X4fcrHtElTw==  //123qwe

this cause a problem when trying to find user as it always shows 'Null' 

I'm using following method to get user 
var user = await _userManager.FindByEmailAsync(registerModel.UsernameOrEmailAddress);

Note: I'm registering user then sign-out then Sign-In and getting this error.
Any Idea?? what I'm doing wrong here?

**Comment by amalmansouri** [comment]
I finally resolve the problem 

IsEmailConfirmed was False and that's why I received null 

I update it to True and now everything is working fine.

**Comment by emaish** [comment]
close the issue please
