### ISSUE TITLE
Diferences between Permission to RoleClaim

### ISSUE THREAD

**Issue by alexandrejose** [aspnetboilerplate/module-zero#340]
Hi,
    I'm looking for IdentityServer branch and comparing Permission(Module zero) with RoleClaim(AspnetIdentityCore).

I saw that in AbpRoleStore now has methods for two models(Permission and RoleClaim), and for me both are to do the same thing, do you did this for maintain compatibility?

One more question is about IsGranted, in permission we have this concept and I didn't see in RoleClaim, do you plane to migrate this concept?

Thanks.

**Comment by hikalkan** [comment]
RoleClaim is a new entity came with Identity Core (was not included AspNet Identity 2.x). So, we had Permission system. RoleClaim can be thought as similar. But, in general, claims are less changeable and permissions are more changeable things.

See this great article about this discussion: https://leastprivilege.com/2016/12/16/identity-vs-permissions/

**Comment by alexandrejose** [comment]
Thanks a lot, I understood.
