### ISSUE TITLE
support IdentityServer3 and IdentityServer4

### ISSUE THREAD

**Issue by robertosistemas** [aspnetboilerplate/module-zero#347]
I wish module zero would support IdentityServer3 and IdentityServer4.
theses startekits implements it:
https://github.com/joeaudette/cloudscribe.StarterKits

**Comment by hikalkan** [comment]
We will work on IdentityServer4, it's a high priority work next versions.

**Comment by hikalkan** [comment]
Closing this for https://github.com/aspnetboilerplate/module-zero/issues/358

**Comment by cuibty** [comment]
IdentityServer3 supported?

**Comment by hikalkan** [comment]
No, only for AspNet Core & Identity Server 4 implemented. We don't think to work on IdentityServer3.

**Comment by cuibty** [comment]
tks!
