### ISSUE TITLE
SettingManager Scopes conflict with logic

### ISSUE THREAD

**Issue by emaish** [aspnetboilerplate/module-zero#35]
The perfect SettingManager should go through all setting levels if the setting scope is User, it should be apple to read the setting value from the "Definition", then override from "Application" setting db record if found then override from "Tenant" setting db record if found then override from "User" setting db record if found.
in SettingManager.GetAllSettingValuesAsync() doesn't do that as each SettingDefinition may has only one scope in its definition.

Example for Setting with user scope
1- Setting "A" with default value 'False' is defined as user scope so user can change it with his own value,
2- The admin changed the application value for this setting to 'True' (UserId and TenantId are null in database for this setting)
3- when user open his setting page he should see 'True' (as it should be because application value in database should override the default value) but he sees 'False' because the method GetAllSettingValuesAsync skip reading the value fro "A" setting because its scope is user not application :(
-----------------------
Example for Setting with application scope
1- Setting "B" with default value 'False' is defined as application scope
2- The admin changed the application value for this setting to 'True' (UserId and TenantId are null in database for this setting)
3- when user open his setting page he will always see 'True' whatever the value he save because the method GetAllSettingValuesAsync will never read his saved value because its scope is Application not User :(

so do i understand correctly or what ?!

**Comment by hikalkan** [comment]
Answered here: https://github.com/aspnetboilerplate/aspnetboilerplate/issues/340
