### ISSUE TITLE
Does not enforce unique username or unique email

### ISSUE THREAD

**Issue by coommark** [aspnetboilerplate/module-zero#351]
I am having a weird issue. I have been developing an application using ASP.NET Core Multipage template. For some time, user registration worked alright. Unique constrains on usernames and emails were enforced. However, this no longer works. I can create multiple users with exactly same usernames and emails.

Before this, the two major changes I made include: 

1. Deleted migrations including the initial because they were getting too many and recreated them.
2. Deleted the database and recreated it.

Could these be the cause? Everything appears to be ok except this. Where should I look for pointers?

**Comment by hikalkan** [comment]
These should not effect it. Are you using UserManager to create new users? If so, it always checks uniqueness (https://github.com/aspnetboilerplate/module-zero/blob/dev/src/Abp.Zero/Authorization/Users/AbpUserManager.cs#L106). You can create a demo on aspnetzero.com and try to create a user with same username with an existing user. I just tested and it works.

**Comment by coommark** [comment]
That was totally my mistake. I [AbpAllowAnonymous] at User registration, but forgot to set the Tenancy. Did this: `CurrentUnitOfWork.SetTenantId(input.TenantId);` and now I am good.

@hikalkan But your response above was what helped me. After following the sample from your link, it still could not find the user. That was when I figured!
