### ISSUE TITLE
 Increase size of AuditLog properties

### ISSUE THREAD

**Issue by jmhinnen** [aspnetboilerplate/module-zero#352]
Small request, we have some methods that have very large parameters being passed.  Mainly around large complex orders in an ordering system.

Is there a reason that the following columns are limited?

Parameters
Exception
CustomData

Seems to me, other than this table already takes up a large amount of space, but for diagnosing issues, limiting those columns seems harsh.

On the flip side of that, what could I do to implement this myself.  All the AuditLog stuff is way down deep in the framework.  Is there an easy way for me to override those and change the behavior?

Thanks as always!

**Comment by hikalkan** [comment]
Hi,

The only possibility is to replace IAuditingStore by your own implementation. You can see current code from here: https://github.com/aspnetboilerplate/module-zero/blob/dev/src/Abp.Zero.Common/Auditing/AuditingStore.cs and https://github.com/aspnetboilerplate/module-zero/blob/dev/src/Abp.Zero.Common/Auditing/AuditLog.cs

AuditLog.CreateFromAuditInfo truncates it. So, you should not use it in your store.
You should change max lenghts of AuditLog properties via EF fluent mapping configuration.

But we can also take this as an enhancement request for next release.

**Comment by ebicoglu** [comment]
From now on In AbpZeroDbContext you can override the properties below;
MaxServiceNameLength, MaxMethodNameLength, MaxParametersLength, MaxClientIpAddressLength, MaxClientNameLength, MaxBrowserInfoLength, MaxExceptionLength, MaxCustomDataLength

For your case; in DbContext you need to set MaxParametersLength, MaxExceptionLength and MaxCustomDataLength to a larger value than the default just before base.OnModelCreating row.

```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    AuditLog.MaxParametersLength = 4000;
    //other fields...

    base.OnModelCreating(modelBuilder);

    //...
}

```
