### ISSUE TITLE
Update from 1.5.2 to 2.0.2

### ISSUE THREAD

**Issue by prom3theu5** [aspnetboilerplate/module-zero#353]
Hi
I'm using a module-zero starter template which is built with 1.5.2
Do you foresee any issues with updating all of ABP to 2.0.2 including module zero?
Are there any breaking changes?

Also - As another minor gripe I have - is there a simple way to disable logging the passwords in plain text in the AuditLog table for authentication requests?
Currently even successful authentication's (token and web) get logged in plain text.

Cheers

**Comment by hikalkan** [comment]
There are a few minor breaking changes and you can easily understand it from compiler messages and fix them.

Use [DisableAuditing] for any attribute you want to hide: https://www.aspnetboilerplate.com/Pages/Documents/Audit-Logging#DocEnableDisableByAttrs

**Comment by prom3theu5** [comment]
Excellent - thanks a lot :)
