### ISSUE TITLE
Is there a way to use override module-zero internal Localization?

### ISSUE THREAD

**Issue by GutierrezDev** [aspnetboilerplate/module-zero#356]
Hi guys and thanks for the excellent framework.

Im trying to fix a problem I have. 
When Im using my own Localization (in Core Layer) everthing is OK with the language template but properties that exist in module-zero I cant figure out how to override the values.
Example: 
module-zero/src/Abp.Zero.Common/Zero/Localization/Source/AbpZero.xml is defined in module Zero but if I define those keys in my own template file, the framework still uses the Module-Zero template.
Is there a way to that without using the source code and compling my own version of module-zero?

**Comment by hikalkan** [comment]
Yes: https://www.aspnetboilerplate.com/Pages/Documents/Localization#DocExtending

**Comment by GutierrezDev** [comment]
Thanks so much Halil. I need to read the full documentation.
