### ISSUE TITLE
Tenant is not loaded in user entity

### ISSUE THREAD

**Issue by easyest** [aspnetboilerplate/module-zero#36]
ModuleZeroSampleApp with default seed gives this:
![image](https://cloud.githubusercontent.com/assets/6928101/6319176/72b79570-babb-11e4-8c72-3c6d6b0cc1ec.png)

Take look at tenant for user emre - it should be loaded, as there is `TenantId`.

Did this test as tenants are not loaded for any user on my page.

**Comment by easyest** [comment]
What's even more strange is that `Tenant` is loaded into `User` just perfectly in the `Seed` method of `Configuration` (I checked that using debugger attach).

**Comment by hikalkan** [comment]
I updated the solution, so I'm closing this now.
