### ISSUE TITLE
Role Claims in AbpRole with incorrect foreign key

### ISSUE THREAD

**Issue by rcyq** [aspnetboilerplate/module-zero#362]
I noticed that under AspZeroCore, the property "RoleClaims" in AbpRole is referencing UserId as foreign key

```        
/// <summary>
/// Claims of this user.
/// </summary>
[ForeignKey("UserId")]
public virtual ICollection<RoleClaim> Claims { get; set; }
```

https://github.com/aspnetboilerplate/module-zero/blob/6dd18867d9f519db1ea4b98e9d46b48b6642478b/src/Abp.ZeroCore/Authorization/Roles/AbpRole.cs

**Comment by hikalkan** [comment]
Thank you for informing. Fixed it.
