### ISSUE TITLE
Apereo .NET CAS client integration 

### ISSUE THREAD

**Issue by jamesatgithub** [aspnetboilerplate/module-zero#365]
I tried to integrate with the CAS .net client (https://github.com/apereo/dotnet-cas-client) for single-sign-on and have got the user principal from CAS server, e.g. HttpContext.Current.User.Identity.Name with the correct username from CAS server, but still got 403 on controllers with [AbpMvcAuthorize], any suggestion to get CAS working with Abp?

**Comment by hikalkan** [comment]
I don't have an idea about CAS. If you want to know which claims are checked for IAbpSession, see ClaimsAbpSession: https://github.com/aspnetboilerplate/aspnetboilerplate/blob/dev/src/Abp/Runtime/Session/ClaimsAbpSession.cs

You can find claim types here: https://github.com/aspnetboilerplate/aspnetboilerplate/blob/dev/src/Abp/Runtime/Security/AbpClaimTypes.cs

If HttpContext.Current.User.Identity contains related claims, then ABP will know the user and will work properly.

**Comment by jamesatgithub** [comment]
@hikalkan  Thanks for the clarification, very informative. I think I need to add the abp claims in CAS client CasPrincipal.cs constructor https://github.com/apereo/dotnet-cas-client/blob/master/DotNetCasClient/Security/CasPrincipal.cs#L214

I'm not sure if this is the best place to add the required abp claims since I need to add abp references to CAC client project, or it's better to add the claims in my Abp Web project somewhere?

**Comment by jamesatgithub** [comment]
@hikalkan I found this thread https://github.com/aspnetboilerplate/aspnetboilerplate/issues/1624 and replaced the IPricencipalAccessor in my Abp Web project

`Configuration.ReplaceService(typeof(Abp.Runtime.Session.IPrincipalAccessor), () => {
                IocManager.Register<Abp.Runtime.Session.IPrincipalAccessor, HttpContextCasPrincipalAccessor>(Abp.Dependency.DependencyLifeStyle.Transient);
            });`

In the HttpContextCasPrincipalAccessor, the CasPrincipal as HttpContext.Current.User is converted to ClaimsPrincipal and required claims are added for Abp. 

Is this the best way?

**Comment by hikalkan** [comment]
This is a good way. I suggest you do it like that. IPrincipalAccessor is an extension point for such customizations.

**Comment by jamesatgithub** [comment]
Thanks @hikalkan it all works well now

**Comment by hoatv1008** [comment]
Hi @jamesatgithub , could you please share us your implementation for HttpContextCasPrincipalAccessor ?

Thanks in advance

**Comment by jamesatgithub** [comment]
@hoatv1008 
` public  class HttpContextCasPrincipalAccessor : DefaultPrincipalAccessor
    {
        private readonly ISessionAppService _sessionAppService;

        public HttpContextCasPrincipalAccessor(ISessionAppService sessionAppService)
        {
            _sessionAppService = sessionAppService;
        }
        public override ClaimsPrincipal Principal
        {
            get
            {
                if (HttpContext.Current != null)
                {
                    //convert CasPrincipal (from CAS) to ClaminsPrincipal which is used by Abp
                    if (HttpContext.Current.User != null && HttpContext.Current.User is DotNetCasClient.Security.CasPrincipal)
                    {
                        ClaimsPrincipal principal = null;
                        try
                        {
                            principal = new ClaimsPrincipal(HttpContext.Current.User);
                        }
                        catch
                        {
                            principal = HttpContext.Current.User as ClaimsPrincipal;
                        }
                        ClaimsIdentity identity = principal.Identity as ClaimsIdentity;
                        return principal;
                    }
                }

               return base.Principal;
            }
        }
    }`

**Comment by hoatv1008** [comment]
Thanks @jamesatgithub for sharing. I've guessed you implemented some sorts of converting from "Username" to "UserId" in the accessor but seems you put it in CAS customization module.

Actually, I am injecting UserManager into the HttpContextCasPrincipalAccessor (as _userManager). Get user info by calling _userManager.FindByNameAsync(HttpContext.Current.User.Identity.Name) then init Abp claims from that user. But it doesn't seem to be a nature way :)
