### ISSUE TITLE
How to extend AbpPermissions to work with existing UserPermissionSetting and RolePermissionSetting?

### ISSUE THREAD

**Issue by jamesatgithub** [aspnetboilerplate/module-zero#367]
I want to add some custom fields in AbpPermissions, and have checked this thread https://github.com/aspnetboilerplate/module-zero/issues/168 

Do I have to add classes inheriting UserPermissionSetting and RolePermissionSetting separately but with same custom fields in the new classes? and also override  UserStore/RoleStore methods to use the repository of the new classes?

**Comment by hikalkan** [comment]
Hi,

What's the purpose of extending? Do you want to use new properties (fields) in the authorization process, or you just want to store some permission-related data in the same table.

**Comment by jamesatgithub** [comment]
@hikalkan the requirement is to add some extended information on permission related data in AbpPermission table

**Comment by hikalkan** [comment]
This table is maintained (entities are created/updated/deleted) internally by the framework. I suggest you to create another entity to store your extra data and create a FK releation.

**Comment by jamesatgithub** [comment]
ok thanks
