### ISSUE TITLE
Add IsActive to LanguageInfo

### ISSUE THREAD

**Issue by ismcagdas** [aspnetboilerplate/module-zero#372]
This will allow enable / disable languages.

**Comment by tom177y** [comment]
Hi Ismail,

To double confirm on this enhancement, it allows administrator to set the list of 'active' languages and therefore, restricting the list of languages the users are able to select as their preferred language in the languages dropdown list?

Thanks.
/Tommy

**Comment by hikalkan** [comment]
It's for that. But "filtering inactive languages to create language selection list" is application's responsibility like:

var activeLanguages = languageManager.GetLanguages().Where(l => !l.IsDisabled).ToList();

**Comment by tom177y** [comment]
Hi Halil,

Thanks for prompt response.  I would also like to confirm if the following behavior is part of the enhancement where "once a user selected a preferred language, the system will always show that specific language regardless of which device used to logged in or cookies or user session".

To understanding, aspnetzero will show the user selected language after logged out and in again but it is NOT permanent as it will revert to system default language if log in using a different device or using "In-private browsing" mode with IE.
