### ISSUE TITLE
Why is the username may only letters and Numbers

### ISSUE THREAD

**Issue by ShiWei-L** [aspnetboilerplate/module-zero#373]
When I want to register an account, I want to use Chinese characters as a user name, but prompt microsft. Identity. Invaliderror, how should I do?

**Comment by hikalkan** [comment]
This is default behaviour of ASP.NET Identity. You can change it in the constructor of your UserManager class like:

````C#
(UserValidator as Microsoft.AspNet.Identity.UserValidator<User, long>).AllowOnlyAlphanumericUserNames = false;
````

**Comment by ShiWei-L** [comment]
Thank you very much
