### ISSUE TITLE
Migrate Abp.Zero to Abp.ZeroCore

### ISSUE THREAD

**Issue by gabrielrobert** [aspnetboilerplate/module-zero#377]
Hi,

Is it feasible to migrate an existing project from `Abp.Zero` to `Abp.ZeroCore` ? Implying:

1. Existing entries in `AbpUser` table.
2. Existing login/logout and registration.
3. Still targeting full framework.

I need to implements `IdentityServer` in my application and Abp did not supported IdentityServer3 for old `Microsoft.AspNet.Identity`, i'm looking forward an upgrade to go `Microsoft.AspNetCore.Identity` with your brand new implementation.

**Comment by hikalkan** [comment]
Hi,

We actually did the same thing, moving from Abp.Zero to Abp.ZeroCore. It takes time but surely possible.
Database has not much change:

![image](https://user-images.githubusercontent.com/1210527/26860064-907b3122-4b44-11e7-8bd4-cdb31a78ea9e.png)

You can take the latest module zero core template as a reference and implement it yourself if you see that it has a value for your project.

**Comment by gabrielrobert** [comment]
Great, thank you @hikalkan. I will use https://github.com/aspnetboilerplate/module-zero-core-template as reference 👍

**Comment by hikalkan** [comment]
Comping a new version of this template: https://twitter.com/aspboilerplate/status/871350397478342656 :) Will be released in 1-2 days.

**Comment by gabrielrobert** [comment]
@hikalkan For your info, it took me 1h58 to migrate to `Abp.ZeroCore`.

I thought it was going to be worse. Let's say I had bad experiences with older versions of Microsoft.Identity 😄 

Have a nice day, keep up the good work!

**Comment by hikalkan** [comment]
Thats very good. Thank you for the feeback.
