### ISSUE TITLE
Register A User and AddToRolesAsync()

### ISSUE THREAD

**Issue by coommark** [aspnetboilerplate/module-zero#378]
I am trying to register a new user and add the user to a set of roles. The problem however, is that the user is not added to the database until after the Register action method has exited.

Here is what I have tried in the `UserAppService`:

```
CurrentUnitOfWork.SetTenantId(input.TenantId);

using (var unitOfWork = _unitOfWorkManager.Begin())
                {
                    CheckErrors(await UserManager.CreateAsync(user));
                    unitOfWork.Complete();
                }

var returnedUser = await UserManager.FindByEmailAsync(user.EmailAddress);
```

The problem is returnedUser is always null because the user only gets inserted after the everything has exited. How can I force the user to be inserted so that I can query the DB and obtain the ID of the new user?

**Comment by acjh** [comment]
Try `await CurrentUnitOfWork.SaveChangesAsync();` after `CreateAsync`

**Comment by coommark** [comment]
Thank you @acjh This works perfect.
