### ISSUE TITLE
Can't login if user has no tenant

### ISSUE THREAD

**Issue by emaish** [aspnetboilerplate/module-zero#38]
in the sample project database seeding there is a part to insert Role and User with null tenant and you call it  "tenancy owner"
but when i try to login with user that is saved in database with no tenant, the _userManager.FindAsync and _userRepository.FirstOrDefaultAsync always return null
i want to be able to login without providing a tenant even when setting MultiTenant.IsEnabled = true because i want to get current tenant from logged in tenant

**Comment by hikalkan** [comment]
I added login method to user manager. Use it: https://github.com/aspnetboilerplate/module-zero/blob/master/src/Abp.Zero/Authorization/Users/AbpUserManager.cs#L65
