### ISSUE TITLE
Remove Tenant generic argument from PermissionChecker

### ISSUE THREAD

**Issue by hikalkan** [aspnetboilerplate/module-zero#380]
To fix it for existing applications, remove Tenant argument from PermissionChecker derived class:

Old version:

````C#
    public class AppPermissionChecker : PermissionChecker<Tenant, Role, User>
    {
        public AppPermissionChecker(UserManager userManager)
            : base(userManager)
        {
        }
    }
````

New version:

````C#
    public class AppPermissionChecker : PermissionChecker<Role, User>
    {
        public AppPermissionChecker(UserManager userManager)
            : base(userManager)
        {
        }
    }
````

**Comment by Zesulile** [comment]
Thank you @hikalkan , now it gives me this error " Required permissions are not granted. At least one of these permissions must be granted: Tenants "

**Comment by hikalkan** [comment]
It's not related to this issue probably. Are you sure that you have the given permission.

**Comment by Zesulile** [comment]
Yes I do have given permissions
