### ISSUE TITLE
Roles List in accessToken

### ISSUE THREAD

**Issue by coommark** [aspnetboilerplate/module-zero#382]
I am working on a single sign on application that authenticates many other applications using a common database. My question is, how can I add roles to the accessToken and return it to the caller?

Currently when I decode my accessToken using [https://jwt.io/](https://jwt.io/), the payload is like this:

```
{
  "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier": "12",
  "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name": "08424721426",
  "http://schemas.microsoft.com/accesscontrolservice/2010/07/claims/identityprovider": "ASP.NET Identity",
  "AspNet.Identity.SecurityStamp": "c484ae9d-c6bd-4ddf-a0c0-9fe422160e7e",
  "http://www.aspnetboilerplate.com/identity/claims/tenantId": "1",
  "sub": "12",
  "jti": "1d1feea0-bba5-48f7-8a72-0e2038e475c5",
  "iat": 1497279036,
  "nbf": 1497279036,
  "exp": 1497365436,
  "iss": "CRM",
  "aud": "CRM"
}
```

Thank you.

**Comment by hikalkan** [comment]
Are you using new [Identity Server integration](https://aspnetboilerplate.com/Pages/Documents/Zero/Identity-Server)?

**Comment by coommark** [comment]
No I don't think so. This is my Web.MVC Startup class is like this:

```
public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            //MVC
            services.AddMvc(options =>
            {
                options.Filters.Add(new AutoValidateAntiforgeryTokenAttribute());
            });

            services.AddScoped<IWebResourceManager, WebResourceManager>();

            //Configure Abp and Dependency Injection
            return services.AddAbp<CRMWebMvcModule>(options =>
            {
                //Configure Log4Net logging
                options.IocManager.IocContainer.AddFacility<LoggingFacility>(
                    f => f.UseAbpLog4Net().WithConfig("log4net.config")
                );
            });
        }
```

So I guess not. I'm using Abp 1.5.1

Thank you

**Comment by hikalkan** [comment]
So, are you using TokenAuthController (https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Core/Controllers/TokenAuthController.cs) to generate tokens. If so, you can change here: https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Core/Controllers/TokenAuthController.cs#L212

**Comment by coommark** [comment]
Thank you. I initially thought so but wanted to verify. I have it working now thanks lots.
