### ISSUE TITLE
InvalidToken - ConfirmEmailAsync

### ISSUE THREAD

**Issue by gabrielrobert** [aspnetboilerplate/module-zero#385]
Consider the following:

`UserManager.cs`
```
 var user = User.CreateTenantAdminUser(
    AbpSession.TenantId.Value,
    input.EmailAddress,
    input.Password
);

user.SetNewEmailConfirmationCode();
user.IsEmailConfirmed = false;

await CreateAsync(user);
```

Then:
`SomeController.cs`
```
var user = await _userManager.GetUserByIdAsync(userId);
var result = await _userManager.ConfirmEmailAsync(user, code);
```

I tried this to be sure:
`await _userManager.ConfirmEmailAsync(user, user.EmailConfirmationCode);`

Any idea?

I'm using latest ABP (2.1) with Microsoft.AspNetCore.Identity.

**Comment by gabrielrobert** [comment]
I also tried to use this:

```
var emailConfirmationToken = await GenerateEmailConfirmationTokenAsync(user);
user.EmailConfirmationCode = emailConfirmationToken;
```

No success.

**Comment by acjh** [comment]
Does this not work?

```c#
var emailConfirmationToken = await GenerateEmailConfirmationTokenAsync(user);
user.EmailConfirmationCode = emailConfirmationToken;
var result = await ConfirmEmailAsync(user, emailConfirmationToken);
```

**Comment by gabrielrobert** [comment]
@acjh Unfortunately, no as stated [here](https://github.com/aspnetboilerplate/module-zero/issues/385#issuecomment-308814242)

**Comment by acjh** [comment]
Your comment doesn't say if you do
```c#
var emailConfirmationToken = await GenerateEmailConfirmationTokenAsync(user);
user.EmailConfirmationCode = emailConfirmationToken;
await CreateAsync(user);
var result = await ConfirmEmailAsync(user, user.EmailConfirmationToken);
```
or
```c#
await CreateAsync(user);
var emailConfirmationToken = await GenerateEmailConfirmationTokenAsync(user);
user.EmailConfirmationCode = emailConfirmationToken;
var result = await ConfirmEmailAsync(user, user.EmailConfirmationToken);
```
The latter works; the former doesn't.

**Comment by gabrielrobert** [comment]
@acjh It's done in two step. First one, user is created with an token. Then the user need to open the email containing the token and click the link.

Yes, the confirmation token is set in the database.

**Comment by acjh** [comment]
How did you generate the link - using `Url.Action`, `UriBuilder`, `StringBuilder` or manually?

**Comment by gabrielrobert** [comment]
@acjh Manually.

```
var encodedCode = HttpUtility.UrlEncode(args.EmailConfirmationCode);
var actionLink = $"account/confirm-email?code={encodedCode}&userId={args.UserId}";
```

But this is not the problem, because I get the email confirmation code directly from the entity. When I will be able to confirm a mail, then I will use my custom generated link.

**Comment by acjh** [comment]
Did you try doing
```c#
await CreateAsync(user);
```
before
```c#
var emailConfirmationToken = await GenerateEmailConfirmationTokenAsync(user);
user.EmailConfirmationCode = emailConfirmationToken;
```
and then
```c#
var result = await ConfirmEmailAsync(user, user.EmailConfirmationToken);
```
as stated [here](https://github.com/aspnetboilerplate/module-zero/issues/385#issuecomment-308827468)?

**Comment by gabrielrobert** [comment]
Yes, and it doesn't work. I also have a function that "resend email confirmation email". It does:

```
var emailConfirmationToken = await GenerateEmailConfirmationTokenAsync(user);
user.IsEmailConfirmed = false;
user.EmailConfirmationCode = emailConfirmationToken;
// send email using emailConfirmationToken and user.Id
```

**Comment by gabrielrobert** [comment]
For some reasons, `ConfirmEmail` started working again when I removed this line:

`user.EmailConfirmationCode = emailConfirmationToken;`

The good flow is:

```
var emailConfirmationToken = await GenerateEmailConfirmationTokenAsync(user);
user.IsEmailConfirmed = false;
// send email using emailConfirmationToken and user.Id
```
