### ISSUE TITLE
learning abp permission source code

### ISSUE THREAD

**Issue by maliming** [aspnetboilerplate/module-zero#389]
``` c#
[UnitOfWork]
public virtual async Task<bool> IsGrantedAsync(UserIdentifier user, string permissionName)
{
	if (CurrentUnitOfWorkProvider == null || CurrentUnitOfWorkProvider.Current == null)
	{
		return await IsGrantedAsync(user.UserId, permissionName);
	}

	using (CurrentUnitOfWorkProvider.Current.SetTenantId(user.TenantId))
	{
		return await _userManager.IsGrantedAsync(user.UserId, permissionName);
	}
}
```
IsGrantedAsync method has [UnitOfWork], Its internal should have uow, why check CurrentUnitOfWorkProvider and CurrentUnitOfWorkProvider.Current?

**Comment by hikalkan** [comment]
I suppose we check ``CurrentUnitOfWorkProvider == null || CurrentUnitOfWorkProvider.Current == null`` because CurrentUnitOfWorkProvider is property injected. But in pratical if will never be null because of [UnitOfWork] attribute.
