### ISSUE TITLE
IFilterByTenant implementation 

### ISSUE THREAD

**Issue by emaish** [aspnetboilerplate/module-zero#39]
is IFilterByTenant implemented in module zero ?, because i implemented IFilterByTenant in my entity and it wasn't filtered by Tenant.
and what about other MultiTenancy "IMayHaveTenant, IMustHaveTenant" are they implemented ?

**Comment by hikalkan** [comment]
Hi,

No, nothing implemented about that. Probably I will implement in a very near future.

**Comment by hikalkan** [comment]
Folow https://github.com/aspnetboilerplate/aspnetboilerplate/issues/391
