### ISSUE TITLE
AbpSession is using the wrong UserId.

### ISSUE THREAD

**Issue by langman66** [aspnetboilerplate/module-zero#40]
I'm working to upgrade my project based on Zero and Abp (0.5.5.0) to the latest version and have run into an issue.  I just pulled down all the last code changes you have in both Abp and Zero master branches.

I have an MVC controller (AccountController) that has a Register method.  I need to create the AbpUser, authenticate the user and then call some additional Service classes to do inserts into various other tables (Subscription, Profile, Payments).  

I need the Insert of the AbpUser to complete the Transaction of creating the user so I can populate my DTO objects in my ApplicationService classes to have the FK (AbpUserId) to properly update the other tables.

Here's a snippet of my Account Register Controller.  If I don't use an explicity UnitOfWork manager, then I am not able to get the newly created primary key (Id) from the AbpUser table.  I am using the snippet below so I can get the Id.  However, when I call                         AuthenticationManager.SignIn(new AuthenticationProperties { IsPersistent = false }, identity); I am not still not authenticated.

If I check my base.CurrentSession.UserId, I show that I have a UserId from a previous user I attempted to register and not the newly registered user.  

How can I register a user, have them authenticated with a session and also perform actions other ServiceClasses (inherited from ApplicationService) that require the AbpAuthorize attribute?

Here is my Immediate window output.
?this.CurrentSession
{Abp.Runtime.Session.AbpSession}
    [Abp.Runtime.Session.AbpSession]: {Abp.Runtime.Session.AbpSession}
    TenantId: 1
    UserId: 17

                        var identity = await _userManager.CreateIdentityAsync(user, DefaultAuthenticationTypes.ApplicationCookie);
                        if (user.TenantId.HasValue)
                        {
                            identity.AddClaim(new Claim(AbpClaimTypes.TenantId, user.TenantId.Value.ToString(CultureInfo.InvariantCulture)));
                        }

                        AuthenticationManager.SignIn(new AuthenticationProperties { IsPersistent = false }, identity);

AuthenticationManager.SignOut(), then my environment still has an AbpSession.UserId with whatever previous user logged into my system.

        [HttpPost]
        [AllowAnonymous]
        public async virtual Task<ActionResult> Register(RegisterViewModel model, string returnUrl = "")
        {

                    AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);

                    var user = new User
                    {
                        Id = 0,
                        TenantId = 1,
                        UserName = model.UsernameOrEmailAddress,
                        EmailAddress = model.UsernameOrEmailAddress,
                        IsEmailConfirmed = false,
                        Name = model.FirstName,
                        Surname = model.LastName,
                        CreationTime = DateTime.UtcNow,
                        IsActive = true
                    };

                    var createdUser = false;
                    using (var unitOfWork = _unitOfWorkManager.Begin())
                    {
                        var result = await _userManager.CreateAsync(user, model.Password);
                        createdUser = result.Succeeded;
                        unitOfWork.Complete();
                    }

                    if (createdUser)
                    {

                        //AuthenticationManager.SignOut(DefaultAuthenticationTypes.ExternalCookie);

                        var identity = await _userManager.CreateIdentityAsync(user, DefaultAuthenticationTypes.ApplicationCookie);
                        if (user.TenantId.HasValue)
                        {
                            identity.AddClaim(new Claim(AbpClaimTypes.TenantId, user.TenantId.Value.ToString(CultureInfo.InvariantCulture)));
                        }

                        AuthenticationManager.SignIn(new AuthenticationProperties { IsPersistent = false }, identity);

Thanks,

Chris

**Comment by hikalkan** [comment]
Hi,

You should not use AbpSession while registering a new user. It gets user and tenant id from cookie and will be set after login of new registered user.
I've limit time for now, if this does not help, I will try to help again.

**Comment by langman66** [comment]
Hi,

I'm not using the AbpSession object.  I was just investigating it from both my MVC controller and my application service to see how it was being populated.  It looks like it only gets updated during the initial construction from the DI framework.  

If I Register against the MVC Account Controller and check the this.CurrentSession, the UserId is null.  I then attempt to call over to one of my UserProfileApplicationService that has an AbpAuthorize attribute to update other aspects of my newly created user (payment information, default language setting, etc.) and I'm unable to because my user is not Authorized.  

If I return my call back to the browser and turn around and call to the same UserProfileApplicationService I am now authenticated and can invoke the actions without any issues.

I would like to perform all these actions during registration and either allow them all to be successful or to be rolled back if there is a failure.

Thanks for your response.

Chris

**Comment by hikalkan** [comment]
See https://github.com/aspnetboilerplate/module-zero/blob/master/src/Abp.Zero/Runtime/Session/AbpSession.cs

It actually gets UserId from Thread.CurrentPrincipal. You may try to set it?
