### ISSUE TITLE
How to get Application services in Custom Authorization Attribute in web api

### ISSUE THREAD

**Issue by Noushida** [aspnetboilerplate/module-zero#402]
How to get Application services in Custom Authorization Attribute in web api?

**Comment by ismcagdas** [comment]
Hi @Noushida, can you explain your case a little bir more ? I couldn't understand it.

Thanks.

**Comment by Noushida** [comment]
Hi
Thank You For response.
I resolved this issue just now. Actually I want to call logInManager.LoginAsync in OnAuthrization method in authorization filter attribute for a normal webapi.I got it by using IIocResolver.

**Comment by ismcagdas** [comment]
Great @Noushida
