### ISSUE TITLE
Oracle Migration Languages.IsDisabled

### ISSUE THREAD

**Issue by Worthy7** [aspnetboilerplate/module-zero#403]
/// <summary>
--
  | /// Is this language active. Inactive languages are not get by <see cref="IApplicationLanguageManager"/>.
  | /// </summary>
  | public bool IsDisabled { get; set; }

The new IsDisabled property breaks migrations on oracle.
Oracle doesn't accept new columns which are Non-Null unless the table is empty.

**Comment by hikalkan** [comment]
Isn't it work if you change migration code and make it nullable? Then update existing rows to false.

**Comment by Worthy7** [comment]
Your right, this was my solution. I was hoping that something could be done with "defaultvalue" in EF, but it only exists in EF core and apparently isn't detected by the oracle provider anyway. So it looks like nothing can be done for now. But having a default value set in Abp may prepare it for the future if/when Oracle do update their provider driver.

https://docs.microsoft.com/en-us/ef/core/modeling/relational/default-values

**Comment by hikalkan** [comment]
Default value normally become 'false' for booleans when we don't define it for a non nullable field. But I haven't tried with Oracle.

**Comment by Worthy7** [comment]
Hmm, ok. I guess it's up to oracle.
