### ISSUE TITLE
Add Login method to UserManager

### ISSUE THREAD

**Issue by hikalkan** [aspnetboilerplate/module-zero#41]

**Comment by emaish** [comment]
the Nuget published version 5.6.0 miss this line
```C#
protected AbpUserManager(AbpUserStore<TTenant, TRole, TUser> userStore, AbpRoleManager<TTenant, TRole, TUser> roleManager)
```
so i have build error now:
Abp.Authorization.Users.AbpUserManager<CP.MultiTenancy.Tenant,CP.Authorization.Role,CP.Users.User>' does not contain a constructor that takes 2 arguments

**Comment by hikalkan** [comment]
See AccountController for usage:

https://github.com/aspnetboilerplate/module-zero/blob/master/sample/ModuleZeroSampleProject.Web/Controllers/AccountController.cs

Also, added IRepository<Tenant> and MultiTenancyConfig to AbpUserManager base class. So, we should add derived class too. See sample:

https://github.com/aspnetboilerplate/module-zero/blob/master/sample/ModuleZeroSampleProject.Core/Users/UserManager.cs

**Comment by emaish** [comment]
You have an assumption that the Tenant is set in login form or subdomain or any where else, what about if we want to get the tenant name after login and set it in the whole session, as in the case when you deploy one application with one login page in one domain to serve mutliboe tenants.
The login logic now allow login without providing tenant name for only tenancy owner.

**Comment by hikalkan** [comment]
Hi,

I thought that a lot. If we do like you said, we can not create same user name in different tenants. I want to allow same user name or email be used for different tenants in same deployments. So, checking username and pass is not enough in login, we should also know the tenant.
So, this is by design.

If you can provide uniqueness of user names and emails in the database, then you can login without tenant and get tenant from user. But, you should implement it yourself. Maybe you can find user from user repository in account controller's login, then get the tenancy name and call UserManager.LoginAsync.

**Comment by emaish** [comment]
yes we can not create same user name in different tenants, and it's logical to me :) , i will implement that logic in login controller if i had to, thank you

**Comment by hikalkan** [comment]
Especially, user-name uniqueness is hard if you will have many tenants. Think that they even can not share 'admin' user. Also, same user may want to register for multiple tenants with same email. Think carefully.

**Comment by emaish** [comment]
Yes, i think you are right. Your logic is more flexible
