### ISSUE TITLE
css/style.css error

### ISSUE THREAD

**Issue by toyysky** [aspnetboilerplate/module-zero#411]
When I was in the controller layer to invoke the service method, the interceptor will first call the Valid method, then an AbpValidationException is thrown, view will jump to the Error.cshtml page, but will find the dead cycle main card UI “Please wait...  ", that is caused by the css/style.css file, you can delete this file normal, why? Thank you

**Comment by toyysky** [comment]
The version is up to date

**Comment by ismcagdas** [comment]
Hi @toyysky , which template do you use ?

**Comment by toyysky** [comment]
v2.3.0. thanks

**Comment by toyysky** [comment]
The latest edition zero template

**Comment by ismcagdas** [comment]
I mean, did you download the solution here https://aspnetboilerplate.com/Templates ?
If so, what did you selected while downloading the template ? 
* ASP.NET Core or ASP.NET MVC 5x ?
* Angular or Multi Page Application ?

**Comment by toyysky** [comment]
ASP.NET Core or ASP.NET MVC 5x ?

**Comment by toyysky** [comment]
ASP.NET MVC 5x

**Comment by ismcagdas** [comment]
Thanks, we will check this issue.

**Comment by toyysky** [comment]
thank you!

**Comment by toyysky** [comment]
When will it be released V2.4 ? thank you!

**Comment by acjh** [comment]
@toyysky `v3.0.0` of [ABP (+ module-zero)](https://github.com/aspnetboilerplate/aspnetboilerplate/releases) and [module-zero-template](https://github.com/aspnetboilerplate/module-zero-template/releases) were released 12 days ago.

> **IMPORTANT NOTICE:** This repository is moved to <a href="https://aspnetboilerplate.com/" target="_blank">ASP.NET Boilerplate</a> repository and it is deprecated now. Please refer to <a href="https://aspnetboilerplate.com/" target="_blank">ASP.NET Boilerplate</a> repository.

**Comment by toyysky** [comment]
@ismcagdas 

When I was in the controller layer to invoke the service method, the interceptor will first call the Valid method, then an AbpValidationException is thrown, view will jump to the Error.cshtml page, but will find the dead cycle main card UI “Please wait... ", that is caused by the css/style.css file, you can delete this file normal, why? Thank you

Is this settled yet? Which version is the solution, please?

**Comment by ismcagdas** [comment]
@toyysky we haven't take a look at your problem. I have moved your issue to https://github.com/aspnetboilerplate/module-zero-template/issues/101. We will check it for the next release.
