### ISSUE TITLE
Why moving module-zero to abp?

### ISSUE THREAD

**Issue by diogodamiani** [aspnetboilerplate/module-zero#412]
Hi,
Why move module-zero to abp? I'm just curious to know.

Cheers

**Comment by hikalkan** [comment]
For faster development & deployment. Nothing changes for developers.

**Comment by tom177y** [comment]
It certain helps when both are combined into a single repository.

Are you able to share why they were separated in the first place?  Recalling my initial experience with Abp. I always have to second guess where the particular method may reside. ;o)

thanks.

**Comment by hikalkan** [comment]
> why they were separated in the first place?

"Wrong decision" or "changing requirements" or whatever you want to say :)
