### ISSUE TITLE
Using DI to inject ASP.NET Identity using Castle Windsor (StartUp.cs)

### ISSUE THREAD

**Issue by KennyEng12** [aspnetboilerplate/module-zero#413]
What I wanted to do is prevent multiple login.
And I followed this article: [Prevent Multiple Login](http://tech.trailmax.info/2015/09/prevent-multiple-logins-in-asp-net-identity/)

After that I followed this article: [Changing PK data type](http://tech.trailmax.info/2014/08/cookieauthenticationprovider-and-user-session-invalidation-on-change-of-securitystamp/) to change the data type of primary key from string(default) to long. But I still can't prevent multiple login.

I found out that the reason why it's not working is because I can't get an instance of UserManager

The code above is not working. I'm getting error of

> Object reference not set to an instance of an object.

Then I realize that is because I can't inject UserManager here(StartUp.cs) like other .cs file.
For example:
```
private readonly UserManager _userManager;

public StartUp(UserManager userManager)
{
      _userManager = userManager;
}
```
And the code above is giving me this error:

> No parameterless constructor defined for this object

I've been stuck here for few weeks. Please help me ! ! !

**Comment by hikalkan** [comment]
You can not inject it into Startup class because Identity is not registered to DI in the time Startup class being created. This is a fundamental principle of AspNet Core's DI/startup system.

But you can resolve it inside Configure method like:

````C#
var userManager = app.ApplicationServices.GetService<UserManager>();
````

**Comment by KennyEng12** [comment]
Thanks for the quick response.
But I'm using MVC5AJ1, the code you provided is able to use in MVC5AJ1?

**Comment by hikalkan** [comment]
Then ``IocManager.Instance.Resolve<UserManager>()``

**Comment by KennyEng12** [comment]
Thanks that is working for me, but now there is another problem.
Which is the user can't login at all even there is not logged in user. It forced me logged out straight away.

Here are my codes:
```
app.CreatePerOwinContext(() => IocManager.Instance.Resolve<UserManager>());

app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
                LoginPath = new PathString("/Account/Login"),    // URL to the login page to redirect unauthorized requests
                Provider = new CookieAuthenticationProvider 
                {
                    OnValidateIdentity = SecurityStampValidator.OnValidateIdentity<UserManager, User, long>(
                        validateInterval: TimeSpan.FromMinutes(0),
                        regenerateIdentityCallback: (manager, user) => (manager.CreateIdentityAsync(user, DefaultAuthenticationTypes.ApplicationCookie)),
                        getUserIdCallback: (ci) => (Int64.Parse(ci.GetUserId())))
            });
```

After doing some debugs and I found out that, this is because ABP framework created the identity claims at starting of the program and it's not getting override even calling CreateIdentityAsync method.

And I did some research about it and I found that we need to remove the claim and add a new claim for it. Is there any other way of doing it like straight away update the identity claim?

**Comment by KennyEng12** [comment]
I've found out the reason that cause the claims not updating.
The reason is I update the security stamp after the log in method. That's why the claim is not updating.

This is mentioned in this article: [Prevent Multiple Login](http://tech.trailmax.info/2015/09/prevent-multiple-logins-in-asp-net-identity/)
```
[HttpPost]
[AllowAnonymous]
[ValidateAntiForgeryToken]
public async Task<ActionResult> Login(LoginViewModel model, string returnUrl)
{
    if (!ModelState.IsValid)
    {
        return View(model);
    }


    // check if username/password pair match.
    var loggedinUser = await UserManager.FindAsync(model.Email, model.Password);
    if (loggedinUser != null)
    {
        // Now user have entered correct username and password.
        // Time to change the security stamp
        await UserManager.UpdateSecurityStampAsync(loggedinUser.Id);
    }

    // do sign-in AFTER we have done the update of the security stamp, so the new stamp goes into the cookie
    var result = await SignInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, shouldLockout: false);
    switch (result)
    {
        // do the rest of method
```
But thanks by the way, I can't settle this until you provided me this:
`IocManager.Instance.Resolve<UserManager>()`
