### ISSUE TITLE
The internal table name of the module is too long to exceed the length specified by oracle

### ISSUE THREAD

**Issue by WoJoinGitHub** [aspnetboilerplate/module-zero#415]
The internal table name of the module is too long to exceed the length specified by oracle

**Comment by acjh** [comment]
Which table is this?

**Comment by hikalkan** [comment]
You can always change table names by overriding OnModelCreating of your dbcontext.

**Comment by WoJoinGitHub** [comment]
PM> update-database
Specify the '-Verbose' flag to view the SQL statements being applied to the target database.
Applying explicit migrations: [201709270512432_db].
Applying explicit migration: 201709270512432_db.
Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-00972: 标识符过长
ORA-00972: 标识符过长
 OK ！ Let Me Try .Some tables have been successfully created,But I don't know why other people is succeeded；It is because the version is too low？the version is oracle 10g  @hikalkan @acjh

**Comment by ismcagdas** [comment]
@WoJoinGitHub your problem might be similar to https://forum.aspnetboilerplate.com/viewtopic.php?f=5&t=5389&p=13486. Can you check that ?

**Comment by WoJoinGitHub** [comment]
OK thanks everyone！
