### ISSUE TITLE
Can not get localization source with project 'Abp.ZeroCore' when currentCulture is 'zh-CN'

### ISSUE THREAD

**Issue by laozhuorun** [aspnetboilerplate/module-zero#416]
I Can't get  localization source with project 'Abp.ZeroCore' when currentCulture is 'zh-CN'

the localization source result i get on 'zh-CN' culture is:

"AbpZero": {
"CanNotDeleteAdminUser": "不能删除默认管理员{0}!",
"CanNotDeleteStaticRole": "不能删除系统预定义角色: {0}",
"CanNotRenameAdminUser": "不能重命名默认管理员的用户名 {0}",
"InvalidTenancyName": "租户名无效!",
"RoleDisplayNameIsAlreadyTaken": "角色显示名称 {0}已被占用.",
"RoleNameIsAlreadyTaken": "角色名{0}已被占用.",
"TenancyNameIsAlreadyTaken": "租户名{0} 已被占用."
},

but in 'en' that is :
"AbpZero": {
"CanNotDeleteAdminUser": "Can not delete user {0} since this is the default admin user!",
"CanNotDeleteStaticRole": "Can not delete a static role: {0}",
"CanNotRenameAdminUser": "Can not rename user name of the {0} since this is the default admin user!",
"Email": "Email",
"EmailSecurityCodeBody": "Your security code is: {0}",
"EmailSecurityCodeSubject": "Security Code",
"Identity.ConcurrencyFailure": "Optimistic concurrency failure, object has been modified.",
"Identity.DefaultError": "An unknown failure has occurred.",
"Identity.DuplicateEmail": "Email '{0}' is already taken.",
"Identity.DuplicateRoleName": "Role name '{0}' is already taken.",
"Identity.DuplicateUserName": "User name '{0}' is already taken.",
"Identity.InvalidEmail": "Email '{0}' is invalid.",
"Identity.InvalidPasswordHasherCompatibilityMode": "The provided PasswordHasherCompatibilityMode is invalid.",
"Identity.InvalidPasswordHasherIterationCount": "The iteration count must be a positive integer.",
"Identity.InvalidRoleName": "Role name '{0}' is invalid.",
"Identity.InvalidToken": "Invalid token.",
"Identity.InvalidUserName": "User name '{0}' is invalid, can only contain letters or digits.",
"Identity.LoginAlreadyAssociated": "A user with this login already exists.",
"Identity.PasswordMismatch": "Incorrect password.",
"Identity.PasswordRequiresDigit": "Passwords must have at least one digit ('0'-'9').",
"Identity.PasswordRequiresLower": "Passwords must have at least one lowercase ('a'-'z').",
"Identity.PasswordRequiresNonAlphanumeric": "Passwords must have at least one non alphanumeric character.",
"Identity.PasswordRequiresUpper": "Passwords must have at least one uppercase ('A'-'Z').",
"Identity.PasswordTooShort": "Passwords must be at least {0} characters.",
"Identity.RoleNotFound": "Role {0} does not exist.",
"Identity.UserAlreadyHasPassword": "User already has a password set.",
"Identity.UserAlreadyInRole": "User already in role '{0}'.",
"Identity.UserLockedOut": "User is locked out.",
"Identity.UserLockoutNotEnabled": "Lockout is not enabled for this user.",
"Identity.UserNameNotFound": "User {0} does not exist.",
"Identity.UserNotInRole": "User is not in role '{0}'.",
"InvalidTenancyName": "Tenancy name is not valid!",
"OrganizationUnitDuplicateDisplayNameWarning": "There is already an organization unit with name {0}. Two units with same name can not be created in same level.",
"RoleDisplayNameIsAlreadyTaken": "Role display name {0} is already taken.",
"RoleNameIsAlreadyTaken": "Role name {0} is already taken.",
"Sms": "Sms",
"SmsSecurityCodeMessage": "Your security code is: {0}",
"TenancyNameIsAlreadyTaken": "Tenancy name {0} is already taken."
},

the project 'Abp.ZeroCore' localization source is lose in 'zh-CN'

**Comment by acjh** [comment]
@laozhuorun Do you want to help with the 12 missing translations?

```xml
<text name="Identity.ConcurrencyFailure">Optimistic concurrency failure, object has been modified.</text>
<!--<text name="Identity.DefaultError" value="发生了一个未知的异常错误." />-->
<!--<text name="Identity.DuplicateEmail" value="邮箱地址 '{0}' 已被占用." />-->
<text name="Identity.DuplicateRoleName">Role name '{0}' is already taken.</text>
<!--<text name="Identity.DuplicateUserName" value="名字{0}已被占用." />-->
<!--<text name="Identity.InvalidEmail" value="邮箱地址 '{0}' 不符合要求." />-->
<text name="Identity.InvalidPasswordHasherCompatibilityMode">The provided PasswordHasherCompatibilityMode is invalid.</text>
<text name="Identity.InvalidPasswordHasherIterationCount">The iteration count must be a positive integer.</text>
<text name="Identity.InvalidRoleName">Role name '{0}' is invalid.</text>
<!--<text name="Identity.InvalidToken" value="无效的token." />-->
<!--<text name="Identity.InvalidUserName" value="用户名{0}不符合要求, 只能包含字母和数字." />-->
<text name="Identity.LoginAlreadyAssociated">A user with this login already exists.</text>
<!--<text name="Identity.PasswordMismatch" value="密码错误." />-->
<!--<text name="Identity.PasswordRequiresDigit" value="密码至少要包含一位数字 ('0'-'9')." />-->
<!--<text name="Identity.PasswordRequiresLower" value="密码至少要包含一位小写字母 ('a'-'z')." />-->
<!--<text name="Identity.PasswordRequiresNonAlphanumeric" value="密码必须包含一位非字母特殊符号或数字." />-->
<!--<text name="Identity.PasswordRequiresUpper" value="密码至少要包含一位大写字母 ('A'-'Z')." />-->
<!--<text name="Identity.PasswordTooShort" value="密码至少要{0}位." />-->
<!--<text name="Identity.RoleNotFound" value="角色{0}不存在." />-->
<!--<text name="Identity.UserAlreadyHasPassword" value="用户已设置密码." />-->
<!--<text name="Identity.UserAlreadyInRole" value="用户已拥有此角色." />-->
<text name="Identity.UserLockedOut">User is locked out.</text>
<!--<text name="Identity.UserLockoutNotEnabled" value="对此用户，不能启用锁定." />-->
<!--<text name="Identity.UserNameNotFound" value="用户 {0} 不存在." />-->
<!--<text name="Identity.UserNotInRole" value="用户不包含此角色." />-->
<text name="Email">Email</text>
<text name="EmailSecurityCodeSubject">Security Code</text>
<text name="EmailSecurityCodeBody">Your security code is: {0}</text>
<text name="Sms">Sms</text>
<text name="SmsSecurityCodeMessage">Your security code is: {0}</text>
```
