### ISSUE TITLE
Why role doesn't implement ISoftDelete, nor IPassivable ?

### ISSUE THREAD

**Issue by emaish** [aspnetboilerplate/module-zero#44]
I'm sure you have a reason(s), but i want you to share the idea with us :)

**Comment by hikalkan** [comment]
I assume that a role is an immutable-like entity. making a role active/passive or soft-delete is not needed that much. That makes role management and authorization more compicated. Just delete a role or create new one.

**Comment by emaish** [comment]
thank you

**Comment by hikalkan** [comment]
@emaish I thought that soft-delete can be useful for roles.
active/passive is not so much needed since we can easily prohibit all permissions from a role. Thus, it will be like passive in the system.

**Comment by emaish** [comment]
:+1:

**Comment by emaish** [comment]
you implemeted soft delete for roles it, right ?

**Comment by hikalkan** [comment]
Yes, I did.
