### ISSUE TITLE
How do we create and use an entity framework module?

### ISSUE THREAD

**Issue by dinhienhy** [aspnetboilerplate/module-zero#45]
Hi hikalkan,

That's greet project!
I have created an entity framework module. But I don't know how to use it in a class DbContext which already extend AbpZeroDbContext. 
Please give me some advice,

Thanks,
Hien Phan

**Comment by hikalkan** [comment]
Folow http://forum.aspnetboilerplate.com/viewtopic.php?f=2&t=16
