### ISSUE TITLE
After updating Abp.Zero to 5.10 MultiTenancyConfig isn't found

### ISSUE THREAD

**Issue by bongiozzo** [aspnetboilerplate/module-zero#47]
The type or namespace name 'MultiTenancyConfig' could not be found (are you missing a using directive or an assembly reference?)

using Abp.Authorization;
using Abp.Authorization.Users;
using Abp.Domain.Repositories;
using Abp.Runtime.Session;
using Abp.Zero.Configuration;

   public class UserManager : AbpUserManager<Tenant, Role, User>
    {
        public UserManager(
            UserStore store,
            RoleManager roleManager,
            IRepository<Tenant> tenantRepository,
            MultiTenancyConfig multiTenancyConfig,
            IPermissionManager permissionManager)
            : base(
                store,
                roleManager,
                tenantRepository,
                multiTenancyConfig,
                permissionManager)
        {
        }
    }

**Comment by emaish** [comment]
From release  0.5.6.0. And on MultiTenancyConfig moved from module-zero configuration directly to IAbpStartupConfiguration.

**Comment by hikalkan** [comment]
Thanks @emaish 

So, use Configuration.MultiTenancy.IsEnabled in PreInitialize of your module.

**Comment by hmmdeif** [comment]
I think the issue here is that the sample project passes the concrete type `MultiTenancyConfig` instead of `IMultiTenancyConfig`. That will fix the OP's issue (as it looks like he copied the code directly from the sample proj as part of the update process).

**Comment by hikalkan** [comment]
There was no IMultiTenancyConfig before and the sample project a little old (project rapidly changes nowadays :))

**Comment by codemonkey21** [comment]
I'm having the same issue. I've tried to add that Configuration.MultiTenancy.IsEnabled but it still is not found. It is my single roadblock for days now. If the sample application was updated to include this, it would be helpful.

**Comment by hikalkan** [comment]
I updated the sample project.
