### ISSUE TITLE
Write automatic audit logs

### ISSUE THREAD

**Issue by hikalkan** [aspnetboilerplate/module-zero#48]
I'll create a table named 'AbpAuditLogs' and will insert an item for every application service method call.

* Will write application service name, method name, execution time, execution duration, parameters as json string, client's browser, client's computer name, client's IP, Exception message (if there is) and User id.
* Will define an attribute to enable/disable this feature for single method or single class.
* Will define a configuration to enable/disable for entire application.

Note that, this is different than detailed entity-change logs property-by-property (It's also in my mind).

**Comment by langman66** [comment]
Great idea.
