### ISSUE TITLE
AbpUserStore.AddToRoleAsync(TUser user, string roleName)

### ISSUE THREAD

**Issue by emaish** [aspnetboilerplate/module-zero#49]
There is a case when Tenancy owner want to create a tenant with admin role for that tenant , and then admin user and add this user to the admin role for that tenant.
i had a look on abp and asp.net identity classes and understood that:
1- asp.net identity UserManager isn't aware of tenant Id when adding role and assumes that role name is unique
2- We have a method in the AbpUserStore which is aware of TenantId we can use it in the Custom UserManager that inherit AbpUserManager, but this method will not work with my case because it determine tenant Id from current session.
3- the solution is to have overloading method AbpUserStore.AddToRoleAsync(TUser user, int roleId)  that take role Id instead of role name 
```C#
public async Task AddToRoleAsync(TUser user, int roleId)
        {
            await _userRoleRepository.InsertAsync(
                new UserRole
                {
                    UserId = user.Id,
                    RoleId = roleId
                });
        }
```
Are my assumptions correct ?

**Comment by hikalkan** [comment]
Hi,

You found a good point. In my application, I directly used UserRepository instead of UserManager to solve this problem. It's not just for AddToRole but also in many methods of UserManager since Identity Framework does not know Tenancy.

Maybe I will override most methods of UserManager. My current code is something like that:

         public async Task<Tenant> CreateTenantWithStaticRolesAndAdminUser(string tenancyName, string name, string adminEmailAddress, string adminPassword, bool isActive)
        {
            //Create tenant
            var tenant = await _tenantRepository.InsertAsync(new Tenant(tenancyName, name) { IsActive = isActive });

            _unitOfWorkManager.Current.SaveChanges(); //Saving to get Id of the tenant

            //create static roles
            var userRole = await CreateStaticRoleAsync(tenant, StaticRoles.Tenants.User);
            var adminRole = await CreateStaticRoleAsync(tenant, StaticRoles.Tenants.Admin);

            _unitOfWorkManager.Current.SaveChanges(); //Saving to get Ids of the roles

            //create default admin user
            var adminUser = User.CreateTenantAdmin(tenant.Id, adminEmailAddress, adminPassword);
            await _userRepository.InsertAsync(adminUser);

            _unitOfWorkManager.Current.SaveChanges(); //Saving to get Id of the adminUser

            //grant all permissions to admin role
            var permissions = _permissionManager.GetAllPermissions().Where(p => p.MultiTenancySides.HasFlag(MultiTenancySides.Tenant));
            await _roleManager.SetGrantedPermissionsAsync(adminRole, permissions);

            //Assign admin role to admin user
            await _userManager.AddToRoleAsync(adminUser.Id, adminRole.Name);

            _unitOfWorkManager.Current.SaveChanges(); //Saves role assignment

            return tenant;
        }

        private async Task<Role> CreateStaticRoleAsync(Tenant tenant, string roleName)
        {
            var role = new Role(tenant.Id, roleName, roleName) { IsStatic = true };
            var existingRole = await _roleRepository.FirstOrDefaultAsync(r => r.TenantId == tenant.Id && r.Name == roleName);
            if (existingRole != null)
            {
                throw new AbpException("Role " + roleName + " already exists in the tenant " + tenant.TenancyName);
            }

            return _roleRepository.Insert(role);
        }

**Comment by emaish** [comment]
Yes we need overriding or overloading, i will go with your suggestion temporarily, thank you

**Comment by hikalkan** [comment]
We can close it for now, Thanks.

**Comment by easyest** [comment]
For me `await _userManager.AddToRoleAsync(adminUser.Id, adminRole.Name);` throw exception 'UserId not found'. I think this is because of filters.
