### ISSUE TITLE
Token based Authentication

### ISSUE THREAD

**Issue by ioanes** [aspnetboilerplate/module-zero#51]
Hi Halil, 

First of all thanks for sharing all of this. I am just curious if you plan to add Web API authentication support. In my case it will be better not to reload whole angular app.

**Comment by dawsidious** [comment]
+1, It could be more user-friendly to not reload the whole app, in some project :)

**Comment by xumx** [comment]
Add Registration and Forget password to AccountController in .WebApi project

**Comment by Jerome2606** [comment]
+1

**Comment by hikalkan** [comment]
Hi,

Now startup template supports token based authentication (but not documented yet).

**Comment by hikalkan** [comment]
I'm closing this since it's also documented.
