### ISSUE TITLE
UserManager.LoginAsync should check email confirmation

### ISSUE THREAD

**Issue by hikalkan** [aspnetboilerplate/module-zero#52]
It will be configurable.

**Comment by hikalkan** [comment]
Set
    Configuration.Modules.AbpZero().UserManagement.IsEmailConfirmationRequiredForLogin = true
in module PreInitialize.

**Comment by emaish** [comment]
i wanted that :) thank you

**Comment by ademgashi** [comment]
On a ABP project with module zero references does this work by default
Configuration.Modules.Zero().UserManagement.IsEmailConfirmationRequiredForLogin = true;
Also is the same example updated on ModuleZeroSample

**Comment by hikalkan** [comment]
Hi,

This is changed a bit. Now, it uses Setting Management to get the configuration.

See https://github.com/aspnetboilerplate/module-zero/blob/master/src/Abp.Zero/Zero/Configuration/AbpZeroSettingProvider.cs

Default value is false.

**Comment by ademgashi** [comment]
Hi, Halil I hope you are doing well with everything.
First thank you very much for the quick response.
So if I want to turn IsEmailConfirmationRequiredForLogin  to true, I can just override the value on my project settings provider right?

**Comment by hikalkan** [comment]
Hi,

You can create a setting page for that as normally.
Then you can use SettingManager.ChangeSettingForApplication or ChangeSettingForTenant methods to change the setting for application or for a tenant.
If you want to change default value from false to true, yes you can override this setting as you done before.

**Comment by ademgashi** [comment]
Thanks Halil for the explanation.
And kudos for the ABP and modulezero, I appreciate very much your hard work.
Best Regards

**Comment by hikalkan** [comment]
Thanks :)

**Comment by Worthy7** [comment]
@hikalkan How do we do the same thing on a later version?

**Comment by ismcagdas** [comment]
@Worthy7 do you mean ASP.NET Core ?

**Comment by Worthy7** [comment]
Yea. I worked it out:
Core.Configuration.AppSettingProvider.cs

`new SettingDefinition(AbpZeroSettingNames.UserManagement.IsEmailConfirmationRequiredForLogin, "true", scopes: SettingScopes.Application | SettingScopes.Tenant | SettingScopes.User, isVisibleToClients: true)`
