### ISSUE TITLE
Write logs to AbpAuditLogs on every Controller action of Web project

### ISSUE THREAD

**Issue by Otgontugs** [aspnetboilerplate/module-zero#54]
It's useful for people who are using Multipage web application

**Comment by hikalkan** [comment]
Hi,

It's possible for now. In your module's PreInitialize, use;

<pre lang="cs">Configuration.Auditing.Selectors.Add(
	new NamedTypeSelector(
		"MyControllerSelector",
		type => typeof (Controller).IsAssignableFrom(type)
		)
	);</pre>

**Comment by Otgontugs** [comment]
Thank you man!
