### ISSUE TITLE
User.PasswordResetCode's length should be bigger.

### ISSUE THREAD

**Issue by hikalkan** [aspnetboilerplate/module-zero#58]
As described in https://github.com/aspnetboilerplate/module-zero/issues/50

**Comment by lerich** [comment]
it's not enough. It should be min 328 - length of   Microsoft.AspNet.Identity.UserManagerExtensions GenerateEmailConfirmationToken

**Comment by hikalkan** [comment]
Resolved in https://github.com/aspnetboilerplate/module-zero/commit/76627b4f9899d1a480ab3ec8c35958e83d1733d5

**Comment by lerich** [comment]
Hi,
You changed only MaxPasswordResetCodeLength 
But the MaxEmailConfirmationCodeLength = 128
EmailConfirmationCode should be min 328 too.
Thanks
