### ISSUE TITLE
Method 'SaveAsync' in type 'Abp.Auditing.AuditingStore'  does not have an implementation.

### ISSUE THREAD

**Issue by emaish** [aspnetboilerplate/module-zero#59]
After upgradint to latest packages
Method 'SaveAsync' in type 'Abp.Auditing.AuditingStore' from assembly 'Abp.Zero, Version=0.5.12.2, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by hikalkan** [comment]
Latest module-zero implements it. I'll publish nuget package in a few hours.

**Comment by emaish** [comment]
Thank you dear

**Comment by hikalkan** [comment]
Published nuget package.
