### ISSUE TITLE
Contructors for PermissionChecker, AbpUserManager and ApbRoleManager

### ISSUE THREAD

**Issue by marius310** [aspnetboilerplate/module-zero#60]
When I build after the latest updates, I get the following errors:

'TECParishes.Authorization.Role' must be a non-abstract type with a public parameterless constructor in order to use it as parameter 'TRole' in the generic type or method 'Abp.Authorization.PermissionChecker<TTenant,TRole,TUser>'	

'TECParishes.Authorization.Role' must be a non-abstract type with a public parameterless constructor in order to use it as parameter 'TRole' in the generic type or method 'Abp.Authorization.Roles.AbpRoleManager<TTenant,TRole,TUser>'	

'TECParishes.Authorization.Role' must be a non-abstract type with a public parameterless constructor in order to use it as parameter 'TRole' in the generic type or method 'Abp.Authorization.Users.AbpUserManager<TTenant,TRole,TUser>'	

Although I am not expert in this, it seems like this might have something to do with  the "new()" in the contructors for each of these which look like this: "where TRole : AbpRole<TTenant, TUser>, new()"

If it is something I need to change on my end, please let me know.

**Comment by emaish** [comment]
In Role class just change the protected constructor to public

**Comment by marius310** [comment]
That fixed it. Thanks for the help.
