### ISSUE TITLE
System.Data.Entity.Validation.DbEntityValidationException handling on _userManager.Create method

### ISSUE THREAD

**Issue by Otgontugs** [aspnetboilerplate/module-zero#61]
Morning!

How can i handle DbEntityValidationException occurred in AbpUserManager.Create method. I've already overrided SaveChanges method of my inherited DbContext to catch "... catch (DbEntityValidationException ex) ...". But the debugger never hit it. I've seen in sample application  _userRepository.Insert method was used to create a new user. Do i have to use Repository to register a new user?

Many Thanks!

Server Error in '/' Application.

Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Data.Entity.Validation.DbEntityValidationException: Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.

Source Error: 

Line 69:         public ActionResult CreateUser(CreateUserViewModel model)
Line 70:         {
Line 71:             IdentityResult result = _userManager.Create(new CustEntity() { TenantId = 1, Name = model.Name, UserName = model.UserName, Surname = model.Surname, EmailAddress = model.EmailAddress });
Line 72:             if (result.Succeeded)
Line 73:             {

**Comment by Otgontugs** [comment]
CustEntity is inherited from AbpUser and _userManager is instance of class inherited from AbpUserManager and also DbContext is inherited from AbpDbContext

**Comment by hikalkan** [comment]
Probably there is a problem with the user entity. To see exception details, you can create an exception handler as defined here: https://github.com/aspnetboilerplate/aspnetboilerplate/issues/62
Then create a breakpoint inside handler and see exception's details and EntityValidationErrors property.

**Comment by easyest** [comment]
Just put Your method `AbpUserManager.Create` into try/catch block like that:
```c#
try
{
    IdentityResult result = _userManager.Create(new CustEntity() { TenantId = 1, Name = model.Name, UserName = model.UserName, Surname = model.Surname, EmailAddress = model.EmailAddress });
}
catch (Exception ex)
{
                
    throw;
}
```
You will get the exception **WITH** validation errors in the catch block. I don't know why, but then Visual Studio just throws this exception, it does not contains errors, but You can see them if inspecting the variable `ex` in the catch block.
You can also do it like this:
```c#
catch (DbEntityValidationException ex)
{
    foreach (var entityValidationErrors in ex.EntityValidationErrors)
    {
        foreach (var dbValidationError in entityValidationErrors .ValidationErrors)
        {
            Trace.TraceInformation("PropertyName: {0} ErrorMessage: {1}", dbValidationError.PropertyName, dbValidationError.ErrorMessage);
        }
    }
}
```

**Comment by Otgontugs** [comment]
Thank you guys
