### ISSUE TITLE
Tenant still not loaded in User entity (update on #36)

### ISSUE THREAD

**Issue by easyest** [aspnetboilerplate/module-zero#62]
I updated `ModuleZeroSampleApp` and checked again for `Tenant` property of the `User` - it is still null.
Please run the following test to see the problem:
```c#
    public class UserRepository_Tests : SampleProjectTestBase
    {
        [Fact]
        public void Should_Get_User_With_Tenant()
        {
            var user = UsingDbContext(context => context.Users.Find((Int64)2));
            var tenant = user.Tenant;
            tenant.ShouldNotBe(null);
        }
    }
```

The same result can be obtained using this test for `ModuleZero` itself:
```c#
        [Fact]
        public void Should_Insert_And_Retrieve_User_With_Tenant()
        {
            var userRepository = LocalIocManager.Resolve<IRepository<User, long>>();
            var tenantRepository = LocalIocManager.Resolve<IRepository<Tenant, int>>();

            var tenant = tenantRepository.Insert(new Tenant("Testing", "Testing"));
            userRepository.Insert(new User
            {
                TenantId = tenant.Id,
                UserName = "tenancyTest",
                Name = "Tenancy",
                Surname = "Test",
                EmailAddress = "testtenancy@domain.tld",
                IsEmailConfirmed = true,
                Password = "AM4OLBpptxBYmM79lGOX9egzZk3vIQU3d/gFCJzaBjAPXzYIK3tQ2N7X4fcrHtElTw==" //123qwe
            });

            userRepository.FirstOrDefault(u => u.EmailAddress == "testtenancy@domain.tld").Tenant.ShouldNotBe(null);
        }
```

**Comment by hikalkan** [comment]
Hi,

This is a normal situation and not related to ABP if you think carefully. If you want to include Tenant, you must use Include() extension method of EntityFramework to pre-fetch Tenant property.

But, beside that, I made Tenant property virtual. Thus, it will be able to lazy loaded when you get Tenant property of the user in a unit of work (in app service for instance).

**Comment by hikalkan** [comment]
For first test, working code could be:

    var user = UsingDbContext(context => context.Users.Include(u => u.Tenant).Single((Int64)2));

**Comment by easyest** [comment]
OMG. I lack words to describe my inattention - I simply missed a keyword while taking as granted that all properties are virtual...
