### ISSUE TITLE
modifying or overloading UserManager.LoginAsync() to accept collection of claims

### ISSUE THREAD

**Issue by emaish** [aspnetboilerplate/module-zero#63]
i want to add custom claims while logging in,  for example EmployeeId to use it in the system
I need to create session class that will get properties from claims as you do with AbpSession.TenantId
Thank you :)

**Comment by hikalkan** [comment]
How todo:
* Override CreateIdentityAsync to add new claims.
* Derive a class from AbpSession and register it for IAbpSession on PreInitialize.

**Comment by emaish** [comment]
i registered it like that
```C#
IocManager.IocContainer.Register(Component.For<IAbpSession>().ImplementedBy<Al7Session>());
```
and resolve it like that
```C#
Session = (Al7Session)IocManager.Instance.IocContainer.Resolve<IAbpSession>();
```
and it's working, is this the way to do it ?

**Comment by hikalkan** [comment]
Hi,

It's not good to resolve a dependency like that. You can not constructor-inject it. Do it like that:

    IocManager.IocContainer.Register(Component.For<IAbpSession,Al7Session>().ImplementedBy<Al7Session>());

Then you can inject it anywhere using Al7Session and also directly resolve it without cast if you want like that:

    Al7Session session = IocManager.Instance.Resolve<Al7Session>();

**Comment by emaish** [comment]
Thank you dear

**Comment by tonyqus** [comment]
It looks easier to create an extension method than overriding CreateIdentityAsync. In some cases, the argument passed in is not included in User entity at all. Then I created the following extension for my case (serviceLine)

    public static class UserManagerExtensions
    {
        public static void AddServiceLineClaim(UserManager.AbpLoginResult result, string serviceLine)
        {
            if (!string.IsNullOrEmpty(serviceLine))
            {
                result.Identity.AddClaim(new Claim(BVClaimTypes.ServiceLine, serviceLine));
            }
        }
    }

Then I call it after GetLoginResultAsync is called in AccountController.Login[HttpPost]

            var loginResult = await GetLoginResultAsync(
                loginModel.UsernameOrEmailAddress,
                loginModel.Password,
                loginModel.TenancyName
                );
            AbpOne.Users.UserManagerExtensions.AddServiceLineClaim(loginResult, loginModel.ServiceLine);
            await SignInAsync(loginResult.User, loginResult.Identity, loginModel.RememberMe);

btw, I also changed LoginViewModel by adding the new property called ServiceLine.

Hope this is helpful for others.

**Comment by AHassanabadi** [comment]
[Please take a look at this question](https://stackoverflow.com/questions/48366982/get-session-in-asp-boilerplate-service-layer)

1- How can that custom session can be used in Application Service layer ?

2- Is there a way to use custom authenticate ?

**Comment by acjh** [comment]
1. If you mean how the custom *claims* can be used, inject `IPrincipalAccessor` and use it like [this](https://github.com/aspnetboilerplate/aspnetboilerplate/blob/a4882aec97b9167e1ac7793dad47f7322ade353e/src/Abp/Runtime/Session/ClaimsAbpSession.cs#L26):

   ```c#
   var userIdClaim = PrincipalAccessor.Principal?.Claims.FirstOrDefault(c => c.Type == AbpClaimTypes.UserId);
   ```

2. See the documentation on [External Authentication](https://aspnetboilerplate.com/Pages/Documents/Zero/User-Management#external-authentication).

**Comment by AHassanabadi** [comment]
I mean, suppose I have a custom session like :
```
public class MarcoSession : IAbpSession
    {
        public Token MainSession { get; set; }
        ....
    } 
```
and register it like
` IocManager.IocContainer.Register(Component.For<IAbpSession, MarcoSession>().ImplementedBy<MarcoSession>());
`
Is it possible to initiate it in Application Layer like
```
public class UserAppService : ApplicationServiceBase, IUserAppService
{ 
    public Authenticate_Box Authenticate(Authenticate_Box_In box_In)
    {
        //Here that session can be initiated
    }
}
```
Or Should I do something like 
```
[HttpPost]
public JsonResult Login(string username, string password)
{
    //Custom login by service
    var auth_c = ac.LoginAndAuthorize(argLogin);
    var loginResult = auth_c.LoginResult;
    if (loginResult != null)
    {
        switch (loginResult.Result)
        {
            case Result_C.AccountLocked:
                break;
            case Result_C.Succees:
                // 1- Here created AbpSession  
                // 2- In second step get it for sample
                // 3- or Token token = HttpContext.Session["Token"] as Token;
                break;
            default:
                break;
        }
    }
    return Json(true);
}
```

**Comment by hikalkan** [comment]
Have you seen that: https://gist.github.com/hikalkan/67469e05475c2d18cb88

**Comment by AHassanabadi** [comment]
Yes I have seen that but I think that is complicated,
I have an ASP.Net web form with some generic handler and a login page with ASP.Net submit button by clicking that Btn I am creating a custom session...

in the other side I am using aspnetboilerplate App service just to proxy all abp app service in JavaScript (I don'nt want make ajax but using apbservice.method() directly)

So I want to make a relation between my custom session and abp session,
1- I can't access created session in ASP.Net page from an ApplicationService.
2- I don't want everyone can use my abp application services directly unless ASP.Net forms authenticate occurred.
