### ISSUE TITLE
Filters in user and role management

### ISSUE THREAD

**Issue by easyest** [aspnetboilerplate/module-zero#67]
I would suggest to disable `MayHaveTenant` filter for methods of UserManager and UserStore where exact user id or the user object is used as parameter. This would let to the user to impersonate another tenancy and would let tenancy host user manage tenant's data if needed.
I have already implemented this impersonation in my system and there was only one problem - permission checking as several methods of `UserManager` and `UserStore` do not find user if `AbpSession.TenantId` is not the real `TenantId`, but impersonated `TenantId`. Methods I needed to override are `UserStore.FindByIdAsync`, `UserManager.GetUserByIdAsync` and `UserManager.IsGrantedAsync`. The only change for those methods was disabling the filter.

If anyone would be interesed - impersonation is implemented by registering additional claim `OriginalTenantId`. When user wants to impersonate another tenancy, the claim `AbpClaimTypes.TenantId` is removed and added with the new tenant id and the cookie is recreated. This way a super user that has corresponding permission can switch between multiple tenancies and manage their data. When the user wants to switch back, original claim value is restored from `OriginalTenantId`

**Comment by hikalkan** [comment]
Hi,

Did you try to SetParameterValue of UOW to change tenantId? This way, UserManager works with given tenantId.

Impersonation like you implemented has a side effect that in some cases you may not perform operations for given tenant since your user is not a user of the tenant. But your way is good for inspiration. We may build a stronger way of doing it.

**Comment by easyest** [comment]
Thank You! It should be much better to set original `TenantId` for filters for those methods.

I did not yet find any operation that would use user's `TenantId` but not `AbpSession.TenantId`. But the project ATM consist only of basic CRUDs.

**Comment by hikalkan** [comment]
Shall I close this issue?

**Comment by easyest** [comment]
I think so, as many changes have already been done, and Abp has it's own solution to this issue. Moreover there are possibilities to disable default filters is needed, so it seems the issue was resolved more than fully.

**Comment by hikalkan** [comment]
Thanks :)
