### ISSUE TITLE
Missing redirect (for not logged in users) after Update

### ISSUE THREAD

**Issue by lemestrez** [aspnetboilerplate/module-zero#68]
Hi,

i make an update to the latest version of module zero (0.6.0.0)
After the update, the redirect for not logged in users do not work any more.
I see only the main view (in my case Home/Index) with an message box "No user logged in!"
On the controller is the attribute "AbpAuthorizeAttribute".
I don't see the changes on the project.

Greetings

**Comment by hikalkan** [comment]
Thanks for the reporting. I'll check it.

**Comment by lemestrez** [comment]
Hi,

thank you. That was it!.
