### ISSUE TITLE
Can't create component 'XXXX.Web.Controllers.AccountController' as it has dependencies to be satisfied

### ISSUE THREAD

**Issue by exile-Charith** [aspnetboilerplate/module-zero#69]
XXXX.Web.Controllers.AccountController' is waiting for the following dependencies:
- Service 'XXXX.Users.UserManager' which was not registered.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: Castle.MicroKernel.Handlers.HandlerException: Can't create component 'XXXX.Web.Controllers.AccountController' as it has dependencies to be satisfied.

'XXXX.Web.Controllers.AccountController' is waiting for the following dependencies:
- Service 'XXXXX.Users.UserManager' which was not registered.

**Comment by hikalkan** [comment]
Have you solved your problem. Shall I close the issue?
