### ISSUE TITLE
How to install with aspnetboilerplate base?

### ISSUE THREAD

**Issue by biapar** [aspnetboilerplate/module-zero#71]
How to install with aspnetboilerplate base?

**Comment by hikalkan** [comment]
I started documentation but not finished yet: https://github.com/aspnetboilerplate/aspnetboilerplate/blob/master/doc/WebSiteContents/zero/installation.html

You can see sample project for now: https://github.com/aspnetboilerplate/module-zero/tree/master/sample

**Comment by hikalkan** [comment]
Document: http://www.aspnetboilerplate.com/Pages/Documents/Zero/Installation
