### ISSUE TITLE
Does modulezero implement IUserTokenProvider?

### ISSUE THREAD

**Issue by ademgashi** [aspnetboilerplate/module-zero#76]
On an ABP project that references module zero
I tried  to generate code for email activation through
string code = await _userManager.GenerateEmailConfirmationTokenAsync(user.Id);
I got No IUserTokenProvider is registered.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 
Exception Details: System.NotSupportedException: No IUserTokenProvider is registered.

So how can we implement this interface and where is the right place to do it, I am thinking without changing the Abp.zero code base?!

**Comment by hikalkan** [comment]
Hi,

It's not implemented. But you can implement without changing module-zero source. UserStore and UserManager is in your code, you can implement additional interfaces.

**Comment by ademgashi** [comment]
Thank you I am closing the question now.
