### ISSUE TITLE
Error Database migration with MySQL connector

### ISSUE THREAD

**Issue by Jerome2606** [aspnetboilerplate/module-zero#77]
Hi,

Before all many thanks for your work !!

My problem is that I got an error when I Update-Database with a MySQL connector, I get a :
MySql.Data.MySqlClient.MySqlException (0x80004005): Specified key was too long; max key length is 767 bytes

It seems that the foreign key generated with AbpRoles table are too long for a DB MySQL.

Can I make something in migrations to workaround this error ?

Thanks

**Comment by Jerome2606** [comment]
This problem is not link to module-zero.
It's a problem between EF and MySQL.
If you need to run MySQL with EF code first you need to add a class MySqlHistoryContext.cs:

    public class MySqlHistoryContext : HistoryContext
    {
        public MySqlHistoryContext(
          DbConnection existingConnection,
          string defaultSchema)
            : base(existingConnection, defaultSchema)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<HistoryRow>().Property(h => h.MigrationId).HasMaxLength(100).IsRequired();
            modelBuilder.Entity<HistoryRow>().Property(h => h.ContextKey).HasMaxLength(200).IsRequired();
        }
    }

And then add in the Configuration.cs file in Migration:

    using System.Data.Entity;
    ...
    internal sealed class MySqlConfiguration : DbConfiguration
    {
        public MySqlConfiguration()
        {
            SetHistoryContext("MySql.Data.MySqlClient", (conn, schema) => new MySqlHistoryContext(conn, schema));
        }
    }

**Comment by hikalkan** [comment]
Thanks for informing us.

**Comment by guillaumejay** [comment]
And since Configuration is now using DbMigrationConfiguration, you need to use SetHistoryContextFactory

**Comment by Jesn** [comment]
@Jerome2606 
when i  execute command  add-migration  mysqltest , 
the error : Unresolved member “MySql.Data.MySqlClient.MySqlException,MySql.Data, Version=6.9.8.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d”。
what  should i do?

**Comment by guillaumejay** [comment]
Add the MySQL nuget package

**Comment by Jesn** [comment]
@guillaumejay    i have add  Mysql.Data.Entity to  *.EntityFramework and *.web project

**Comment by Jerome2606** [comment]
Be sure to update you connector/.NET

check this post: http://stackoverflow.com/questions/31494583/asp-net-mvc-type-is-not-resolved-for-member-mysql-data-mysqlclient-mysqlexceptio

**Comment by Jesn** [comment]
@Jerome2606  thank you very mush!  According to your method has been solved！
But I fund a new problem, in the connectionStrings,  when server  use IP address is ok,user Domain is error .
error: The provider did not return a ProviderManifestToken string.
