### ISSUE TITLE
how use filter in IRepository Query ,on AppService ?

### ISSUE THREAD

**Issue by mona6767** [aspnetboilerplate/module-zero#79]
hi

best regard !

i see your tempalate on "http://demo.aspnetzero.com/Application#/auditLogs" 

very nice !!

but , How i use Filter for searching , on MyAppService ?
for example :  advanced filters in auditLogs !!

can you help me ??

thank you .

**Comment by hikalkan** [comment]
Hi,

Thanks. Just LINQ :) I can share the LINQ statement you:

            var query = from auditLog in _auditLogRepository.GetAll()
                join user in _userRepository.GetAll() on auditLog.UserId equals user.Id into userJoin
                from joinedUser in userJoin.DefaultIfEmpty()
                where auditLog.ExecutionTime >= input.StartDate && auditLog.ExecutionTime < input.EndDate
                select new AuditLogAndUser {AuditLog = auditLog, User = joinedUser};

            query = query
                .WhereIf(!input.UserName.IsNullOrWhiteSpace(), item => item.User.UserName.Contains(input.UserName))
                .WhereIf(!input.ServiceName.IsNullOrWhiteSpace(), item => item.AuditLog.ServiceName.Contains(input.ServiceName))
                .WhereIf(!input.MethodName.IsNullOrWhiteSpace(), item => item.AuditLog.MethodName.Contains(input.MethodName))
                .WhereIf(!input.BrowserInfo.IsNullOrWhiteSpace(), item => item.AuditLog.BrowserInfo.Contains(input.BrowserInfo))
                .WhereIf(input.MinExecutionDuration.HasValue && input.MinExecutionDuration > 0, item => item.AuditLog.ExecutionDuration >= input.MinExecutionDuration.Value)
                .WhereIf(input.MaxExecutionDuration.HasValue && input.MinExecutionDuration < int.MaxValue, item => item.AuditLog.ExecutionDuration <= input.MaxExecutionDuration.Value)
                .WhereIf(input.HasException == true, item => item.AuditLog.Exception != null && item.AuditLog.Exception != "")
                .WhereIf(input.HasException == false, item => item.AuditLog.Exception == null || item.AuditLog.Exception == "");

It' similar to that. But surely I can not share the full source code since it's a commerical product.

**Comment by mona6767** [comment]
Thank you very much

This will help a lot to me,

but . Is it possible share "input" class on this method ?  
I also learn its structure !!!

very very Thank you .

**Comment by hikalkan** [comment]
I think no need to input class since you can easily see what it contains: UserName, ServiceName, MethodName... and so on.. all those are using on LINQ explicitly.

**Comment by mona6767** [comment]
Thank you very much.

your are pro man !.
