### ISSUE TITLE
Create organization unit

### ISSUE THREAD

**Issue by hikalkan** [aspnetboilerplate/module-zero#81]
* An organization unit (OU) can be used to group entities (and users) of a Tenant (or Host).
* It should be hierarchical. So, an OU can have child OUs.
* An OU can have a OU code like '0003.0042.0006' that can be used to write LIKE queries to get entities of a OU and children.
* A User can be a member of zero or more OU. (We may introduce a configuration to allow more than one UO membership)
* There should be an OuManager which performs OU domain tasks.

**Comment by wocar** [comment]
+1

**Comment by vitorlacerda** [comment]
+1

Sent from my HTC Butterfly

----- Reply message -----

**Comment by wocar** [comment]
>> A User can be a member of one or more OUs. We should think if he can not
be belogn to any OU?

A user must belong to the root OU

**Comment by hikalkan** [comment]
A user is may be assigned to root OU if not assigned to any OU. This is a solution and maybe good for most one. But what if assigning a user to a OU is assumed a permission to this OU entities for an application? Maybe we can create a default 'Other' OU for this reason.

**Comment by vitorlacerda** [comment]
I think that default 'Other' OU is the best solution.
Sent from my HTC Butterfly

----- Reply message -----

**Comment by vitorlacerda** [comment]
Halil,
Are you working on it right now?
Will be exist a dynamic filter for OU entities using the current user? Like soft delete or tenant?

Sent from my HTC Butterfly

----- Reply message -----

**Comment by hikalkan** [comment]
Hi,

Not starting right now but thinking to start in a short time. Yes, a dynamic and automatic filter based on user's allowed OUs seems a good idea. I will consider it to implement, but without adding much complexity since it's complicated than soft delete and tenant id. Here, user-OU relation is many-to-many.

**Comment by vitorlacerda** [comment]
Halil,
I know this is complex but would make the infrastructure of user/permissions perfect!! :-)

Only missing a user owner for entities and his filter/permissions. Rsrsrsrs..



Sent from my HTC Butterfly

----- Reply message -----

**Comment by vitorlacerda** [comment]
Hi Halil,

On My Project, a User belong to 1 or + OU (Organization Unit). 

Entities like "Sales" implements "IMustHaveOU" interface.

public interface IMustHaveOU
{
public Guid OrgUnitId {get;set;}

[ForeingKey("OrgUnitId")]
public OrgUnit OrgUnit {get;set;}
}

I want to create a DynamicFilter to filter entity that implement this interface using OU's from Current User (AbpSession).

So, I extend "User" class

public class User : AbpUser<Tenant, User>
{
public virtual ICollection<OrgUnit> OrgUnits{ get; set; } //List of OU that user belongs
}

The question is?

How can i get User navigation from AbpSession?

How can i use AbpSession.User.OrgUnits (List) on Dynamic filter?

protected override void OnModelCreating(DbModelBuilder modelBuilder)
{
base.OnModelCreating(modelBuilder);
modelBuilder.Filter("OuFilter", (IMustHaveOU entity) => AbpSession.User.OUList.Contains(entity.OrgUnitId), null);
}


Is this a good approach? this will create a "IN" clause on SQL?

Thanks 

Vitor Lacerda

**Comment by hikalkan** [comment]
@vitorlacerda 
I tried to answer it on the forum: http://forum.aspnetboilerplate.com/viewtopic.php?f=2&t=646&p=2169#p2169

**Comment by hikalkan** [comment]
I created a branch (dev-81-ou) and started working: https://github.com/aspnetboilerplate/module-zero/tree/dev-81-ou

**Comment by vitorlacerda** [comment]
Hi Halil,
awesome!
I will upgrade my project when you finish.

Thanks!

Vitor Lacerda

**Comment by buaziz** [comment]
I can see that you are working on this feature now and wanted list some ideas that some you might find useful to incorporate in module zero.

* an OU can have global settings (root OU settings)
* an OU can have custom settings
* an OU can inherit parent settings
* an OU can have Entities
* an Entitiy that implements IMustHave or IMayHave  OU,  is auto filtered.
* Fire Event : when a User is Moved from one OU to another. (to log it or do other things)
* a Parent OU can list Child OU Entities and Users
* an OU can have Roles 
* an OU can inherit Parent Roles
* OrganizationAuthorize Attribute that inherits Abp Authorize and accepts OU Code or Id

this is just off the top of my head, and I will update this list if interested.

**Comment by hikalkan** [comment]
Thank you @buaziz for your comments. They are valuable since I'm at the beginning of development.
I think to implement it simple at the beginning. Then we can consider to add per-OU settings, roles and their inheritance.

One thing:

"OrganizationAuthorize Attribute that inherits Abp Authorize and accepts OU Code or Id"

In this case there should be static OUs which we know their Code/Id on development and they can not be deleted by users.
I thought OUs completely dynamic. They can be created/deleted on User Interface. So, we can't know Code/Id on development.
If we need it, it's better to relate permissions to OUs. So, we check a permission. And if user in a OU which have this permission, the user is granted. But this is also not considered in first release.

**Comment by buaziz** [comment]
Another thought:  **Groups**

when Active Directory is reimplemented in Azure as Azure Active Directory the Identity team scraped OUs and just created [Azure AD Groups.](https://azure.microsoft.com/en-us/documentation/articles/active-directory-manage-groups/)

* Groups can contain **Users**
* Groups can contain **other Groups**
* Groups can have **Roles**
* Groups can have **Owners**

this fulfils most applications and any other specifics like hierarchy or Managers can be implemented in each application business logic.

**Comment by hikalkan** [comment]
@buaziz this Groups thing looks like what I'm implementing. (I edited the first comment: #issue-89013601). Thanks.

**Comment by hikalkan** [comment]
See document: http://www.aspnetboilerplate.com/Pages/Documents/Zero/Organization-Units
