### ISSUE TITLE
How Create Tenant And Get Id ?

### ISSUE THREAD

**Issue by mona6767** [aspnetboilerplate/module-zero#83]
Hi

Best Regard ,

how Create Tenant,And Get Id ,like "InsertAndGetIdAsync" ?

l want create Tenant and get id for inset in other tables in One Method in MyAppService !

Please Help Me.

very thank you .

**Comment by hikalkan** [comment]
EF requires saving changes in DbContext in order to get Id of an inserted entity. Call SaveChangesAsync after inserting Tenant. See http://www.aspnetboilerplate.com/Pages/Documents/Unit-Of-Work#DocUowSaveChanges

Beside this, if you're inserting directly to the repository, it has InsertAndGetIdAsync method. But I sugges to use TenantManager.

**Comment by mona6767** [comment]
thank you , 
but error is :
-----------------------------
System.Data.Entity.Infrastructure.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.Entity.Core.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Cannot insert explicit value for identity column in table 'AbpTenants' when IDENTITY_INSERT is set to OFF.
----------------------------
when want create Tenant , on myService with "_tenantManager" !!!!

can you help me ?

very thank you .

**Comment by hikalkan** [comment]
Strange.. Can you share the code create the tenant and use tenantmanager's create method.

**Comment by mona6767** [comment]
code : 
var tenantResult = await _tenantManager.CreateAsync(new Tenant(tenancyName,name));
 
but error :
Cannot insert explicit value for identity column in table 'AbpTenants' when IDENTITY_INSERT is set to OFF.

**Comment by mona6767** [comment]
hi ,

i think this problem for my edit on Tenant Class : 

        [ForeignKey("TenantId")]
        public virtual TenantInfo Info { get; set; }

when remove this class, Succefully Created !

-----
how add "Info class" for more details in Tenant Class ? (and User Class ?)

i want get INFO (more details class) , when Find (Tenand or User ) in myRepository ?

**Comment by mona6767** [comment]
public class Tenant : AbpTenant<Tenant, User>
    {

        [ForeignKey("TenantId")]
        public virtual TenantInfo Info { get; set; }
        public override string ToString()
        {
            return string.Format("[Tenant {0}] {1}", Id, TenancyName);
        }

        protected Tenant()
        {

        }

        public Tenant(string tenancyName, string name)
            : base(tenancyName, name)
        {


        }
    }

**Comment by hikalkan** [comment]
Hi,

OK, now it's clear. Do not define such a foreign key. What's inside TenantInfo? Why don't you move it's properties into Tenant? That's more nature.

**Comment by mona6767** [comment]
hi , 
i want add more properties on User (example : MobileAlias,IsFemale,Fax,...) and more detail on Tenant (example : CompanyName,AdditionalInfo,...) !

what is the best method?
-new class (info) and use relation ?
-add this items on Tenant class or User class ?

very thank you .

**Comment by hikalkan** [comment]
Just add they to the User and Tenant classes, do not create additional classes.
After adding properties, don't forget running "Add-Migration" command.

**Comment by mona6767** [comment]
i do this .

very very thank you .

**Comment by hikalkan** [comment]
You're welcome ;)
