### ISSUE TITLE
CREATE DATABASE statement not allowed within multi-statement transaction.

### ISSUE THREAD

**Issue by xbuilder** [aspnetboilerplate/module-zero#85]
I Run the sample with database localdb 2012,but there is a error:

```CREATE DATABASE statement not allowed within multi-statement transaction.```

My connectionString like this:

```connectionString="Server=(localdb)\v11.0; Database=ModuleZeroSampleProject; Trusted_Connection=True;"```

**Comment by emaish** [comment]
Creat database manualy before migration, this is what i do to avoid this issue

**Comment by hikalkan** [comment]
Thanks @emaish 

Yes, creating db manually solves the problem. Actually, this is an exception of EF, not directly related to ABP.
Thanks.

**Comment by xbuilder** [comment]
@emaish @hikalkan 
Thanks,
