### ISSUE TITLE
RemoveFromRoleAsync doesn't work !

### ISSUE THREAD

**Issue by behiunforgiven** [aspnetboilerplate/module-zero#86]
I can't Remove user Roles by RemoveFromRoleAsync !

this function do nothing !

    public async Task DeleteRolesAsync(List<string> deleteList, long userId)
       {
            foreach (var roleName in deleteList)
               {
                   IdentityResult deletionResult = await _userManager.RemoveFromRoleAsync(userId, roleName);
               }
    }

**Comment by hikalkan** [comment]
Also, there is a problem with AddToRole.

**Comment by hikalkan** [comment]
As I tested. These are working in the latest version.
