### ISSUE TITLE
Navbar configuration

### ISSUE THREAD

**Issue by lesliechen5705** [aspnetboilerplate/module-zero#88]
Hi, I've just downloaded the boilerplate using Angular js and Entity framework, but I'm confused on how to "not show certain menu items based on roles".

For e.g. I have a Admin role that should see the menu item but not for normal users.

How can I accomplish that? Thanks.

**Comment by emaish** [comment]
by providing permission name in the menu item, check the documentaion http://www.aspnetboilerplate.com/Pages/Documents/Navigation
