### ISSUE TITLE
How Get RoleName for user ?

### ISSUE THREAD

**Issue by mona6767** [aspnetboilerplate/module-zero#90]
hello , best regard .

i want get user by tenant , and get full roles details , (RoleName , RoleDisplayname) !

how can this ????

thank you .

**Comment by hikalkan** [comment]
Hi,

You can use _userManager.GetRoles to get role names then for each role name call _roleManager.GetRoleByName.

For a better performance, you can get _userManager.Users (which is IQueryable) and _roleManager.Roles  (which is IQueryable) and write some join LINQ.

**Comment by mona6767** [comment]
how use for get user and role (role by RoleName) in one Query ?

(( exactly like : demo.aspnetzero.com/Application#/users ))

thank you .

**Comment by hikalkan** [comment]
I did not get it in one query, instead, I got users in one query and found distinct role ids. Than I executed a second query to get role names for these ids.

**Comment by hikalkan** [comment]
If you want exact code of ASPNET Zero, than I can share it:

        private async Task FillRoleNames(List<UserListDto> userListDtos)
        {
            /* This method is optimized to fill role names to given list. */

            var distinctRoleIds = (
                from userListDto in userListDtos
                from userListRoleDto in userListDto.Roles
                select userListRoleDto.RoleId
                ).Distinct();

            var roleNames = new Dictionary<int, string>();
            foreach (var roleId in distinctRoleIds)
            {
                roleNames[roleId] = (await _roleManager.GetRoleByIdAsync(roleId)).DisplayName;
            }

            foreach (var userListDto in userListDtos)
            {
                foreach (var userListRoleDto in userListDto.Roles)
                {
                    userListRoleDto.RoleName = roleNames[userListRoleDto.RoleId];
                }
            }
        }

I do it like that.

**Comment by mona6767** [comment]
very very thank you !!!

this exactly .. 

thank you .
