### ISSUE TITLE
Localization Enhancement for module-zero (database based localization)

### ISSUE THREAD

**Issue by matxhe** [aspnetboilerplate/module-zero#91]
Hi @hikalkan ,

http://www.aspnetboilerplate.com/Pages/Documents/Localization
After I study the Localization, It's very good design and extentable, thanks for your great job again!

But in the Muli-Tenancy, different tenant may want their own localized text on same laguage, any way to fix this scenario on module-zero,TQ

**Comment by hikalkan** [comment]
Hi,

Sorry for the late response. That's strange, I haven't thought and needed it before :)
I always assumed same text always localized as same. Because that is UI localization, not content localization. In that case, localizations should be located in the database. You can create a custom ILocalizationSource and get strings from database based on given text and current tenant. That's the only way currently.

**Comment by gentledepp** [comment]
I think the idea is that each tenant may call the same thing differently.
Like you have some "defect" reporting system.
For some tenant this might be called "issue", and for another "finding" and for yet another "error" or whatever.
You see? :)

**Comment by hikalkan** [comment]
I'm working on a database based localization source which will allow to customize languages and localization texts per tenant. I will try to complete it in 2 weeks. It's core will be implemented in module zero project (and I will prepare UI on aspnetzero.com project).

**Comment by talkwaqar** [comment]
so this is exactly what I asked last time about this.... that some people can say "Basket" some people can use "Shopping Cart"

**Comment by emaish** [comment]
Dear Halil,
could you clarify how to use that feature ?

**Comment by hikalkan** [comment]
I will document it soon. As a brief, you will use IApplicationLanguageManager and IApplicationLanguageTextManager to manage languages and texts.

**Comment by hikalkan** [comment]
See https://github.com/aspnetboilerplate/module-zero-template/commit/44584c9378a8fd78f97e900446d9f6d6b265f2f0 to enable it.
