### ISSUE TITLE
How to get permissions from database?

### ISSUE THREAD

**Issue by gregoriusxu** [aspnetboilerplate/module-zero#93]
Hi:
      First of all,my english is not well,so i wish you can understand the question.
I am going to get permissions from database by EF,I use this code bellow,but i think this way is not very well:

            var rolepermissionslist = IocManager.Instance.Resolve<RoleManager>().GetPermissions();
            var permissionmanager = IocManager.Instance.Resolve<IPermissionManager>();
            if (permissionmanager.GetAllPermissions().Count == 0)
            {
                MethodInfo oMethod = permissionmanager.GetType().GetMethod("CreatePermission", BindingFlags.Instance | BindingFlags.Public);
                var paremeters = oMethod.GetParameters();
                var usermanager = IocManager.Instance.Resolve<UserManager>();
                var userpermissionlist = usermanager.GetAllPermission();
                foreach (var permission in userpermissionlist)
                {
                    oMethod.Invoke(permissionmanager, SetParameter(paremeters, permission));
                }

                foreach (var permission in rolepermissionslist)
                {
                    oMethod.Invoke(permissionmanager, SetParameter(paremeters, permission));
                }
            }

I cannot use the PermissionManager's CreatePermission method,so i use reflection method,is there a better way to finish
this function?
thank you

**Comment by gregoriusxu** [comment]
I have another question ,how to delete tenant user by host?

**Comment by hikalkan** [comment]
Hi,

Have you seen http://forum.aspnetboilerplate.com/viewtopic.php?f=3&t=367 ?
Why you want to get permissions from database. If a permission is not used in the code, it's meaningless.

To delete a tenant user, you can change IMayHaveTenant filter's value to the tenant's id (http://www.aspnetboilerplate.com/Pages/Documents/Data-Filters#DocSetFilterParams). Then you can use UserManager to get and delete the user.

**Comment by gregoriusxu** [comment]
I have read it,but this is maybe only for mpa?i find that in the demo project of spa,permissons is  init by hard code for client script.I use you method to delete user,but it not work,no data found

**Comment by hikalkan** [comment]
Have you find your answer? If not, can you please share more detail. Where is it hard-coded? Can you show some code. Thanks.

**Comment by hikalkan** [comment]
You can re-open it if you need ;)

**Comment by gregoriusxu** [comment]
@hikalkan 
    Hi,sorry for late post,in the demo project,these is a ModuleZeroSampleProjectAuthorizationProvider class,but the permission is init by the code bellow:
            context.CreatePermission("CanCreateQuestions", new FixedLocalizableString("Can create questions"));
            context.CreatePermission("CanDeleteQuestions", new FixedLocalizableString("Can delete questions"));
            context.CreatePermission("CanDeleteAnswers", new FixedLocalizableString("Can delete answers"));
            context.CreatePermission("CanAnswerToQuestions", new FixedLocalizableString("Can answer to questions"), isGrantedByDefault: true);
In my project,this permission is configed in the table of abppermission table of database,i want to config it in pages and read it from database here,is that right?
