### ISSUE TITLE
Not Login when use "_userManager.LoginAsync" !!!!

### ISSUE THREAD

**Issue by mona6767** [aspnetboilerplate/module-zero#94]
hello , 

i use your example "ModuleZeroSampleProject" ,and use login method in accountController !

but always Result is :  " AbpLoginResultType.InvalidPassword"  !!!

whats problem !??????????

thank you .

**Comment by hikalkan** [comment]
Default password is 123qwe
It works for me. Have tried it?

**Comment by mona6767** [comment]
very very try it !!

i think has a problme !!!

4 try . to update-database !! 
and more for test any password and user !!!

**Comment by mona6767** [comment]
neet to _multiTenancyConfig.IsEnabled = true ? or false ?

**Comment by hikalkan** [comment]
For sample project, multitenancy is disabled.
If you want to start a new project, just create from template (not from sample project): http://www.aspnetboilerplate.com/Templates (select ABP + module zero).
I'll check the sample project.

**Comment by hikalkan** [comment]
I just downloaded ModuleZeroSampleProject (https://github.com/aspnetboilerplate/module-zero/tree/master/sample), created database using "Update-Database", run the application and logged in using admin and 123qwe
I could not see any problem.

**Comment by mona6767** [comment]
You are right

But I'm a customized project, so I'll find the problem !!

when i update some nuget , This problem occurred ..

very thank you for your time .

**Comment by hikalkan** [comment]
OK, then I will check by updating project.

**Comment by mona6767** [comment]
hi,

i find the problem ... :)

=> i add some field to "User class" , and The wrong is Repeated "public virtual string Password { get; set; }"

when remove this , problem solved !

very thank you .
