### ISSUE TITLE
Permissions CRUD using entityframework

### ISSUE THREAD

**Issue by chujzaurus** [aspnetboilerplate/module-zero#96]
Hello! Can you tell me a way, how can I use ABP provided tools to add/edit/remove/check permissions for different user roles? I am having a hard time dealing with this and I can't find any good examples on it. Thank you!

**Comment by wocar** [comment]
Hello!
Did you already have a look to the document regarding
permissions/authorization?

http://aspnetboilerplate.com/Pages/Documents/Authorization

You might also find useful the Role management guide:

http://aspnetboilerplate.com/Pages/Documents/Zero/Role-Management

Also here are is a demo application that might help you:
https://github.com/aspnetboilerplate/sample-blog-module

Regards,
William Obando

**Comment by chujzaurus** [comment]
Hello!

Yes, I've read these. I am not really sure how Tenant - Role - User - Permissions relationship work. 

For example: I have 2 tenants, each tenant have different roles. I want users to be assigned to roles, to get their permissions. 

The main problems I face are:
How to get currently granted permissions for a role.
How to grant a permission to a role. 

I am expecting it to be working on the database level: Storing permissions for each role in a table. 

Can I get an example of practical approach to these problems? 

Maybe I am missing something and trying to use ABP provided tools in a wrong way? 

Thank you!
