### ISSUE TITLE
Permission checking for role

### ISSUE THREAD

**Issue by ducfobhas** [aspnetboilerplate/module-zero#97]
Good evening. Can someone tell me how can I check granted permissions for users role? AbpMvcAuthorize("permissionName") doesn't work. I guess it works for only users permissions. But what about role permissions?

**Comment by hikalkan** [comment]
It works for both permissions of roles of the user and permissions of the user. But user specific permission overrides roles (http://www.aspnetboilerplate.com/Pages/Documents/Zero/Permission-Management)

**Comment by ducfobhas** [comment]
But in my case, I haven't set any user permissions, only role permissions and it looks like my role permissions are totally ignored. Is there any way I can debug it? Like getting a list of currently applied user permissions?

**Comment by langman66** [comment]
You can debug through all the code.  I've asked this question on debugging and hikalkan provided some links to using debug symbols. Search for how to debug and you should find the link.    In my case I actually don't use the nuget packages but rather the actual source code.  If you use the source code then you'll have to manage keeping all your code in sync along with changing all the references.  I find having all the code in my solutions makes learning the framework much easier and quicker to hunt down issues.

**Comment by ducfobhas** [comment]
I know how to debug, but i'm not sure where to even look, thats where i need advice. Maybe i should prohibit all users permissions and then grant role permissions?

**Comment by ducfobhas** [comment]
For example: 

        public bool UserHasPermission(string permissionName)
        {
            return _userRepository.GetAllList(x => x.Permissions.Any(z => z.Name == permissionName && z.UserId == AbpSession.UserId)).Any();
        }

        [HttpGet]
        [AbpMvcAuthorize("TestPermission")]
        public ActionResult Index()
        {
            bool ThisIsAlwaysFalse = UserHasPermission("TestPermission");
            return View();
        }

Method that requires permission, can be run and it can execute method that checks if user has permission and its always false. I don't understand. Also this permission name is imaginary. What am I missing?

**Comment by wocar** [comment]
You can find an answer in the documentation:
http://aspnetboilerplate.com/Pages/Documents/Authorization

Create the permissions:

public class MyAuthorizationProvider : AuthorizationProvider
{
    public override void SetPermissions(IPermissionDefinitionContext
context)
    {
        var administration = context.CreatePermission("Administration");

        var userManagement =
administration.CreateChildPermission("Administration.UserManagement");

userManagement.CreateChildPermission("Administration.UserManagement.CreateUser");

        var roleManagement =
administration.CreateChildPermission("Administration.RoleManagement");
    }
}

Check the permissions:

[AbpAuthorize("Administration.UserManagement.CreateUser")]
public void CreateUser(CreateUserInput input)
{
    //A user can not execute this method if he is not granted for
"Administration.UserManagement.CreateUser" permission.
}

To assign permissions to users you can inject the UserManager and call
GrantPermissionAsync();

Regards

**Comment by hikalkan** [comment]
@ducfobhas,

Yes, delete all entities in AbpPermissions with UserId. This will reset all user specific permission settings. Then, only role permissions is used. Thus, you can see the difference.

**Comment by ducfobhas** [comment]
Yeah well that didn't help. Nothing changed, i did everything exactly by documentation. Permissions are still ignored. What else could affect it? Maybe multitenancy has any effect?

**Comment by ducfobhas** [comment]
The problem was probably in getting the roles. Async method was going on forever without any response for some reason, so I just wrote my own authentification/roles and permissions system. Thanks anyways.
