### ISSUE TITLE
Spelling mistake on http://www.aspnetzero.com/Faq

### ISSUE THREAD

**Issue by natiki** [aspnetboilerplate/module-zero#98]
Hi Halil,

![image](https://cloud.githubusercontent.com/assets/4738140/9381837/7740c5ee-477e-11e5-8f9a-1f3e35af9987.png)

I think you mean "chosen" as opposed to "choosen".

PS. I would be happy to proof read the site if you would like. I am a native English speaker, but cannot speak a word of Turkish ;-). I do however speak Afrikaans. *grin*

**Comment by hikalkan** [comment]
Thanks a lot for informing. I will fix it :)
It's appreciated if you find spelling mistakes. But this can get your time. So, if you just see a mistake, share with me. But not spend time to fully read the all docs.

**Comment by natiki** [comment]
Its not a problem, I will do it and let you know. You made ABP available it is the least I can do :-)
