### ISSUE TITLE
Warning after pulling module zero download and building it....

### ISSUE THREAD

**Issue by natiki** [aspnetboilerplate/module-zero#99]
Hi,

Not a biggie... Downloaded the template using http://www.aspnetboilerplate.com/Templates. First build produces warning below. Ideally it should be updated so that warning is not generated.

```
App_Start\PraktisWebModule.cs(24,21,24,42): warning CS0618: 'Abp.Localization.Sources.Xml.XmlLocalizationSource' is obsolete: 'Directly use DictionaryBasedLocalizationSource with XmlFileLocalizationDictionaryProvider instead of this class'
5>  Praktis.Web -> E:\DataSyncPoint\DJE\Natiki\Clients\Praktis\FrontEnd\Praktis.Web\bin\Praktis.Web.dll
```

**Comment by hikalkan** [comment]
OK, then we should update the template. Thanks :)

**Comment by hikalkan** [comment]
I resolved it: https://github.com/aspnetboilerplate/module-zero-template/commit/8cf1767227a1e83162efa371450319d9e72997f0
Thanks again.
